### PR TITLE
report: new styling for audit details

### PR DESCRIPTION
**Pull request by paulirish**
* remove the collapsible details/summary control entirely.
* new colors.
* make sure we're always max 100% width.

image

### example reports:

https://venomous-horse.surge.sh/cnn.html
https://venomous-horse.surge.sh/dbwtester.html
https://venomous-horse.surge.sh/errors.html
https://venomous-horse.surge.sh/example.html
https://venomous-horse.surge.sh/paulirish.html
https://venomous-horse.surge.sh/tinyhouse.html

https://venomous-horse.surge.sh/z.devtools.cnn.html
https://venomous-horse.surge.sh/z.devtools.dbwtester.html
https://venomous-horse.surge.sh/z.devtools.errors.html
https://venomous-horse.surge.sh/z.devtools.example.html
https://venomous-horse.surge.sh/z.devtools.paulirish.html
https://venomous-horse.surge.sh/z.devtools.tinyhouse.html

### CODE REVIEW

**Comment by patrickhulce** [comment]
❤️ this. so. much.

**Comment by vinamratasingal** [comment]
Looks great!!! 

cc: @hwikyounglee

**Comment by paulirish** [comment]
@hwikyounglee does this work for you?

it's this instead of trying expand/collapse within details like these mocks
screen shot 2018-05-07 at 12 36 18 pm

the parent already collapses and the only usecase is: "i only want to see the audit description, but not the details stuff below it."  meh.

**Comment by hwikyounglee** [comment]
Yes, having one collapse/expand LGTM. Thanks!!!

**Pull request merged**
