### PR TITLE
core(iframe-elements): remove from default config

### PR DESCRIPTION
**Pull request by connorjclark**
Shouldn't be in the default.

### CODE REVIEW

**Comment by brendankenny** [comment]
it has to be in the default config so that plugins can use it. To make it so we aren't saving extra artifacts when not needed, we'll need to either dynamically add them to the config when requested by plugins (extra complexity) or do #7787 (downsides listed there).

pegg

**Comment by connorjclark** [comment]
oh i c

**Comment by jburger424** [comment]
this makes perfect sense to me, but we were planning on publishing an npm package using the new LH gatherer (hopefully today!) and this will break us if people use a future version of LH with us as a plugin. Any way I can help to ensure one of the above fixes makes it into the next version?

**Comment by brendankenny** [comment]
> this makes perfect sense to me, but we were planning on publishing an npm package using the new LH gatherer (hopefully today!) and this will break us if people use a future version of LH with us as a plugin. Any way I can help to ensure one of the above fixes makes it into the next version?

I don't think anyone is overly concerned about it yet since the IFrameElements gatherer isn't too intensive. I think in the end the solution will be thinking around #7787 to find a way to make it ergonomic for our biggest use cases (after the main one, which should work fine with it today :)

**Pull request closed without merging**
