### PR TITLE
cli: do not set AutofillShowTypePredictions

### LINKED ISSUE #11985: --enable-features=AutofillShowTypePredictions messes with accessibility results
I've banged my head against this for too long, gotta call it a night, but happy to nerd snipe someone else if they're up for it 😅 Basically, Lighthouse running axe from CLI is returning different results (missing an `<input>` that lacks a label) than every other channel. PSI, DevTools, and *evaluating the exact string that Lighthouse `evaluteAsync`s in the console* all successfully find the label issue. The smoke test for the same axe rule is working just fine. I'm totally at a loss for what's going on at this point.

Originally inspired by [my failing FR CI test](https://github.com/GoogleChrome/lighthouse/pull/11975/checks?check_run_id=1738355009#step:10:190) but this is a regular Lighthouse issue too. Can anyone else repro locally?

#### Provide the steps to reproduce
1. Run LH on http://melodic-class.glitch.me/axe-label.html
  
#### What is the current behavior?

Lighthouse marks "Form elements have associated labels" as passed.

#### What is the expected behavior?

Lighthouse marks "Form elements have associated labels" as failed.

#### Environment Information
* Affected Channels: CLI only (AFAICT)
* Lighthouse version: master
* Chrome version: Canary and stable
* Node.js version: v12
* Operating System: macOS + Linux

### PR DESCRIPTION
**Pull request by connorjclark**
fixes #11985

### CODE REVIEW

**Comment by brendankenny** [comment]
should all traces of it be removed?

like

https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js#L44-L46

and

https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js#L531

and

https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-core/lib/page-functions.js#L141-L143

and anything in those PRs that doesn't just match a `AutofillShowTypePredictions` search?

**Comment by connorjclark** [comment]
> should all traces of it be removed?

No, I don't think so.

> 
> like
> 
> https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js#L44-L46
> 

There's still a smoke test for this experimental audit.

> 
> https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js#L531
> 


same

> 
> https://github.com/GoogleChrome/lighthouse/blob/5c32e645d4cee10731cd8cd20f3b65cb41341ea6/lighthouse-core/lib/page-functions.js#L141-L143
> 
> and anything in those PRs that doesn't just match a `AutofillShowTypePredictions` search?

still supporting experimental usage, should anyone care..

We could remove more but this is the minimal to have any impact. Anything else might be churn (removed but brought back later).

**Comment by connorjclark** [comment]
Ahhhh I assume the chrome flags being set in the smoke test runner would apply to all, but that is just `bundle.js`. The normal run of smoke tests uses the regular chrome launching...

Add the flag to `cli.js`, or just remove/comment out form smoke tests?

**Review by adamraine — APPROVED** [review]

**Comment by brendankenny** [comment]
> still supporting experimental usage, should anyone care..

FWIW historically we've been in this exact position with an unsupported feature hidden by a flag that no one owns like two or three times now and it always ends up the same way.

**Pull request merged**
