### PR TITLE
Fix errorManifest call

### PR DESCRIPTION
**Pull request by boopathi**
+ Fixes erroManifest call when there is no manifest file found

### CODE REVIEW

**Comment by samccone** [comment]
Hey @boopathi would you mind taking the approach @paullewis did here
https://github.com/GoogleChrome/lighthouse/pull/156/files#diff-46cbbb0c89e355119012db6ee6226afbR67

and just converting the this calls the Manifest

And then just adding a test to ensure this does not regress?  :)

+100

**Comment by paullewis** [comment]
Yeah, if you can do this we can merge and I'll rebase mine on top of it! Thanks for the PR :dart:

**Comment by boopathi** [comment]
There are no tests for gatherers ?

**Comment by samccone** [comment]
not yet, +1 to land this and we can add tests

**Pull request merged**
