### PR TITLE
fix: table formatter image preview URL encode

### PR DESCRIPTION
**Pull request by patrickhulce**
R: @ebidel all

Image previews were broken for URLs with `)` since markdown can't handle them

Before
image

After
image

### CODE REVIEW

**Comment by brendankenny** [comment]
upstream issue: https://github.com/chjj/marked/issues/619 (looks like it won't be fixed)

**Comment by patrickhulce** [comment]
FWIW in defense of marked I think it's actually an artifact of the markdown spec itself. There's no guarantee in an arbitrary link that an opening paren will be followed by a close paren.

Also relevant http://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses

**Comment by ebidel** [comment]
🚫 🖼

**Comment by brendankenny** [comment]
> the markdown spec itself

"spec" :)

**Pull request merged**
