### PR TITLE
misc: fix typo in comment

### PR DESCRIPTION
**Pull request by charisTheo**
**Summary**
Fixing a typo inside commented code.

### CODE REVIEW

**Comment by charisTheo** [comment]
@googlebot I signed it!

**Comment by patrickhulce** [comment]
C'mon @googlebot pick up the pace! :)

**Comment by connorjclark** [comment]
hmmm @charisTheo can you double check the stuff under "What to do if you already signed the CLA"?

**Comment by patrickhulce** [comment]
What's the status here?

@charisTheo does everything look good on your end in the Googlebot links?

> Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

@connorjclark on your end is it just showing up as no CLA still?

Sorry for the annoyance here @charisTheo I know it's just a simple 1-character fix 😅

**Comment by charisTheo** [comment]
I'm actually a Googler but this commit was signed with my personal email instead. 

Indeed it's a one character fix so let me not keep you more on this, since I will need to file a ticket to get access to Github OSS.

**Comment by patrickhulce** [comment]
Ah! That's funny :)

Maybe just `git commit --amend --author="Charis Theo <YOURLDAP@google.com>" && git push -f` fixes us here then?

**Comment by charisTheo** [comment]
@googlebot I signed it!

**Comment by brendankenny** [comment]
hmm, @charisTheo, are you able to add yourself on go/github?

**Comment by charisTheo** [comment]
> hmm, @charisTheo, are you able to add yourself on go/github?

No I don't have access there. I've just submitted a ticket.

**Comment by charisTheo** [comment]
@googlebot I signed it!

**Comment by charisTheo** [comment]
@connorjclark the Google bot doesn't seem to be capturing the new email I have put in my Github account. 
Should I go ahead and close this and open another PR that has a commit with the google email?

**Comment by patrickhulce** [comment]
Oof, yeah that might be best @charisTheo. #longesttypofixever 😄  just make sure the commit itself is also authored using your google email when it's first pushed too?

**Pull request closed without merging**
