### PR TITLE
tests: run every smoke test (except forms) for bundle

### PR DESCRIPTION
**Pull request by connorjclark**
ref https://github.com/GoogleChrome/lighthouse/pull/11463#issuecomment-700981945

### CODE REVIEW

**Comment by patrickhulce** [comment]
should we split this out so basics isn't *all smokes* plus the basics?

**Review by patrickhulce — APPROVED** [review]
perfect thanks @connorjclark!

**Comment by patrickhulce** [comment]
(though one is failing)

**Comment by connorjclark** [comment]
The forms failure makes no sense ... banging my head against the wall on this one :/

**Comment by connorjclark** [comment]
Whatever it is, that audit is in experimental, and may receive a refactor that will remove the issue here, so I'm just going to exclude forms form the bundle test for now.

**Pull request merged**
