### PR TITLE
[Proposal] Report downloaded but offscreen images

### PR DESCRIPTION
**Pull request by mixed**
## Motivation

When I have analyzed load performance using devtools Almost performance bottleneck was network(images...). So, I have checked invisible image and applied lazy load image. I think that This practice is common sense.
## How to make it?

I have filtered image that checked size, position. So, I think that LH(LightHouse) have to support options size and position of image. If I ran LH that I think LH have to suggest perf enhance point. So. LH support 2 features.
- support option (size, position)
- perf enhance point

I have made prototype. What do you think about this feature?

image

reference)
- [AMP Prioritize resource loading](https://www.ampproject.org/learn/how-amp-works/#prioritize-resource-loading)
- [Lazy loading image library in github](https://github.com/search?l=JavaScript&q=lazy+image+loading&ref=searchresults&type=Repositories&utf8=%E2%9C%93)
- [Lazy loading image article in google](https://www.google.co.kr/search?q=Lazy+loading+image&oq=Lazy+loading+image&aqs=chrome..69i57j0l5.1281j0j4&sourceid=chrome&ie=UTF-8)

### CODE REVIEW

**Comment by brendankenny** [comment]
hi @mixed!

To clarify here, by "invisible" do you mean offscreen? And why do you not bother with images smaller than a certain size (70x70 by default)?

**Comment by mixed** [comment]
Hi. @brendankenny 
- Yes. Invisible image means offsetscreen but It can boundary range using [options](https://github.com/GoogleChrome/lighthouse/pull/821/commits/4e8692f43c9e6fbc04fe2c239375f88449c2fd5c#diff-b8e76f1137b1f350d675e8c5cc1ed3b6R17). Though image display outside of screen. Image have to load because of ux.

- Um... When I made this feature I found too many images. So I removed small size images. but I seem to better include smaller size images. Thanks. 👍

**Comment by paulirish** [comment]
I retitled this PR just slightly

**Comment by paulirish** [comment]
okay first up.. **huge apologies.** This PR sat here untouched mostly because it was big and we were scared to take it on. 😨 

The feature is very much desired and I apologize, both personally, and on behalf of the other maintainers, for not acknowledging this PR and providing feedback. 😭 😢 

-----------

For better or for worse, though.. we can now close the PR as #1807 has landed and covers the same approach. I know patrick looked at this code for inspiration, so it was very valuable to have here. 😅 

❤️ ❤️

**Comment by mixed** [comment]
@paulirish 
I`m OK because it helps #1807 PR. :)

**Pull request closed without merging**
