### PR TITLE
docs: add Code of Conduct to project

### PR DESCRIPTION
**Pull request by jivthesh**
**Summary**

### CODE REVIEW

**Comment by brendankenny** [comment]
hi @jivthesh,

This is a good idea but we'll want to use the general Google open source code of conduct, not the Chromium one. It's provided at https://opensource.google/docs/releasing/template/CODE_OF_CONDUCT/, but as HTML, not as markdown.

Here's a version that has the raw markdown: [`CODE_OF_CONDUCT.md`](https://raw.githubusercontent.com/google/intellij-gn-plugin/3703a34069c0e75408029325aa8fa64894570b9b/CODE_OF_CONDUCT.md).

- [ ] `PROJECT NAME` needs to be replaced with `'Lighthouse'`
- [ ] I'll get back to you later today about what to put for `'PROJECT STEWARD NAME(s) AND EMAIL(s)'`

**Comment by jivthesh** [comment]
@brendankenny shall i close this and the proper one?

**Comment by brendankenny** [comment]
You could also edit and push this PR, but it's up to you.

**Comment by jivthesh** [comment]
@brendankenny i have made another pr pls check

**Comment by jivthesh** [comment]
@brendankenny  after getting PROJECT STEWARD NAME(s) AND EMAIL(s) i will reedit this

**Comment by jivthesh** [comment]
@brendankenny what to put in PROJECT STEWARD NAME(s) AND EMAIL(s)

**Comment by jivthesh** [comment]
@brendankenny  project name?

**Comment by brendankenny** [comment]
> @brendankenny what to put in PROJECT STEWARD NAME(s) AND EMAIL(s)

After looking at what other Google projects are [putting there](https://github.com/search?l=Markdown&q=org%3Agoogle+Google+Open+Source+Strategy+team&type=Code), you can put me as the project steward for now and we can discuss internally how we want to handle this in the future (e.g. an external mailing list instead of a single point of contact).

I've updated the checklist above (https://github.com/GoogleChrome/lighthouse/pull/11212#issuecomment-668632721) with the new substitution as well.

**Comment by patrickhulce** [comment]
Seems like a lot of projects take those responsibilities really seriously ;)

image

**Comment by jivthesh** [comment]
@brendankenny updated please check and inform me if anything has to updated

**Comment by brendankenny** [comment]
something is going on with the `yarn smoke oopif` test. Fails locally as well. Currently looking into it.

**Pull request merged**
