### PR TITLE
i18n: import

### PR DESCRIPTION
**Pull request by adamraine**

### CODE REVIEW

**Review by connorjclark — APPROVED** [review]

**Comment by brendankenny** [comment]
Seems like this has the same problem as that previous PR that it's removing a lot of translated strings, but somehow the english strings are ending up in the locale files?

**Comment by connorjclark** [comment]
We just did a lighthouse stack pack change / modified some strings, but we also just sent those strings to TC, so yea we got english fallbacks.

one day we will automate this tc pipeline :(

**Comment by brendankenny** [comment]
> We just did a lighthouse stack pack change / modified some strings, but we also just sent those strings to TC, so yea we got english fallbacks.

I mean, it's not worse than the way we handled missing strings in the locale file (by falling back to the `en-US` string) since it's the english string either way, but something definitely changed with tc. We used to have untranslated strings up until #11396, now we always have 0 (e.g. https://github.com/GoogleChrome/lighthouse/pull/11494/checks?check_run_id=1184737239#step:16:25). Having an english fallback in each locale file makes that check completely useless, incidentally :)

**Comment by brendankenny** [comment]
Did automation on the google3 side somehow start picking up english fallbacks in each locale?

**Comment by connorjclark** [comment]
We just redid the import/export and saw no change. Seems the data we get from TC is now giving en fallbacks explicitly.

**Comment by brendankenny** [comment]
we'll have to revisit #11149 and #10791 now :/

**Pull request merged**
