### PR TITLE
manifest: Move production dependencies to root manifest.

### LINKED ISSUE #503: Can't run cli on linux: Error: Cannot find module 'handlebars'
$ npm install -g googlechrome/lighthouse
    /usr/local/nodejs/bin/lighthouse -> /usr/local/nodejs/lib/node_modules/lighthouse/lighthouse-cli/index.js
    ...

```
$ lighthouse --help
module.js:442
    throw err;
    ^

Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/nodejs/lib/node_modules/lighthouse/lighthouse-core/report/report-generator.js:22:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Running on a 64bit linux 4.2.0-38-generic:

```
$ node --version
v6.3.0

$ npm --version
3.10.3
```

FWIW the same thing was happening on node v4.

### PR DESCRIPTION
**Pull request by paulirish**
A bit of housekeeping.

This makes sure all of CLI and Core's runtime dependencies are installed directly from the root manifest. This fixes #503 with a much cleaner solution.

devdependencies are kept separate for sanity. The original postinstall (which fails in a `-g` install`) is restored since we have no deps to install in the postinstall. A development install will successfully run the postinstall and do the devdeps.

### CODE REVIEW

**Comment by paulirish** [comment]
Doesn't work. :) core needs to request the deps from a dir higher. :/

**Comment by paulirish** [comment]
> core needs to request the deps from a dir higher.

I'm a little unpracticed with npm module strategies. What's the best way to resolve this? 

This PR has devdeps local to -core but keeps the runtime deps at root. AFAIUI, the module resolution breaks as it finds the -core package.json and expects deps like `require('debug')` to be in -core/node_modules, not the node_modules for root.

Should we just get rid of -core's package.json to simplify all this?

**Comment by wardpeet** [comment]
I think getting rid of the package.json is the only good option. It's normal that it's behaves that way because each package has it's own scope. 

Some options:
1) Use npm link to create a symlink.
2) Override require function so it goes a level deeper than it  should
3) Remove package.json and perhaps create a cli for core with yargs so you have some kind of npm run.

**Comment by paulirish** [comment]
@wardpeet K. I'm sold on that.   Do you think you could help with this? 

Mostly it's a matter of merging the lines of core's package.json into the root. The hardest part looks to be tweaking all the npm scripts to have correct paths and such.

**Comment by wardpeet** [comment]
Sure thing, so basically we want to remove package.json from the core directory? This will fix issues with postinstall not being fired. Another issue rises, the api will not be npm anymore but node if you would build a cli for it.

Is there a reason why it has it's own package.json? We could update the overlapping tasks like (unit, watch, ...) to just expand the search directories so they pick up the core directory as well.

If that's not the case we can create tasks like npm unit:core that runs the specific mocha. Or I create a yargs cli.

My preference goes to updating overlapping tasks.

**Comment by paulirish** [comment]
> Is there a reason why it has it's own package.json?
Because we thought that was improving the modularity of the project. I
suppose the exercise helped, but in reality we need these pieces to be in a
mono-repo. So... whooops. :)  My bad, mostly.

Overlapping tasks yup.

**Comment by wardpeet** [comment]
I have another PR #526  ready for this one

**Pull request closed without merging**
