### PR TITLE
core(fr): clone default categories to avoid modification

### LINKED ISSUE #13334: Lighthouse node module fails with "Error: could not find uses-responsive-images-snapshot audit for category performance" when used with user flows
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

Any URL

### What happened?

Lighthouse report fails to generate when used along with the [User Flow API](https://web.dev/lighthouse-user-flows/), with the following error:

```
node_modules\lighthouse\lighthouse-core\fraggle-rock\config\validation.js:190
        throw new Error(`could not find ${auditRef.id} audit for category ${categoryId}`);
              ^

Error: could not find uses-responsive-images-snapshot audit for category performance
```

To reproduce, simply import the `startFlow` function from `lighthouse/lighthouse-core/fraggle-rock/api.js`, and run normal lighthouse report

Simple repro: 
```
const puppeteer = require("puppeteer");
const fs = require("fs");
const { startFlow } = require("lighthouse/lighthouse-core/fraggle-rock/api.js");
const lighthouse = require("lighthouse");

async function createReportWithBrowser(
  page,
  browser,
  url,
  options = { output: "html" }
) {
  const endpoint = browser.wsEndpoint();
  const endpointURL = new URL(endpoint);
  return lighthouse(
    url,
    Object.assign(
      {},
      {
        port: endpointURL.port,
      },
      options
    )
  );
}

async function measure() {
  const browser = await puppeteer.launch({ args: ["--no-sandbox"] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 1080 });
  await page.setUserAgent(
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
  );

  const result = await createReportWithBrowser(
    page,
    browser,
    "https://www.google.com"
  );

  fs.writeFileSync(`lighthouse_report.html`, result.report, "utf-8");
}

measure().then(() => {
  console.log("done");
});

```

If I remove the `startFlow` import, it starts working again. Is there a way to use the new User Flows API along with normal lighthouse reports?

### What did you expect?

Lighthouse report generation without errors.

### What have you tried?

_No response_

### How were you running Lighthouse?

node

### Lighthouse Version

8.6.0

### Chrome Version

_No response_

### Node Version

_No response_

### OS

_No response_

### Relevant log output

```shell
node_modules\lighthouse\lighthouse-core\fraggle-rock\config\validation.js:190
        throw new Error(`could not find ${auditRef.id} audit for category ${categoryId}`);
              ^

Error: could not find uses-responsive-images-snapshot audit for category performance
```

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #13334 

Just loading user flow code which has the FR default config in transitive deps will trigger this bug, adding a `uses-responsive-images-snapshot` `auditRef` to the perf category of the FR _and_ the legacy configs because the category isn't copied before being altered. Since the audit only occurs in FR runs, the legacy default config then fails validation.

This PR copies the perf category before adding the `auditRef`.

Unclear how far we want to go with `deepClone` here. Just in case, should we clone `settings`, `audits`, and `groups`, too?

### CODE REVIEW

**Comment by adamraine** [comment]
> Just in case, should we clone settings, audits, and groups, too?

Could we just deep clone the entire legacy default config?

**Comment by brendankenny** [comment]
> > Just in case, should we clone settings, audits, and groups, too?
> 
> Could we just deep clone the entire legacy default config?

Technically the default config isn't required to be compatible with a JSON roundtrip, though since the last i18n change to `IcuMessage` I believe what we have is compatible. This might be the simplest and we'll have to worry a lot less about other changes down the line.

Let's just do that, and we'll count on our FR config validation and tests :)

**Comment by adamraine** [comment]
> Technically the default config isn't required to be compatible with a JSON roundtrip

If future changes to the config make it incompatible, are we guaranteed a fatal error?

**Comment by brendankenny** [comment]
No, like functions are dropped as if they never existed, which mainly affects audits and gatherers definitions (which allow `Class`es or instances of classes). `NaN` becomes `null`, `undefined` becomes nothing. None of it is an apparent immediate issue but it's also not something we're looking out for on the config side of things.

**Comment by paulirish** [comment]
@adamraine i think next action is on you here

**Comment by brendankenny** [comment]
this should be good to go to fix the immediate bug and we can add more protections later on

**Review by adamraine — APPROVED** [review]

**Pull request merged**
