### PR TITLE
Fixes (or appears to) the occasional hang

### PR DESCRIPTION
**Pull request by paullewis**

### CODE REVIEW

**Comment by boopathi** [comment]
```
driver.gotoURL('about:blank', {waitForLoad: true});
```

isnt waitForLoad the required thing ?

**Comment by paullewis** [comment]
You'd think so, wouldn't you? The actual code is this:

```javascript
return driver.gotoURL('about:blank')
    // Wait one second for about:blank to "take hold" before switching back to the page.
    .then(_ => new Promise((resolve, reject) => setTimeout(resolve, 1000)))
    .then(_ => driver.gotoURL(options.url, {waitForLoad: true}));
```

If you call `Page.navigate` to the URL you're currently on, Chrome will hang. Instead you'd normally call `Page.reload`, but we can't do that because we need a navigation for the Service Worker to spin down and back up again. So we go into an `about:blank` -> `url.com` tennis match.

And it turns out that there's no point in waiting for a load event from `about:blank` because it doesn't fire one, and I think we switch so fast that Chrome gets into a hang.

**Comment by paulirish** [comment]
sg, but lets drop the timer down to 500ms?

**Comment by brendankenny** [comment]
+1 to @paulirish's suggestion, but LGTM otherwise

**Comment by paulirish** [comment]
merged and made the change.

**Pull request closed without merging**
