### PR TITLE
tests(smoke): remove html imports from dbw_tester

### PR DESCRIPTION
**Pull request by brendankenny**
unblocks CI along with #12353

html imports have been [deprecated for a loooong time](https://chromestatus.com/features/5144752345317376) (Chrome 70), but looks like they were only finally removed in Chrome 92.

dbw_tester has been holding on to them as render blocking resources, so it's time to remove since they no longer trigger a network request. Other render-blocking stuff is pretty well covered and I didn't see anything new to add in their place, so this is just a simple removal.

### CODE REVIEW

**Review by connorjclark — COMMENTED** [review]
lgtm

(unrelated page crash in CI, I restarted the tests).

**Review by adamraine — APPROVED** [review]
Still a couple references to these files in the devtools logs and traces of `lighthouse-core/test/results/artifacts` but I don't think it's worth messing with those files.

We also might be in a deadlock with https://github.com/GoogleChrome/lighthouse/pull/12353. @paulirish can we force merge?

**Comment by brendankenny** [comment]
> Still a couple references to `dbw_partial_*.html` in the devtools logs and traces of `lighthouse-core/test/results/artifacts` but I don't think it's worth messing with those files.

yeah, I didn't want to mess with those just because we'd have a lot more audit changes that weren't relevant for this change (just removing two network requests), but we will have to pull the trigger on those at some point, I suppose.

**Comment by brendankenny** [comment]
rebased on top of #12353

**Pull request merged**
