### PR TITLE
link to "offscreen images" reference

### PR DESCRIPTION
**Pull request by kaycebasques**

### CODE REVIEW

**Comment by patrickhulce** [comment]
nice! not sure what our policy is going forward on using "TTI" now though, I'm assuming publicly we're trying to say `TTI = time to consistently interactive`? We changed the language of `loadfast4pwa` to say "time to first interactive", but that's rather LH specific at the moment.

**Comment by kaycebasques** [comment]
How about I change it to `... improve page load speed and time to Consistently Interactive.`

**Comment by patrickhulce** [comment]
I was mostly just hoping to remove the use of "(TTI)" as an acronym in the short help text since AFAIK we still talk generally about "time to interactive" being important. I'll defer to others for specific language guidance. I'm fine with whatever.

cc: @paulirish

**Comment by kaycebasques** [comment]
Oh, OK. I'm fine with that.

**Comment by kaycebasques** [comment]
I removed the acronym and changed "time to interactive" to lowercase to indicate that we're talking about a general concept, not a specific metric

**Pull request merged**
