### PR TITLE
Travel destinations

### PR DESCRIPTION
**Pull request by lukecoupe**
We are going to travel the world together

**Summary**

**Related Issues/PRs**

### CODE REVIEW

**Comment by patrickhulce** [comment]
Please stop opening these PRs. Hundreds of people receive an email when you do this.

**Comment by lukecoupe** [comment]
sorry, thought it was a practice project.

________________________________

**Comment by exterkamp** [comment]
@lukecoupe I'm curious, how did you end up here? Were you following a tutorial or guide that told you this was a practice project?

**Comment by lukecoupe** [comment]
I followed a tutorial through Udacity, I must have made an error somewhere, my apologies.

Sent from my iPhone

On 12 Feb 2020, at 20:36, Shane Exterkamp <notifications@github.com> wrote:

﻿

@lukecoupe<https://github.com/lukecoupe> I'm curious, how did you end up here? Were you following a tutorial or guide that told you this was a practice project?

**Comment by connorjclark** [comment]
whats the url of the course?

**Comment by patrickhulce** [comment]
(we're not mad @lukecoupe if someone's instructing people to do this we'd love to get to the bottom of it, you're not the first to do this 😄)

**Comment by exterkamp** [comment]
> I followed a tutorial through Udacity

What tutorial? Like @patrickhulce said, we just want to fix the tutorial so that people know this isn't a test project :smile:

**Pull request closed without merging**
