### PR TITLE
feat: Page execution timings (don't merge)

### PR DESCRIPTION
**Pull request by addyosmani**
This initial PR adds support for page execution timings to the report. The ultimate goal of the feature is to inform developers where time is being spent during load and could be augmented to just show this before they are interactive.

Preview (extension):
screen shot 2017-02-10 at 7 12 42 pm

CLI:
screen shot 2017-02-10 at 6 56 34 pm

**A few directions we could take this:**

- Improve approach to grouping. @paulirish shared this [nice](https://docs.google.com/spreadsheets/d/1jqbSfdkB5RMtuifJwQsGb70WUUhWvzir7hq41wYHXsU/edit#gid=0) categorization doc for Timeline events that could be used.
- Add support for V8 Runtime Call Stats (to address #1158). This could come later. 
- Eventually, I'd like to introduce page execution 'budgets' (e.g your Parse and Compile times are wayyyy too long. Read this doc on how to trim em' down) 
- Eventually distinguish between lifetime of page load and work done between FMP and TTI

### CODE REVIEW

**Comment by tdresser** [comment]
We should probably be reusing code from: https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/chrome/chrome_user_friendly_category_driver.html to do the categorization.

I'm not sure that we should do this in lighthouse, but I'm hoping that long term we'll have some UI surface which lets us expose this information to developers, split by whether the work was pre-TTI or post-TTI, and maybe even more precisely than that. I can imagine someone asking the question "why is my FMP so far after FCP?", and then we could give them a CPU time breakdown between those two points.

Does this use wall time or cpu time?

**Comment by tdresser** [comment]
Ping re code sharing with https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/chrome/chrome_user_friendly_category_driver.html.

**Comment by addyosmani** [comment]
I was pretty sure I had commented on this a while back, but must have forgot to hit submit :)

I'm fully in support of reusing the code from https://github.com/catapult-project/catapult/blob/master/tracing/tracing/extras/chrome/chrome_user_friendly_category_driver.html. to do the categorization, @tdresser. I'll pick this work back up in the next week or two.

**Comment by wardpeet** [comment]
would it be beneficial to show compile & execution time per script or do we just want this to manually trigger the user to go in devtools

**Comment by benschwarz** [comment]
> would it be beneficial to show compile & execution time per script or do we just want this to manually trigger the user to go in devtools

It'd be great to have these stats on a per-script basis, as well as what @addyosmani has prepared so far. 

I'm going to push this around today and see where its at. IMO, we should get what we have shipped then start to look at enhancements thereafter.

**Comment by paulirish** [comment]
As requested, not merging this. ;)

Closing in favor of ward's new PR: #3520

**Pull request closed without merging**
