### PR TITLE
Add yarn.lock

### PR DESCRIPTION
**Pull request by samccone**
drops install time to 11.16s

### CODE REVIEW

**Comment by paulirish** [comment]
Was just about to do this, too. :)


image

**Comment by paulirish** [comment]
Wanna update travis to use yarn instead?

**Comment by samccone** [comment]
sure

**Comment by samccone** [comment]
actually might want to wait for https://github.com/yarnpkg/yarn/issues/692 before we migrate travis

**Comment by ebidel** [comment]
🔒

**Pull request merged**
