### PR TITLE
update yarn.lock

### PR DESCRIPTION
**Pull request by ebidel**
Updating from latest master.

### CODE REVIEW

**Comment by paulirish** [comment]
these appear to be dependencies of `codecov@2.2.0`
http://npm.anvaka.com/#/view/2d/codecov

**Comment by brendankenny** [comment]
> `+ Hits         4745     4837      +92`
> `- Misses        855      923      +68`
> `- Partials       14       20       +6`

that seems implausible, codecov

**Comment by ebidel** [comment]
So what's up? We don't want an updated yarn.lock?

**Comment by paulirish** [comment]
@ebidel im basically saying that i think this is incorrect.
your deletions are implicit dependencies of `codecov` which was recently added.

try updating to the latest version of yarn? 

is anyone else seeing this diff in their lock?

**Comment by paulirish** [comment]
eh. i applied it and everything seems to be fine. 
i have no idea why i wasn't seeing this diff.


sorry dude. let's do it.

**Pull request merged**
