### PR TITLE
deps: upgrade third-party-web to 0.20.2

### PR DESCRIPTION
**Pull request by alexnj**

### CODE REVIEW

**Comment by connorjclark** [comment]
Is the delta in sample json expected? May need to tweak the artifacts to restore some failing audit result there.

**Comment by alexnj** [comment]
No, the delta exists due to the entity not being recognized. It should be recognized, hence #14548.

**Comment by alexnj** [comment]
Alternatively, if we choose to not recognize the ~1040 entities that are missing due to not being present in HTTPArchive-data set, I'll go ahead update the sample json.

**Comment by connorjclark** [comment]
let's land #14548 first, and hopefully get the sample json to not lose data

**Review by connorjclark — APPROVED** [review]

**Pull request merged**
