### PR TITLE
Lighthouse treats "shrink-to-fit" property in meta-tag "viewport" as invalid

### PR DESCRIPTION
**Pull request by hmelenok**
Fix for #2474 

screen shot 2017-08-07 at 12 33 34

### CODE REVIEW

**Comment by hmelenok** [comment]
I signed it!

**Comment by paulirish** [comment]
The package.json change looks great, but the yarn.lock diff is much bigger than i'd expect.

want to try that part again?

**Comment by hmelenok** [comment]
Hey @paulirish, thanks  to check it out. It's fixed

**Comment by paulirish** [comment]
thanks very much for making this happen in both projects!

**Pull request merged**
