### PR TITLE
Wait for the insecure content page and show an error.

### PR DESCRIPTION
**Pull request by Janpot**
There was also a potential race condition with listening to the load event.
I fixed this by moving the call to `_waitForLoadEvent` before the call to
`Page.navigate`.

### CODE REVIEW

**Comment by Janpot** [comment]
Still work in progress but feedback welcome

**Comment by paulirish** [comment]
Nice. Do you want to add a smoketest for this that checks one of the badssl domains?

**Comment by brendankenny** [comment]
This currently halts the trace and moves on to the `afterPass` stage of the gatherers when an insecure state is found. Don't we want to stop the lighthouse run altogether because it's not actually measuring the target page, it's measuring the "Your connection is not private" page?

**Comment by Janpot** [comment]
@paulirish Will look into the smoketests, I guess I can use https://badssl.com/ ?

@brendankenny What do you suggest? I can reject when there is insecure state. I think that stops the whole process and shows a `Runtime error`. Also, keep in mind that some passes actually work when reviewing `https://www.cnn.com`.

**Comment by brendankenny** [comment]
> @brendankenny What do you suggest? 

I mean, it is a pretty big error, so I think it should probably reject altogether. The gatherer results will be at best inconsistent, with many of the results (e.g. performance metrics) actually for the "Your connection is not private" page and not the target page, with only a log entry to tell the difference.

Sort of related: are there other cases besides the "Your connection is not private" page interstitial page that are treated as `securityState` `insecure`? https://github.com/GoogleChrome/lighthouse/issues/1123#issuecomment-265916790 makes it sound like there's no explicit test, and we don't want to conflate different cases. OTOH, if Chrome always refuses to show a page when `insecure` the distinction might not matter.

**Comment by Janpot** [comment]
Another option would be to start Chrome with the `--ignore-certificate-errors`. In my project that makes sense as auditing security is part of our reports.

**Comment by paulirish** [comment]
> Another option would be to start Chrome with the --ignore-certificate-errors.  

heh. That was our resolution last time we discussed this: https://github.com/GoogleChrome/lighthouse/issues/559

**Comment by Janpot** [comment]
That wouldn't work at all together with this PR though, the navigation wouldn't wait for the load event anymore. Personally I think the `--ignore-certificate-errors` makes most sense if there's an audit for the security issue.

**Comment by brendankenny** [comment]
@Janpot so where you think this should go?

Direct users to `--ignore-certificate-errors` and add an audit for `insecure` security state? Looks like crbug.com/504499 will also (eventually) give us a debugger protocol method of detecting the SSL interstitials directly

**Comment by Janpot** [comment]
@brendankenny Maybe as `additionalFlags` [here](https://github.com/GoogleChrome/lighthouse/blob/83a5fdb94d2180adb2814dc0e9b916d08aa63c38/lighthouse-cli/bin.ts#L204)?

**Comment by Janpot** [comment]
@paulirish @brendankenny Ok, gave it a bit more thought. I think the right way to go for now would be to direct users to `--ignore-certificate-errors`. Closing this PR since it would break that workflow. As far as I can see there is no way to properly detect this failure. 
It seems like a `Network.loadingFailed` event is not coming through when chrome blocks on insecure state.

**Pull request closed without merging**
