### PR TITLE
deps(chrome-launcher): Upgrade chrome-launcher

### PR DESCRIPTION
**Pull request by wardpeet**
Upgrade chrome-launcher to 0.10.1.

I wasn't sure why chrome-launcher does not have a `^` in package.json so feel free to decline this PR.

### CODE REVIEW

**Comment by patrickhulce** [comment]
uh-oh looks like we broke chrome-launcher typings :(

image

**Comment by paulirish** [comment]
ruh roh. looks like i did indeed break the TS typings with the folder move: https://github.com/GoogleChrome/chrome-launcher/pull/69#issuecomment-350393653

**Comment by paulirish** [comment]
just rebased to get the #4209 fix that was breaking this PR.

why was it breaking this PR out of the blue?  that, we'll never know.  🐩

**Comment by samccone** [comment]
Is there a test we could add to chrome-launcher to prevent this?

**Comment by paulirish** [comment]
> Is there a test we could add to chrome-launcher to prevent this?

yes i would love that. not how to write it, personally. you might know better than most of us. :)

**Comment by wardpeet** [comment]
Not 100% sure but we can write a test like this:
```
npm pack
Unpack zip 
Parse package.json
See if typing field exists
```
By default it checks in the root directory

**Comment by paulirish** [comment]
i was thinking a more functional test. e.g. some module that require()s chrome-launcher successfully typechecks with TS.

**Comment by paulirish** [comment]
even though travis is busted, appveyor is happy. shipping.

**Pull request merged**
