### PR TITLE
Update deps to be major version dependent

### PR DESCRIPTION
**Pull request by rviscomi**
Prefixing versions with ^ will relax the dependency requirement to match only the major version number. For example, ^1.0.0 is compatible with all 1.x versions.
Similarly, prefixing with ~ will match major and minor version numbers. So ~1.0.0 will be compatible with only the 1.0.x versions.
Updated all prod dependencies to major version requirements.

### CODE REVIEW

**Comment by rviscomi** [comment]
Signed the CLA

**Comment by samccone** [comment]
Hi thanks for the PR.

I am actually -1 to this. We have a yarn.lock file now and locking our dependencies down as tight as they can be is actually a good thing imho. 

chrome-devtools-frontend for example does not follow semver and updating it requires changing things, so this would break for consumers pretty quick.

The goal here is that by shipping a fairly locked down tool users that install it at any time in the future will have a working version and not one that is broken due to an upstream semver breaking change (since enough transient and direct deps do not exactly follow semver)

**Comment by brendankenny** [comment]
@rviscomi after outside discussion, are we going to close this? Or is there some subset of this PR that you do want to merge?

**Comment by brendankenny** [comment]
closing, though we can of course continue this conversation

**Pull request closed without merging**
