### PR TITLE
core(csp-xss): hidden severity

### PR DESCRIPTION
**Pull request by adamraine**
Can land after https://github.com/GoogleChrome/lighthouse/pull/12221

Screen Shot 2021-03-12 at 6 48 25 PM

When there is no CSP, we now use a table item with severity icon instead of the audit display value. If we just use the display value, the audit state for "no csp" will look very similar to the audit state for "csp is all good".

Before:
Screen Shot 2021-03-16 at 12 44 43 PM

After:
Screen Shot 2021-03-16 at 12 43 41 PM

### CODE REVIEW

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/pull/12221#discussion_r594656594 Proposal to move directive column to the left.

**Comment by adamraine** [comment]
Looks pretty weird for findings with no directive.
Screen Shot 2021-03-15 at 6 04 11 PM

**Review by paulirish — COMMENTED** [review]
as discussed,  we'll drop the icons. and yeah lets keep directive as the last column.

you said you wanted to keep some other changes in here, so i'll let you take that.

**Comment by connorjclark** [comment]
reminder to change the PR title

**Comment by brendankenny** [comment]
> Having the icons available in the LHR might still be useful for testing.

Since they'll be hidden, can the new icon audit-details type be dropped until we need it?

**Comment by adamraine** [comment]
> Since they'll be hidden, can the new icon audit-details type be dropped until we need it?

I removed the icon code from the report renderer, but I don't think I can remove the type entirely.

**Comment by brendankenny** [comment]
couldn't they just be text (e.g. just the current `tooltip` value) in a "severity" column? e.g. `iconName` isn't important if it's just for testing for now.

**Comment by adamraine** [comment]
Could we land this? At this point, it's just a few minor tweaks.

**Review by connorjclark — APPROVED** [review]

**Pull request merged**
