### PR TITLE
Fixes .find on undefined violations object #920

### LINKED ISSUE #920: Cannot read property 'find' of undefined
image

Reported over email.

I was able to repro locally (ping me if you want the URL) and it's in one of the accessibility audits:

image

image

A few ways to fix this; anybody want to take it?

### PR DESCRIPTION
**Pull request by jillesme**
fixes #920 

This PR adds a guard around the violations property on the Accessibility object. 

EDIT: tests failed because I didn't build the lighthouse-cli, all tests pass now 👍

### CODE REVIEW

**Comment by paulirish** [comment]
btw `cd lighthouse-cli && npm run build` to fix those tests.

**Comment by paulirish** [comment]
Hmmm. This adds a violation specific method to our general Audit class. Not sure about that.

I think a tad easier would be something like `const violations = artifacts.Accessibility.violations || [];` at the top of each of these. wdyt?

**Comment by jillesme** [comment]
@paulirish that's actually what I did first! Then I saw it on 6 different places and thought that solution was more robust. Then again, that method doesn't really "fit in" the Audit class so the initial solution will work too. I'll update the PR! 👍

**Comment by paulirish** [comment]
cool!

#941 will fix the "6 different places part". :)

**Comment by paulirish** [comment]
this works for me, but I know @brendankenny wanted another look (and he's in the air right now).

@jillesme can you add a test? Just put it in one of these audit's test file, passing `{violations: undefined}` as the accessibility artifact.

**Comment by jillesme** [comment]
Definitely, done. I didn't at first when the method was in the `audit.js` file because the method abobe it (`generateAuditResult`) wasn't tested as well. Was this for a specific reason or have I just found another PR reason 😄 ?

**Pull request merged**
