### PR TITLE
report: update keyframes for confetti animation

### LINKED ISSUE #12563: Perfect score animation acting buggy
Being a longtime Lighthouse user, I have come to really enjoy the perfect score animation. The confetti animation that follows and shoots confetti off in realistic *poof* is great. I've done this sort of "blast something into the air" animation with GSAP and Physics2D before, not sure how the animation is being implemented here (Pure CSS, some JS, idk) in Lighthouse without having a deeper look at the source.

That all being said, the animation looks great (as expected). But, I've noticed some unexpected behavior for the confetti animation. When you scroll the page down inside the Lighthouse audit (after results are shown) assuming a perfect score was received, the confetti animation starts acting a bit odd and the animation becomes a bit more choppy with the confetti becoming slightly visible as its blurs across the screen to new positions before "firing" more confetti. 

When does this happen:

1. Intermittently when the Lighthouse audit results page isn't scrolled and a perfect score is received.
2. When a lighthouse audit completes and you receive a perfect score, then scroll down inside the audit window and back up to the animation.

Note: In chrome Version 90.0.4430.212 (Official Build) (x86_64) on Mac OS High Sierra

I'm sure most people won't notice this slight sporadic behavior, but maybe some will. Below is a short video highlighting how the confetti begin to become visible as they whizz across the screen and move to different positions before firing off confetti. 

https://user-images.githubusercontent.com/48612525/119689717-efa6e580-bdfd-11eb-9c5f-e84b814bef07.mov

I'm going to have a look in the repo and see if I can `git grep -n ""` anything to see where the animation is being implemented. 

My gut thought for a quick fix is to ensure that the opacity or 'transparency' is 0 when the "confetti launcher" is moving to a new position on the screen and launching confetti. It seems that there is a 1-2ms gap (probably less) where the opacity of the confetti is 1 and they are completely visible as we watch them zip across the screen in a sort of abrupt manner.

### PR DESCRIPTION
**Pull request by tannerdolby**
**Summary**

Fixes #12563 

Updates the `bang` and `gravity` keyframes that are used for the perfect score confetti animation.

When the `lh-pyro-before` and `lh-pyro-after` elements (the confetti) move from one position to the next, we can still see the box-shadow's which makes up the confetti spread sort of abruptly move/flicker to a new position. This is due to the elements still having a visible opacity when moving from point1 (spot near where last confetti went off) -> point2 (new confetti position).

### Current Confetti Behavior
abrupt/buggy at some points where we can see the confetti spread flicker from one spot to its destination due to opacity/visibility when moving to a new position, it doesn't happen always but is noticeable over time.

https://github.com/GoogleChrome/lighthouse/assets/48612525/2f03aa6d-d705-497d-9bf8-406dd78f121e

### Confetti After Change

https://github.com/GoogleChrome/lighthouse/assets/48612525/20ef85b8-2665-40d0-aaea-edef76976c94

**Related Issues/PRs**

https://github.com/GoogleChrome/lighthouse/pull/13635

### CODE REVIEW

**Comment by LGNDDOLLABOUTIQUE** [comment]
I'll get back to you tomorrow after get a connections to login.

**Comment by connorjclark** [comment]
Oh this is great, thanks for working on this!

Can you make the changes to `report/assets/styles.css` instead? If you then run `yarn build-report`, it will update the `component.js` file (which is a hacky generated file not meant to be edited directly).

**Comment by tannerdolby** [comment]
Glad to hear that, you're welcome!

Sure thing, I made the changes in `report/assets/templates.html` as that's where the confetti animation styling lived and used `yarn build-report` command to generate the output file. When editing the `report/renderer/components.js` file directly, it felt like I might have been missing something. Thanks for the heads up.

**Comment by paulirish** [comment]
omg. thank you for figuring this out!   it's been bugging all of us for a long time. 

this is huge. :)

also lol @ `patch-12563`.   that's a branch with style. 💅   cheers.

**Comment by tannerdolby** [comment]
@paulirish you're welcome! it was bugging me for awhile too, i'm really happy that we were able to find a fix :)

thanks lol 💅  I think that branch naming is habit from my current role. cheers!

**Review by adamraine — APPROVED** [review]

**Comment by LGNDDOLLABOUTIQUE** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by LGNDDOLLABOUTIQUE** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by LGNDDOLLABOUTIQUE** [comment]
https://wmtpix.com/qr/e1de21f0-53b1-458e-b320-28b7338db373?utm_source=tsx-01565&utm_medium=qr-code&utm_campaign=kiosk-media-transfer-pair-first

Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by LGNDDOLLABOUTIQUE** [comment]
Dear Lgnd Dolla Boutique,

Thank you so much for contacting us.
To better assist you with your inquiry, please use the email associated to your Xoom account.
If you have any questions, you can contact us. Thank you,    Xoom Customer Verification
Security | Legal | Privacy | Privacy (USA) | About Us | Locations | Help Center

This email has been sent by Xoom, a PayPal service. PayPal is committed to preventing fraudulent emails.

Learn to identify phishing
ref:_00DC0QPVP._5003b1lj36H:ref

**Comment by LGNDDOLLABOUTIQUE** [comment]
https://extension.harvard.edu/?gad=1&gclid=CjwKCAjw1YCkBhAOEiwA5aN4AZqvv0I8wYWNjw37J8bdashB6GncvSeDPMxHNZwfu_1JvV36fWsmkRoCRrgQAvD_BwE

Get Outlook for Android<https://aka.ms/AAb9ysg>

**Pull request merged**
