### PR TITLE
docs(readme): update Foo integration

### PR DESCRIPTION
**Pull request by adamhenson**
**Summary**

automated-lighthouse-check.com has moved to [foo.software](https://www.foo.software). Updated the integration here accordingly.

### CODE REVIEW

**Comment by adamhenson** [comment]
@connorjclark - are these smoke tests just flakey? This is just a documentation change.

**Comment by patrickhulce** [comment]
@adamhenson yes one of the test sites in the smoke tests is currently down (https://shop.polymer-project.org/)

**Comment by patrickhulce** [comment]
@adamhenson you don't need to keep retrying it. The site itself is has an expired SSL cert, so it will continue failing. We'll just need to hold off for awhile until we either remove the test or the site comes back up.

**Comment by adamhenson** [comment]
Sounds good, thanks @patrickhulce.

**Pull request merged**
