### PR TITLE
misc: tweak folder used for vercel deployment

### PR DESCRIPTION
**Pull request by connorjclark**
Noticed a minor extra complexity with how the vercel deployment works. instead of uploading `dist/now` and moving all the `gh-pages` into that folder, I suggest we just upload `dist`.

image

->

image

it's still just a subset of our dist folder (although now it added `report/`) because vercel only runs `yarn now-build`

### CODE REVIEW

**Comment by paulirish** [comment]
> Noticed a minor extra complexity with how the vercel deployment works. instead of uploading `dist/now` and moving all the `gh-pages` into that folder, I suggest we just upload `dist`.

that sounds good to me.  this PR basically removes the "now" term from our file structure, which is a great addition to #12901.  (i was thinking we do s/now/vercel/ but i like this proposal even more)


-----

can you adjust the two lines in dogfood-lhci.sh that also work with /now/ ?

**Review by paulirish — APPROVED** [review]
lgtm % dogfood-lhci thing.

this'll conflict with #12901 too. :/

**Comment by brendankenny** [comment]
> > Noticed a minor extra complexity with how the vercel deployment works. instead of uploading `dist/now` and moving all the `gh-pages` into that folder, I suggest we just upload `dist`.
> 
> that sounds good to me. this PR basically removes the "now" term from our file structure, which is a great addition to #12901. (i was thinking we do s/now/vercel/ but i like this proposal even more)

FWIW https://vercel.com/guides/upgrade-to-zero-configuration#frameworks-with-zero-configuration makes it seem like we could drop the `now.json` too if we're willing to `&& mv dist public`.

It does seem like a `yarn build-all` could sneak into this npm script chain at some point and we'll be uploading MBs of javascript from `dist/` with no one noticing, but presumably that would still be well within any deployment limits? :)

**Comment by brendankenny** [comment]
> can you adjust the two lines in dogfood-lhci.sh that also work with /now/ ?

should something have failed here since `./dist/now/english/` didn't exist?

**Review by paulirish — APPROVED** [review]

**Comment by paulirish** [comment]
> > can you adjust the two lines in dogfood-lhci.sh that also work with /now/ ?
> 
> should something have failed here since `./dist/now/english/` didn't exist?

heh probably but this happened:
 
image

(and probably happens on all runs all the time. ruh roh)



> FWIW [vercel.com/guides/upgrade-to-zero-configuration#frameworks-with-zero-configuration](https://vercel.com/guides/upgrade-to-zero-configuration#frameworks-with-zero-configuration) makes it seem like we could drop the `now.json` too if we're willing to `&& mv dist public` (edit: in `yarn vercel-build`, I mean, not everywhere :)

i tried this on another project recently.. unfortch the config file is still necessary if you don't want vercel to comment after every deployment.   (the   `"github": {"silent": true},` bit)

**Review by adamraine — APPROVED** [review]

**Pull request merged**
