### PR TITLE
Root package

### PR DESCRIPTION
**Pull request by paullewis**

### CODE REVIEW

**Comment by boopathi** [comment]
It's better to 

+ move all devDependencies to root instead of individual directories - i.e. not have any devDeps on individual directories.
+ move all dev tasks (build-ext, watch-ext, tests) to root
+ npm install on root to call npm install on all packages - maybe?

What do you think?

**Comment by paullewis** [comment]
Paging @paulirish, as this was his preferred route.

**Comment by boopathi** [comment]
Just a few more concerns -

+ `npm install lighthouse` would install everything where extension deps are not needed
+ `npm install lighthouse-cli` wouldn't work - as `lighthouse-core` dependency will not be found.
+ `lighthouse` and `lighthouse-cli` are essentially the same - right?
+ `npm install lighthouse-extension` - why would this be useful?

**Comment by paullewis** [comment]
> npm install lighthouse-cli wouldn't work - as lighthouse-core dependency will not be found.

It doesn't need it, it loads in lighthouse-core via relative paths.

> lighthouse and lighthouse-cli are essentially the same - right?

No, lighthouse as a package is the container for lighthouse-cli, lighthouse-core and lighthouse-extension. If you require it, though, we route that to lighthouse-core.

> npm install lighthouse would install everything where extension deps are not needed
> npm install lighthouse-extension - why would this be useful?

For anyone who wants to built a Tip of Tree version of the extension rather than using the current published version.

**Comment by boopathi** [comment]
Ah. Okay.

> It doesn't need it, it loads in lighthouse-core via relative paths.

Relative paths won't work. If I do `npm install lighthouse-cli` (say `-g`), only that package is installed. `lighthouse-core` is outside this bundle/package. It won't be installed.

**Comment by paullewis** [comment]
> Relative paths won't work. If I do npm install lighthouse-cli (say -g), only that package is installed. lighthouse-core is outside this bundle/package. It won't be installed.

That's true _if_ we publish the CLI to npm. As it stands we're not doing that, which begs the question as to why we have multiple package.json files. I guess we're waiting and seeing a little bit here.

**Comment by paulirish** [comment]
I think I'm convinced that we move lighthouse-cli's manifest to merge with this root one. I think that clarifies a lot of the intent here.

Thanks for raising these questions, @boopathi. super helpful. :D

**Comment by paulirish** [comment]
Almost done. Looks like i need to fix smoke tests next.

**Comment by paulirish** [comment]
Lgtm

**Comment by paullewis** [comment]
Removed core/package.json, but offline Irish said he'd like to keep it "for sentimental reasons". Who am I to get in his way? Reverted.

**Pull request merged**
