### PR TITLE
tests: migrate travis to xenial for modern Chrome support

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
traced the master failures of installing latest chrome stable to this bug https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

just need to update dpkg before install chrome

### CODE REVIEW

**Comment by patrickhulce** [comment]
*hopefully* this is temporary until latest dpkg is on travis builds by default?

`sudo apt-get update` ain't cheap :(

**Comment by patrickhulce** [comment]
update: according to the [travis forums](https://travis-ci.community/t/travis-is-downloading-older-chrome-versions-in-place-of-chrome-stable/5040/4) it actually looks like chrome dropped official support for `trusty` and we need to migrate to `xenial`. old  fix I had should work in the short-term but might as well try out xenial instead.

**Comment by paulirish** [comment]
wow nice job tracking this down.

**Comment by brendankenny** [comment]
> update: according to the travis forums it actually looks like chrome dropped official support for trusty and we need to migrate to xenial. old fix I had should work in the short-term but might as well try out xenial instead.

I wish they'd better notify us about [these things](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment). Looks like we can just drop `dist: trusty`?

**Comment by brendankenny** [comment]
```
services:
  - xvfb
```

coooool

**Pull request merged**
