### PR TITLE
report(build): don't build flow if only --standalone is requested

### PR DESCRIPTION
**Pull request by paulirish**
When I'm working on the standalone report, I don't want to incur whatever wildness is going on with the tsc plugin for the flow report build.

That work for you @adamraine ?

### CODE REVIEW

**Review by patrickhulce — APPROVED** [review]

**Review by adamraine — APPROVED** [review]

**Comment by brendankenny** [comment]
> incur whatever wildness is going on with the tsc plugin

this is what @connorjclark and I were talking about wrt logging. The plugin uses a file watcher to do even one-off builds and we can't find an option to silence it :(

**Comment by connorjclark** [comment]
last resort would be to filter it out with grep/redirect stderr to /dev/null. or maybe running in a child process in Node would allow us to filter it too.

this PR is problematic for using the "yarn start" workflow when working on the flow report (the reason it rebuild the standalone report...), but given Adam/patrick are the only ones working on that right now and they've approved I suppose it's not too problematic.

**Comment by adamraine** [comment]
Ope one thing to change:
https://github.com/GoogleChrome/lighthouse/blob/4010f8c41c311c93afd9203ec71e37e058fe91fc/lighthouse-core/scripts/build-test-flow-report.js#L12

`--standalone` --> `--flow`

**Comment by paulirish** [comment]
> Ope one thing to change:
> https://github.com/GoogleChrome/lighthouse/blob/4010f8c41c311c93afd9203ec71e37e058fe91fc/lighthouse-core/scripts/build-test-flow-report.js#L12
> 
> `--standalone` --> `--flow`

good catch. done.

**Pull request merged**
