### PR TITLE
misc: rename lantern master values to baseline values

### PR DESCRIPTION
**Pull request by connorjclark**

### CODE REVIEW

**Comment by brendankenny** [comment]
> I'd have a strong preference for renaming these `lantern-trunk-*` and renaming our master branch to `trunk` instead. Do we think that's feasible to do quickly? (If not I'm fine with `baseline` in the meantime)

you've convinced me on `trunk` over `main`. I'm also fine to call these `lantern-trunk-*` even while we figure out the logistics of using `trunk` for the default branch.

It would be nice if we all agreed on definitive meanings for `trunk`/`baseline`/`golden`(/others?), though :) It sounds like you might already have a classification you're working off of @patrickhulce?

They all _could_ mean slightly different things, but I think in practice we use them in overlapping ways.

**Comment by patrickhulce** [comment]
> It would be nice if we all agreed on definitive meanings for trunk/baseline/golden(/others?), though :) It sounds like you might already have a classification you're working off of @patrickhulce?

I'm defensive of losing the signal in these names because this was the result of me and Paul (I thought it was you too but if you're asking then I guess not?) sitting in a room for like an hour trying to work out the clearest way to communicate what these are after my attempt didn't cut it 😆 

Preemptively renaming to `trunk` ahead of branch rename WFM 👍

**Comment by connorjclark** [comment]
I was going to recommend "main" for the branch rename, primarily because: that's what Chromium is leaning towards (at this early stage); and "maTAB" would be maintained for muscle memory, meaning that if everyone did "main" you'd never have to recall whatever name the project you're working on chose.

**Comment by brendankenny** [comment]
> I'm defensive of losing the signal in these names because this was the result of me and Paul sitting in a room for like an hour trying to work out the clearest way to communicate what these are after my attempt didn't cut it 😆

I'm good with it (and whatever, really), I just want it written down in an issue or a comment or somewhere so the next time I'm naming something and I'm like "wait, should this be a golden-lhr or a trunk-lhr?" I can just look at that and not have to think any more than that about it :D

> (I thought it was you too but if you're asking then I guess not?)

ha, well that's very possible

**Comment by patrickhulce** [comment]
@connorjclark I believe our discussed settled on we will hold off renaming master until full consensus has been reached in other places for the name we're going to match. Are you OK with tabling this for now to avoid a temporary inconsistent name?

AFAIK, no one other than you and me has had to even notice these files exist in the course of their Lighthouse work, so I'm less concerned about the impact here compared to the branch itself (which we're already OK temporarily postpoing).

**Comment by patrickhulce** [comment]
Given that [the community has settled on main](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) and `lantern-main` would be even more ambiguous (unfortunately confirming my issues with `main` as opposed to something like `trunk` 😢 ), I'm fine moving forward with `baseline` here if everyone still thinks it's clear what it's referring to.

**Review by patrickhulce — CHANGES_REQUESTED** [review]
looks like there's more to update, but ya I'm fine with the master -> baseline rename :)

**Review by patrickhulce — APPROVED** [review]

**Pull request merged**
