### PR TITLE
cli: print ansii lighthouse on --version

### PR DESCRIPTION
**Pull request by Hoten**
:)

image

I made the ansii with [img2txt.py](https://github.com/hit9/img2txt):
```
img2txt.py ~/Desktop/lighthouse-logo.png --ansi --maxLen=40 --targetAspect=.5
```

### CODE REVIEW

**Comment by Hoten** [comment]
or...

dithered
image

a different img:

image

**Comment by brendankenny** [comment]
my vote is no, FWIW :P

I'd find it really annoying if just trying to get the version :)

**Comment by brendankenny** [comment]
(if people realllllllly want it, maybe we could do it with a secret `--i-can-be-your-lighthouse` or whatever flag :)

**Comment by Hoten** [comment]
fair enough :)

I put it in the --version because it's one of the few (maybe the only, i dont recall) fields in `yargs` that does not preprocess the text.

**Pull request closed without merging**
