### PR TITLE
clients(extension): update to manifest v3

### PR DESCRIPTION
**Pull request by patrickkettner**
**Summary**
:wave: - patrickkettner@ from extensions devrel here! As a part of our [MV2 sunsetting](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/), I am reaching out to popular extensions to see how migrations are going. Even though y'all have shipped in devtools for such a long time, there is still a _lot_ of folks using the extension. I took a quick look, and this was all that is needed to get yall moved over.

### CODE REVIEW

**Comment by paulirish** [comment]
Thanks for the personal touch. :)  
Tested this out and it's all aces.

Thanks

**Comment by paulirish** [comment]
image

@adamraine afaict this isn't breaking. tbh i think we're fine to deploy this to CWS as soon as its merged. the ext is so small... just a shortcut to opening the viewer.

**Review by paulirish — APPROVED** [review]

**Comment by patrickkettner** [comment]
ayy :D
I

**Comment by patrickkettner** [comment]
@paulirish shouldnt be breaking, though if someone is running super old chrome (<88ish) then it _would_ break there, as MV3 wasn't around then. we can update the minimum chrome version accordingly, if that is a concern

**Pull request merged**
