### PR TITLE
misc: fix unit-viewer command for windows

### PR DESCRIPTION
**Pull request by patrickhulce**
I don't tend to look at the appveyor tests too closely now that they are so flakey, but apparently our viewer filter has been ignored and so it defaults to re-running *all* our tests. As if it weren't slow enough already! 😭 

Turns out it wasn't quoted like the others, so this *should* fix it.

image

### CODE REVIEW

**Comment by brendankenny** [comment]
I had removed the quotes because I get `Invalid testPattern lighthouse-viewer/**/*-test.js supplied. Running all tests instead.`

**Comment by brendankenny** [comment]
oh, I think if it's in quotes it has to be a regex (that jest uses to filter all inputs) vs just globbing a list of input files (like this is doing, that would be broken if the shell doesn't support that)

**Comment by patrickhulce** [comment]
> oh, I think if it's in quotes it has to be a regex (that jest uses to filter all inputs) vs just globbing a list of input files (like this is doing, that would be broken if the shell doesn't support that)

Ha I just found this too, great minds :)

**Comment by patrickhulce** [comment]
I also disabled the one assertion that's particularly flaky on appveyor for now

**Pull request merged**
