### PR TITLE
Fixes #1040 - makes "manifest found icons..." message displayValues. Happy 🦃 📅 !!!

### LINKED ISSUE #1040: Manifest: "found icons sizes" debugString should be displayValue
How come the `--poor-color` is so bright and highlighted in our reports?
It is used for `Found icons of sizes: 152x152,144x144,192x192,256x256,512x512"

Can we use a more subtle color there?

screenshot 2016-11-24 at 9 45 14 am

### PR DESCRIPTION
**Pull request by ebidel**
R: all

Fixes #1040

### CODE REVIEW

**Comment by brendankenny** [comment]
also should we add a `debugString` for the case when no icons of that size or greater were found?

**Comment by ebidel** [comment]
The precedence is that `displayValue` is for the actual values used.

**Comment by brendankenny** [comment]
> The precedence is that displayValue is for the actual values used.

good point, but it ends up a little visually noisy:

screen shot 2016-11-24 at 11 15 57

`extendedInfo` would be formatted a bit better, plus usually you don't care about what actual sizes pass after you first move from not passing to passing, so having them nested below makes some sense

**Comment by ebidel** [comment]
It's a big noisy, but `displayValue` is for this purpose. We use it elsewhere:

screen shot 2016-11-24 at 1 20 23 pm

and it has the correct styling.

**Comment by ebidel** [comment]
With additional "not greater than x size warning":

screen shot 2016-11-24 at 1 28 27 pm

**Comment by brendankenny** [comment]
> Something we should consider is redesigning how displayValue surfaces in the report.

report redesign 5.0 :)

**Pull request merged**
