### PR TITLE
Losslessly optimize all images in this repo

### PR DESCRIPTION
**Pull request by coliff**
This saves 25%. Images optimised with https://imgbot.net/
```
*Total -- 899.26kb -> 678.74kb (24.52%)

/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-1.jpg -- 1.29kb -> 0.57kb (55.53%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-2.jpg -- 1.29kb -> 0.57kb (55.53%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-3.jpg -- 1.29kb -> 0.57kb (55.53%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-4.jpg -- 1.29kb -> 0.57kb (55.53%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-5.jpg -- 1.29kb -> 0.57kb (55.53%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-0.jpg -- 1.29kb -> 0.57kb (55.53%)
/assets/example_audit.png -- 353.17kb -> 195.70kb (44.59%)
/assets/example_dev_tools.png -- 56.77kb -> 44.01kb (22.47%)
/clients/extension/images/lh_logo_canary_bg.png -- 56.81kb -> 44.38kb (21.88%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-6.jpg -- 4.96kb -> 3.93kb (20.67%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-7.jpg -- 4.69kb -> 3.82kb (18.48%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-8.jpg -- 4.69kb -> 3.82kb (18.48%)
/clients/extension/images/lh_logo_canary_icon.png -- 43.46kb -> 36.46kb (16.12%)
/assets/lighthouse-logo.png -- 65.55kb -> 57.09kb (12.92%)
/assets/architecture.jpg -- 76.41kb -> 67.86kb (11.19%)
/lighthouse-core/test/fixtures/traces/screenshots/progressive-app-frame-9.jpg -- 10.18kb -> 9.14kb (10.29%)
/lighthouse-cli/test/fixtures/byte-efficiency/lighthouse-320x212-poor.jpg -- 5.95kb -> 5.60kb (5.87%)
/lighthouse-cli/test/fixtures/byte-efficiency/lighthouse-unoptimized.jpg -- 50.72kb -> 48.14kb (5.09%)
/lighthouse-cli/test/fixtures/byte-efficiency/lighthouse-1024x680.jpg -- 110.07kb -> 107.76kb (2.1%)
/lighthouse-cli/test/fixtures/byte-efficiency/lighthouse-480x320.jpg -- 24.04kb -> 23.79kb (1.05%)
/lighthouse-cli/test/fixtures/dobetterweb/lighthouse-480x318.jpg -- 24.04kb -> 23.79kb (1.05%)
```

### CODE REVIEW

**Comment by patrickhulce** [comment]
Thanks @coliff! A lot of those images though are fixtures which are programmatically generated or designed to be a particular (potentially inefficient) file size for testing.

I think the ones in `/assets` are reasonable to shrink though :)

**Comment by Hoten** [comment]
Can keep the ones in `/clients` too.

**Comment by paulirish** [comment]
> Ah good to know. Can you edit this PR to just keep the /assets and /clients images then?

probably not. we got some other things on our plate right now, but we can be a little patient for you to fix it up.

**Comment by paulirish** [comment]
@coliff ping

**Comment by coliff** [comment]
ok, sorry for the hassle but I had deleted my fork of this after making the PR so I'm unable to make changes to this PR. I think this leaves us with a few options:

1) Add ImgBot to this repo to automatically optimise images now and in the future. Add a imgbot config to ignore certain paths as @dabutvin suggested

2) Someone from the core team could edit this PR to remove the images which shouldn't be optimised and then merge it.

3) Close this PR and I or someone else make a new PR of just the required images which should be optimised.

**Comment by Hoten** [comment]
You should be able to remove files from the PR by clicking on the trash can in the "File changed" tab.

**Comment by patrickhulce** [comment]
@Hoten I think he deleted his fork, which makes this PR uneditable.

**Pull request closed without merging**
