### PR TITLE
Use default args now that node 6 is required.

### PR DESCRIPTION
**Pull request by XhmikosR**
There's also `polyfillNode4Support` which I can't quite look into now. If the name is wrong, the function should be renamed otherwise cleaned up.

### CODE REVIEW

**Comment by brendankenny** [comment]
maybe we should do one big pass for places where we can drop the || dance and use default parameters? A quick search didn't turn up that many, but enough that a PR for each is going to get pretty noisy :)

**Comment by XhmikosR** [comment]
Agreed, but I just looked for node comments and saw this one and the `polyfillNode4Support` function.

**Comment by XhmikosR** [comment]
@brendankenny: please check now. I enabled ESLint's `no-param-reassign` rule locally to quickly see the errors.

**Comment by brendankenny** [comment]
@XhmikosR I fixed the merge conflict in the github UI and immediately regretted it :) Do you want to back that out, fix the merge conflict and I can land?

**Comment by XhmikosR** [comment]
@brendankenny: rebased, check now.

**Comment by brendankenny** [comment]
thanks again!

**Pull request merged**
