### PR TITLE
Travis: assert renderer can compile against devtools

### PR DESCRIPTION
**Pull request by paulirish**
Output:

* https://travis-ci.org/GoogleChrome/lighthouse/jobs/227773873#L606
* https://travis-ci.org/GoogleChrome/lighthouse/jobs/227773872#L607

### CODE REVIEW

**Comment by brendankenny** [comment]
Nice!

I'm curious if it would have caught https://github.com/GoogleChrome/lighthouse/pull/2118/commits/0d6991707691072cabcdad8516c79103c02f0fd1 (I'm disappointed that our current closure check didn't alert that it wasn't on the type and I'm not sure why it didn't)

**Comment by paulirish** [comment]
@brendankenny ill try real quick

**Comment by brendankenny** [comment]
I guess the frontend stuff can't be cached on travis by design? Our travis run times have been edging upwards recently

**Comment by paulirish** [comment]
> I guess the frontend stuff can't be cached on travis by design? 

well a git fetch of latest from those repos would take less time than a brand new clone.
so actually a cache would work out pretty okay for those two folders

**Comment by paulirish** [comment]
@brendankenny i checked out f8a45f97b268b49dfec862d7ec2826721738732f which was the commit right before the closure fix

the task **didn't** catch it:
image

**Comment by brendankenny** [comment]
> the task didn't catch it

weird. I'll investigate (though prob post launch)

**Pull request merged**
