### PR TITLE
Update package.json homepage & issue URLs from Big Rig

### PR DESCRIPTION
**Pull request by ZackBoe**
Was poking about on [npm](https://www.npmjs.com/package/lighthouse) and noticed these references hadn't been changed  :wave:

### CODE REVIEW

**Comment by brendankenny** [comment]
whoops! nice catch

**Comment by samccone** [comment]
aww snap good catch

**Comment by ZackBoe** [comment]
:wink:

**Comment by paulirish** [comment]
thx zack!

**Pull request merged**
