### PR TITLE
core(font-size): fix CSS selector regex

### PR DESCRIPTION
**Pull request by adamraine**
Resolves most of https://github.com/GoogleChrome/lighthouse/issues/12001.

### CODE REVIEW

**Comment by connorjclark** [comment]
Is 8KB too much to pay to solve this + support paul's test cases? https://www.npmjs.com/package/css-selector-parserhttps://www.npmjs.com/package/css-selector-parser

**Comment by adamraine** [comment]
> Is 8KB too much to pay to solve this + support paul's test cases? npmjs.com/package/css-selector-parser

I played around with it real quick. You have to provide things like nesting operators yourself, and if we missed one it will throw on that operator. Also hasn't been updated in a while.

Might still be better then our regex system, but doesn't seem worth it to me. From the other PR:

> that said, there are plenty of these test cases we still don't handle. I don't care a lot, but someone could have fun if they wanted. there's probably some stuff to pull from in this npm module keeganstreet/specificity, but it needs to be updated to include todays' :is() and :where() etc etc. but IMO it's pretty small ROI

**Comment by paulirish** [comment]
I also wonder.... The devtools source doesnt determine specificity.. so i think they may rely on the order coming back from CDP to inform what rule applied?  that would be an alternate approach.

**Review by connorjclark — APPROVED** [review]

**Comment by connorjclark** [comment]
> I also wonder.... The devtools source doesnt determine specificity.. so i think they may rely on the order coming back from CDP to inform what rule applied? that would be an alternate approach.

great catch. I confirmed this experimentally. pr incoming

**Pull request merged**
