### PR TITLE
core(renderer): fix null Util.i18n in PSI renderer

### PR DESCRIPTION
**Pull request by jazyan**
**Summary**
When testing the imported renderer code in PSI, the report failed to render as seen below:
image
This change fixes the error by initializing `Util.i18n` in the [same way](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/report/html/renderer/report-renderer.js#L188-L193) as in `report-renderer.js`.

### CODE REVIEW

**Comment by connorjclark** [comment]
Seems good, verified to work in PSI?

**Comment by jazyan** [comment]
> Seems good, verified to work in PSI?

Yep! Updated `psi-test.js` as well.

**Comment by jazyan** [comment]
[Travis](https://travis-ci.org/github/GoogleChrome/lighthouse/builds/691914330) has been failing with the following:
```
Error: Unexpected status code 403
  {"message":"Invalid token"}
    at ApiClient._convertFetchResponseToReturnValue (/home/travis/.nvm/versions/node/v10.20.1/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:69:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn dogfood-lhci" exited with 1.
```
I think #10828 will resolve this? But anyone LMK if that's incorrect, and I'm instead missing something in this PR 🙂

**Comment by patrickhulce** [comment]
@jazyan that should be fixed by https://github.com/GoogleChrome/lighthouse/pull/10828 that connor just merged :)

**Pull request merged**
