### PR TITLE
Add rel=noreferrer to audit gather

### PR DESCRIPTION
**Pull request by ev1stensberg**
#2482 Could somebody test this though?

### CODE REVIEW

**Comment by ebidel** [comment]
According to the spec:
> For historical reasons, the `noreferrer` keyword implies the behavior associated with the `noopener` keyword when present on a hyperlink that creates a new browsing context. That is, `<a href="..." rel="noreferrer" target="_blank">` has the same behavior as `<a href="..." rel="noreferrer noopener" target="_blank">`.

So, you're correct that browsers which implement `rel="noopener"` will treat `rel="noreferrer"` as `rel="noreferrer noopener"`. IOW, you'll get the same security and perf benefits. Verifiable here: [example](http://jsbin.com/xajatuveru/edit?html,output). However, I'm sure if if the reverse is true for browsers that don't support it. 

A big motivation of this audit is about the performance benefit it brings, so we should be careful about changing the description language if `rel="noreferrer"` (by itself) doesn't do anything for perf. Using `rel="noreferrer"` also has other implications for tools that take in the`HTTP_REFERER` header.

IMO, `rel="noopener"` is the more modern approach and [support is decent](http://caniuse.com/#search=noopener) across browsers. Alternatively, we could just add a note to https://developers.google.com/web/tools/lighthouse/audits/noopener that mentions adding `rel="noreferrer"` for older browsers.  WDYT? cc @kaycebasques

**Comment by patrickhulce** [comment]
> if rel="noreferrer" (by itself) doesn't do anything for perf

@ebidel how would `noreferrer` not give you the benefits? I thought we just established from the spec it is a strict superset of the disassociation. 33% global exposure to a serious potential phishing issue is pretty high to not suggest adding `noreferrer` at all, the ROI on adding it is so so good. I don't think we should enforce it as a requirement since there are very valid reasons to keep the Referrer header, but it's worth highlighting in the description of helptext IMO

**Comment by ebidel** [comment]
> I thought we just established from the spec it is a strict superset of the disassociation.

It would be nice for someone to verify this in a browser that doesn't support `rel="noopener"`. This page would work: http://jsbin.com/xajatuveru/edit?html,output

> worth highlighting in the description of helptext IMO

Any details not required to pass the audit should live in the [audit references](https://developers.google.com/web/tools/lighthouse/audits/noopener). https://github.com/GoogleChrome/lighthouse/blob/master/CONTRIBUTING.md#helptext-guidelines

**Comment by patrickhulce** [comment]
> Any details not required to pass the audit should live in the audit references. 

Bitten by my own proposal 😆 maybe I do actually want to enforce it then, it seems important for a developer to be aware of this exposure and exclusively mentioning noopener here would give no indication of that (and thus no incentive to click Learn More since it can be deduced from the help text alone how to make it pass in that case), passing the audit would still leave a large vulnerability window.

> It would be nice for someone to verify this in a browser that doesn't support rel="noopener".

Ah gotcha, yes all of the above is conditioned on whether they actually behave as stated :)

**Comment by paulirish** [comment]
if our ultimate recommendation is that `rel="noreferrer noopener"` is the most comprehensive way to set this (with all the browser support), then we should just audit for that.  otherwise it's unclear what we want and what they should do.

**Comment by ev1stensberg** [comment]
I'll let you decide what 2 do with this

**Comment by jimmywarting** [comment]
I actually prefer noreferrer instead of noopener in one of my websites.
It's more anonymas which is more important for my users. (leaving of the referrer header)

I think either or should be fine, let the user decide which he wants to use

**Comment by paulirish** [comment]
#4920 took care of this.

**Pull request closed without merging**
