### PR TITLE
Add license to lighthouse-logger.

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by mikesherov** [comment]
Thank you!

**Comment by brendankenny** [comment]
is the LICENSE file necessary with one at the repo root? Or is this to make sure it's in the npm module? If so, should we add one to `chrome-launcher` as well?

**Comment by samccone** [comment]
If someone consumes this module directly then yes for those users it is needed.

**Comment by mikesherov** [comment]
Just as FYI, either LICENSE file or license field works for my use case, which is we use `license-to-fail` to autoscan our deps and fail builds on it and that tool looks in NPM license field or for LICENSE file

**Comment by mikesherov** [comment]
Thanks again!

**Pull request merged**
