### PR TITLE
deps: update old transitive deps

### PR DESCRIPTION
**Pull request by brendankenny**
Try to silent any automated security complaints before the new release. Also I like deleting unneeded dependencies.

All of these were transitive deps.

- json-ld's dep of a dep is technically a dependency, not a devDependency, but it looks like maybe CLI only? w/e

- `isomorphic-fetch`'s `node-fetch` needed to be updated, but since in node `isomorphic-fetch` [literally just calls `node-fetch`](https://github.com/matthew-andrews/isomorphic-fetch/blob/fc5e0d0d0b180e5b4c70b2ae7f738c50a9a51b25/fetch-npm-node.js) (adding a default `https` we don't need anywhere), and we don't need the "isomorphic" part (since we would be running in Chrome which has `fetch`), easy to cut out the middle library and use `node-fetch` directly. _(edit: also `isomorphic-fetch` had a 3.0.0 release but there's [no release info](https://github.com/matthew-andrews/isomorphic-fetch/releases) and tracking down what changed seemed like too much work :)_

- the deps in [`legacy-javascript/yarn.lock`](https://github.com/GoogleChrome/lighthouse/blob/88cb0207a8dd0e43d5901e93fb58e545ea20ec75/lighthouse-core/scripts/legacy-javascript/yarn.lock) are a complete stretch as a problem, but given that automated tools _are_ picking them up, and the version bumps are super tiny, it seemed worth it for now

### CODE REVIEW

**Comment by patrickhulce** [comment]
> the deps in legacy-javascript/yarn.lock are a complete stretch as a problem, but given that automated tools are picking them up, and the version bumps are super tiny, it seemed worth it for now

Should we just exclude these from our npm bundle?

**Comment by brendankenny** [comment]
> > the deps in legacy-javascript/yarn.lock are a complete stretch as a problem, but given that automated tools are picking them up, and the version bumps are super tiny, it seemed worth it for now
> 
> Should we just exclude these from our npm bundle?

I guess they are excluded...at least they won't be in a pristine checkout. "automated tools are picking them up" may actually just be automated tool _singular_. Dependabot checking `yarn.lock` files in repos :)

**Comment by paulirish** [comment]
just curious.. how do you determine/make changes like 3589b8736e0a621bca5c76f395c562b141290d50 and 488bea1a3dfc2ba2fd08fac6bdec0ad6e9075135  ?

**Review by patrickhulce — APPROVED** [review]

**Comment by brendankenny** [comment]
> just curious.. how do you determine/make changes like [3589b87](https://github.com/GoogleChrome/lighthouse/commit/3589b8736e0a621bca5c76f395c562b141290d50) and [488bea1](https://github.com/GoogleChrome/lighthouse/commit/488bea1a3dfc2ba2fd08fac6bdec0ad6e9075135) ?

A mixture of `yarn why dep` and manually traversing the `yarn.lock` tree for the dependency with a vulnerability, deleting blocks, and seeing what `yarn` will regenerate.

Which sounds terrible and probably is but you get pretty fast at it, I guess :)

**Pull request merged**
