### PR TITLE
fix(link): Update broken plugin example link

### PR DESCRIPTION
**Pull request by alabiaga**
Fix broken plugin example link

### CODE REVIEW

**Comment by alabiaga** [comment]
@patrickhulce No problem. Also the plugin example doesn't quite work for me. I get the chrome example.com instance up when running the command mentioned (npx lighthouse https://example.com --plugins=lighthouse-plugin-example --view) in the readme but don't see the the plugin results as the screenshot indicates? Should I file a bug or am I missing something? Thanks

**Comment by patrickhulce** [comment]
> but don't see the the plugin results as the screenshot indicates? Should I file a bug or am I missing something? 

Are you sure you've installed the recipe package at the same level as lighthouse? We might want to update the instructions to elaborate on that point since at the moment it's somewhat unclear what it takes to run it.

**Comment by alabiaga** [comment]
> > but don't see the the plugin results as the screenshot indicates? Should I file a bug or am I missing something?
> 
> Are you sure you've installed the recipe package at the same level as lighthouse? We might want to update the instructions to elaborate on that point since at the moment it's somewhat unclear what it takes to run it.

> Install as a (peer) dependency, parallel to lighthouse
  Yea this wasn't clear to me. Got it. Thanks

**Comment by alabiaga** [comment]
@alabiaga  merge pls.

**Pull request merged**
