### PR TITLE
core(traces): disable cpu profiler trace category

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Let's hope this fixes 🤞  https://github.com/GoogleChrome/lighthouse/issues/12835#issuecomment-891281292

**Related Issues/PRs**
closes https://github.com/GoogleChrome/lighthouse/issues/12835
partially reverts #12692
improves #12837

### CODE REVIEW

**Review by adamraine — APPROVED** [review]
LGTM. @paulirish might need a force merge to get by the unit test issues.

**Comment by brendankenny** [comment]
I'll disable for a minute. No one sneak anything in, pls

**Comment by brendankenny** [comment]
very nice find, @patrickhulce!

**Comment by brendankenny** [comment]
cc @victorporof, we had to disable those trace categories for now due to #12835

**Pull request merged**
