### PR TITLE
deps: update lighthouse-plugin-publisher-ads to latest

### PR DESCRIPTION
**Pull request by brendankenny**
get the [plugin updates](https://github.com/googleads/publisher-ads-lighthouse-plugin/releases) since the last bump in november into 8.0

### CODE REVIEW

**Review by paulirish — APPROVED** [review]

**Comment by connorjclark** [comment]
new devtools test update

**Review by connorjclark — APPROVED** [review]

**Comment by paulirish** [comment]
failure on dbwtester. weird.

image
image

**Comment by brendankenny** [comment]
> failure on dbwtester. weird.

just windows, too, and twice :/

**Comment by paulirish** [comment]
> > failure on dbwtester. weird.
> 
> just windows, too, and twice :/

Just ran locally and got a different failure. 

image

investigating…

**Comment by paulirish** [comment]
Ah. after a re-run, it's passed.

**Pull request merged**
