### PR TITLE
clients(lr): set CPU throttling based on benchmark

### PR DESCRIPTION
**Pull request by adamraine**
Closes https://github.com/GoogleChrome/lighthouse/issues/16201

### CODE REVIEW

**Review by paulirish — APPROVED** [review]
desktop config too.

This is kinda a breaking change.. wdyt about rollout?

**Comment by paulirish** [comment]
> desktop config too.

oh its already 1 in desktop. cool.

**Comment by benschwarz** [comment]
I'd be quite keen in experimenting with this too, especially in non-lantern mode, which… might require different configuration. 

@adamraine is the (end goal) idea that the benchmarkIndex will be dynamically applied for CLI/devtools/non-LR contexts? I know this has been discussed for literal years, so I'm curious as to _why now_ in particular?

**Comment by adamraine** [comment]
> This is kinda a breaking change.. wdyt about rollout?

It's a breaking change for PSI, and would have significant affects there but core API users wouldn't see any change. I would prefer to not wait for 13.0 to do this change but not sure how we have handled this in the past.

> I'd be quite keen in experimenting with this too, especially in non-lantern mode, which… might require different configuration.

I think PSI/LR only uses lantern throttling, so I don't expect this change to affect DevTools throttling.

> @adamraine is the (end goal) idea that the benchmarkIndex will be dynamically applied for CLI/devtools/non-LR contexts? I know this has been discussed for literal years, so I'm curious as to why now in particular?

This is more of a one-off change for PSI since we statistics about the benchmark index there, not anything working towards dynamic CPU throttling.

As for why now, it seems like the conversation just resurfaced in https://github.com/GoogleChrome/lighthouse/issues/16201. Seems like the dynamic CPU throttling challenge hit significant blockers in https://github.com/GoogleChrome/lighthouse/issues/9085, but I'm still trying to understand if we every considered this one-off change for PSI before.

**Comment by paulirish** [comment]
> I would prefer to not wait for 13.0 to do this

agree!  was mostly asking about PSI rollout :) but we can discuss that elsewhere.

**Comment by adamraine** [comment]
The last time I found this discussion was in https://github.com/GoogleChrome/lighthouse/issues/9085#issuecomment-497475375:

> Separate tuning of our exact throttling multiplier for PSI to better account for the longer task lengths we see there is still advised.

So I don't think there was every any opposition to PSI-specific tuning. I'm gonna land this but we should discuss PSI rollout separately.

**Pull request merged**
