### PR TITLE
clients(lr): don't include html report assets in bundle

### PR DESCRIPTION
**Pull request by connorjclark**
Lightrider doesn't support HTML output, so the entire assets module can be ignored.

7.01 MB -> 6.77 MB (3%) (the JS is much smaller now thanks to @wardpeet, so the impact is minimal)

### CODE REVIEW

**Comment by patrickhulce** [comment]
> 7.01 MB -> 6.77 MB (3%)

I'm sorry does this mean the lightrider bundle is **7** MB!? 😱

**Comment by connorjclark** [comment]
locales are very heavy :(

**Comment by connorjclark** [comment]
it takes 80ms for node to parse the locales :P

@exterkamp and I agree it's not worth the complexity to split those off (like we are doing for devtools).

**Comment by paulirish** [comment]
> it takes 80ms for node to parse the locales :P

we could use this pattern to probably speed that up. https://v8.dev/blog/cost-of-javascript-2019#json

(we'd want to do it after the refactors starting in [jon's PR](https://github.com/GoogleChrome/lighthouse/pulls) though)

**Comment by connorjclark** [comment]
was curious about the breakdown for all that locale data in terms of processing time. did some tests:

+30ms for parsing the bundle
+60ms for evaluating locales.js (the require)

So it seems 1/3 the cost of JSON-in-JS is attributable to parsing, and 2/3 is attributable to execution. I'd see how much the execution goes down for `JSON.parse`, but I don't know off-hand how to do that for browserify.

**Pull request merged**
