### PR TITLE
v6.1.1

### PR DESCRIPTION
**Pull request by connorjclark**
Patch release for #11036.

Our scripts aren't intended for patch releases, so I'll describe what I did.

1. make branch `v6.1` from the tag `v6.1.0`.
2. cherry pick the single commit I wanted
3. push branch
4. modify `prepare-commit.sh` [1]
5. run `prepare-commit.sh 6.1.1` as normal; changelog was as expected

[1]
```
diff --git a/lighthouse-core/scripts/release/prepare-commit.sh b/lighthouse-core/scripts/release/prepare-commit.sh
index 2d4c34b77..28840f27f 100755
--- a/lighthouse-core/scripts/release/prepare-commit.sh
+++ b/lighthouse-core/scripts/release/prepare-commit.sh
@@ -27,12 +27,12 @@ fi
 
 if [[ -n "$(git status --porcelain)" ]]; then
   echo "Repo has changes to the files! Commit or stash the changes to continue."
-  exit 1
+  # exit 1
 fi
 
 # Checkout a new branch for the version commit
-git fetch origin master
-git checkout origin/master
+# git fetch origin master
+# git checkout origin/master
 git log -n 1
 git branch -D "$BRANCH_NAME" || true
 git checkout -b "$BRANCH_NAME"

```

### CODE REVIEW

**Comment by patrickhulce** [comment]
hm not entirely sure how to merge this since we only allow squashing through GitHub UI but it'd be nice to retain the individual feature commit. maybe just do it manually now that it's approved? 

could also just squash and leave the longform message there since it's just one commit, not a big deal

**Comment by connorjclark** [comment]
this fetcher commit is in v6.1 so I am super confused why it shows as a file diff here. https://github.com/GoogleChrome/lighthouse/commits/v6.1

**Comment by connorjclark** [comment]
did a merge from v6.1 and that fixed it

**Comment by patrickhulce** [comment]
Ah cool! yeah now squash is 👌

**Pull request merged**
