### PR TITLE
core(emulation): bump chrome UA to m109 and drop LH identifier

### PR DESCRIPTION
**Pull request by paulirish**
Sorry for the inconvenience folks. But we had to make this change due to some developers who prioritize gaming over user experience.

Relevant: b/244577753

### CODE REVIEW

**Comment by benschwarz** [comment]
@paulirish gaming is definitely a thing, but does it actually outweigh people using the UA header to identify LH traffic for bot detection/WAF?

**Review by brendankenny — APPROVED** [review]

**Comment by connorjclark** [comment]
> @paulirish gaming is definitely a thing, but does it actually outweigh people using the UA header to identify LH traffic for bot detection/WAF?

Are you saying you know of usecases where a firewall allows traffic just because a header say's a request is from Lighthouse?

**Comment by benschwarz** [comment]
> Are you saying you know of usecases where a firewall allows traffic just because a header says a request is from Lighthouse?

Yep, absolutely. People check for presence of `Chrome-Lighthouse` as the default easy way to identify incoming traffic (I suspect this is because PSI and other tools do not provide another mechanism to do so). They do so to either alter the response (score hacking), or to let traffic through to staging/preview URLs.

**Comment by connorjclark** [comment]
We're just gonna update the major version, we'll keep the Lighthouse identifier for now at least.

**Comment by fevangelou** [comment]
Oh no... now we have to remove all Google products that **really** were the cause for low LH scores.

You know: Google Analytics, Google Ad Manager, Google Tag Manager, Google AdSense.

Without these it was always 90%+ on LH. I guess it's 2 teams at Google. One that works on improving performance and one that kills it. Maybe it's time the 2 got in touch?

Food for thought folks...

**Comment by BuslikDrev** [comment]
Когда ждать обновление https://pagespeed.web.dev/? А то конкуренты по оптимизации дурят людей =)

**Comment by subhajeetdey** [comment]
HI, colleagues we are using this header checks to detect if we should run PSI tests on staging environments without this header we wont be able to identify

**Comment by benschwarz** [comment]
@Xowap I can understand that you have frustration, though your comments here are both unhelpful and misguided.

> Don't even get me started at other Google products like YouTube or Google Fonts that immediately cost you 50 points when you put them on your page.

**The Lighthouse team aren't responsible for YouTube or Google Fonts.** If you add third party resources to your pages, they have a performance cost, just like any resource on your pages. That's on you and your team to decide what's reasonable, plan and adapt. 

As an alternative to YouTube, you could use [lite-youtube-embed](https://github.com/paulirish/lite-youtube-embed), written by @paulirish 🙃

As an alternative to Google Fonts, you can self host fonts, or use less web fonts.

> When you work in an agency and that all your clients ever heard about SEO is that "if the score is too low Google will penalize you" you have no choice but to get the score up.

Lighthouse / PageSpeed has no impact on SEO rankings. Site speed is determined by analyzing the Chrome User Experience Report (CrUX).

**Comment by fevangelou** [comment]
To all those frustrated with this change, who used the user agent for Lighthouse to filter out third party content, I recommend the following:

a) Educate your clients. If your work is great (like 80+ score) without ads, analytics, widgets etc., make a page variant (/?nocrap) that doesn't load them. This will reveal the true score of YOUR work. In turn this exposes the laziness of others and of course the true cost of crap (eg FB page widget in 2023? Twitter/FB share buttons? Come on...).

b) If one of your clients says "but website X has a score of 90 with ads blah blah", check that site's code. Their devs mostly resort to gimmicks to fool their clients, like loading ads, analytics etc. when the user starts interacting with page (eg scrolls). Which is pointless eventually as true users will count over the actual site score.

And in the end, what matters is THIS aggregate score of real user data that is presented in the Search Console.

It doesn't take a genius to understand why Google is pushing for performance so much. Sure, there was a time that slow sites may have caused practical issues in Google crawl bots. I believe the incentive is somewhat different nowadays, now that 3rd party generative AI is essentially competing with Google products on many fronts.

You see, large sites that generate ad revenue for Google may utilize multiple ad networks all competing (bidding) for ads, from the same ad pool. Google seems to have improved their performance on their third party code added via DFP, AdSense and so on. Other ad networks and Google ad brokers haven't. So when publishers are cornered by performance, they will have to make a choice: either continue with multiple ad networks hoping to maintain revenue, or ditch all but Google in the hopes that their traffic will improve, offsetting Google paying less for ad display compared to specialized ad networks that do "header bidding".

Put all these into perspective and move on.

**Comment by adamraine** [comment]
Using the UA identifier to remove certain content for Lighthouse is exactly what this patch is designed to prevent. Users can still experience a negative impact to performance regardless of if the content first party or third party. Ignoring the effects of third parties isn't justifiable just because those third parties are Google products. That's a kind of bias we should prevent, not encourage.

As @benschwarz said, Lighthouse/PageSpeed scores are not a heuristic used by search engines to rank your page. Gaming the score won't improve SEO, it will just present an inaccurate assessment of performance.

So why do we care if you intentionally test different content than what users see? It's because it isn't always intentional, sometimes developers don't even realize it's happening ([example](https://twitter.com/GijoVarghese_/status/1563097754322501632)).

**Pull request merged**
