### PR TITLE
Add logging to extension driver.

### PR DESCRIPTION
**Pull request by paulirish**
image

### CODE REVIEW

**Comment by brendankenny** [comment]
maybe file an issue for adding support for logging levels when in the extension and using `console.log`?

**Comment by brendankenny** [comment]
LGTM, but let's wait on #156 so it doesn't have to rebase again

**Comment by brendankenny** [comment]
looks like no merging conflicts

**Comment by paulirish** [comment]
> maybe file an issue for adding support for logging levels when in the extension and using console.log?

because its only visible when debugging the background page i think its lower priority, but if anyone feels strongly we can put it on the backlog.

**Pull request merged**
