### PR TITLE
docs(user-flows): update api usage

### PR DESCRIPTION
**Pull request by adamraine**
Fixes https://github.com/GoogleChrome/lighthouse/issues/13825

### CODE REVIEW

**Review by connorjclark — APPROVED** [review]
any chance you'd like to move this code into `recipes` and make a test that runs via yarn test-docs ?

**Comment by adamraine** [comment]
> any chance you'd like to move this code into recipes and make a test that runs via yarn test-docs ?

We already exercise the flow api in the sample json test. Even if we made a doc specific test, it would still be possible for the doc snippets and test to get out of sync.

**Comment by connorjclark** [comment]
> Even if we made a doc specific test, it would still be possible for the doc snippets and test to get out of sync.

The purpose of the docs test is that we provide starting code that works, and can be confident that we never break that (and don't need to constantly manually verify it / wait for a user to report a bug). As the linked issue shows, we had code in docs that was old, which 1) something as minimal as type checking would have caught and 2) a full end-to-end test, like other recipes, would have caught.

For these docs in particular we just need to remember them as we make any other high level API changes, so I'm not suggesting it's worth the effort to do this. For other recipes it def. was (since maybe something lower level could break them)

**Comment by adamraine** [comment]
> For these docs in particular we just need to remember them as we make any other high level API changes, so I'm not suggesting it's worth the effort to do this. For other recipes it def. was (since maybe something lower level could break them)

It might be worth it, I would like to do it in a separate PR though.

**Pull request merged**
