### PR TITLE
core(tsc): update to tsc 3.3.333

### PR DESCRIPTION
**Pull request by Hoten**
no changes needed.

### CODE REVIEW

**Comment by Hoten** [comment]
I didn't exhaustively look to see how the new features could be used. I really wanted 3.4 but that's still in beta.

**Comment by patrickhulce** [comment]
> I didn't exhaustively look to see how the new features could be used. I really wanted 3.4 but that's still in beta.

Oh, well I mean what prompted the update then I guess is what I'm asking. Why do we care about 3.3.3? :)

**Comment by Hoten** [comment]
> Why do we care about 3.3.3? :)

I don't, I just had 5 minutes to kill on the bus. Do you suggest we not update?

**Comment by patrickhulce** [comment]
Oh haha 😆 then yeah I'd vote for not updating if there's no reason too. Just seems like noise otherwise.

**Comment by Hoten** [comment]
I was thinking there might be necessary changes, which would need to be made for the 3.4 update (which I do care about). But there were none :yay:

fine with me

**Comment by brendankenny** [comment]
> Why do we care about 3.3.3?

I haven't seen anything we'd immediately want. [3.4 will have some nice things](https://github.com/Microsoft/TypeScript/wiki/Roadmap#34-march-2019) around better generic inference and better readonly support, but I don't believe it should affect anything we currently use either, only open up options for future use.

([`as const`](https://github.com/Microsoft/TypeScript/pull/29510) would be super helpful for us, but it doesn't work in JS (yet))

**Pull request closed without merging**
