### PR TITLE
fix(url-shim): do not elide short names with preserveHost

### PR DESCRIPTION
**Pull request by patrickhulce**
R: all

### CODE REVIEW

**Comment by patrickhulce** [comment]
> from …img/logo.jpg to /img/logo.jpg. Is that intentional?

Yep, I'll add that test to make it explicit.

> Also the double // in something like http://example.com//logo.jpg would no longer be preserved, though I don't know why someone would want it to be

Haha, fair :) I'll switch to another method

**Comment by patrickhulce** [comment]
PTAL :)

**Comment by brendankenny** [comment]
> I'll switch to another method

looks like you didn't? Does it matter?

**Comment by brendankenny** [comment]
oh, looks like my example was wrong.

`URL.getDisplayName('http://example.com//logo.jpg', {preserveHost: true})` gives `example.com//logo.jpg`, but

`URL.getDisplayName('http://example.com/img/img//logo.jpg', {preserveHost: true})` drops the double // and gives `example.com/…img/logo.jpg`

**Comment by patrickhulce** [comment]
Oh, yeah, realized it doesn't matter for the upfront case you mentioned
(captured by test), only in the middle of a URL, so stopped changing :) but
can continue if we think it'll come up

**Comment by patrickhulce** [comment]
I'm sticking by it too FYI because 
A) it should be rare
B) the way we currently express path parts and ellipsis isn't great to begin with. `/a/b//foo.js` after today becomes `...b/foo.js` but would become just `.../foo.js` after a fix (since the second path part is empty)

bump :)

**Comment by brendankenny** [comment]
> the way we currently express path parts and ellipsis isn't great to begin with

yeah, it's just a display URL, so, SGTM. But we're assigning you the bug when someone inevitably files an issue because `///` in their URLs is essential to their workflow :P

**Comment by patrickhulce** [comment]
> But we're assigning you the bug when someone inevitably files an issue because /// in their URLs is essential to their workflow :P

hahaha deal!

**Pull request merged**
