### PR TITLE
misc: use `CHROME_PATH` variable in CI and scripts

### PR DESCRIPTION
**Pull request by r0mflip**

### CODE REVIEW

**Comment by r0mflip** [comment]
@patrickhulce Setting `$CHROME_PATH` alone just makes the script to exit. Even though I use the suggested variable name I would have to set `$LIGHTHOUSE_CHROMIUM_PATH` anyways. This PR changes that behavior.

**Comment by patrickhulce** [comment]
> Even though I use the suggested variable name I would have to set $LIGHTHOUSE_CHROMIUM_PATH anyways

I understand; it's a good update to make us get off the deprecated chrome-launcher variable :) I was just also noting for other readers that this variable name does still work in `chrome-launcher` even though we change it for our download script here in Lighthouse.

**Comment by r0mflip** [comment]
I totally understand 😇

**Pull request merged**
