### PR TITLE
Using npm script to launch chrome

### PR DESCRIPTION
**Pull request by ragingwind**
I think it would be in consistence with other scripts

### CODE REVIEW

**Comment by paulirish** [comment]
Let's keep the file there.. we want to reuse it from travis, etc.  and it'd be useful to have it sort out Linux and CI environments etc.

but i like the idea of having `npm run chrome` kick it off. lets just define that script to run the `.sh` file. sg?

**Comment by ragingwind** [comment]
Sounds good to me :+1: I will update this

**Comment by ragingwind** [comment]
@paulirish I've updated for it.

**Comment by paulirish** [comment]
thanks jimmy! appreciate it.

**Pull request merged**
