### PR TITLE
core(cls): shorten description

### PR DESCRIPTION
**Pull request by connorjclark**
image

It's a bit long ...

I shortened it without removing any information - simplified the grammar constructs (`being a ...` is a longer way to say `is`).

Further ideas for simplification / changes:

1)
```
A layout shift is any movement an element makes once it is visible
->
A layout shift is when an element moves.
```

2)
```
Layout shifts are recorded, scored, and then aggregated into a cumulative score between 0 and 1; 0 is a stable page, and >=0.5 is a highly shifting page
->
Layout shifts are aggregated into a score between 0 and 1; 0 is a stable page, and >=0.5 is a highly shifting page
```

3)

0.5 seems like a high range. even 0.33 looks "highly shifting"

image

4)

"between 0 and 1" is not true. CLS can be >1.

### CODE REVIEW

**Comment by paulirish** [comment]
i think we can drop the scoring bit. the learnmore link covers that.

here's my attempt at a really terse explanation:


> Cumulative Layout Shift measures the amount of layout changes of visible elements within the viewport, scaled by element size and movement distance.

**Comment by connorjclark** [comment]
> Cumulative Layout Shift measures the amount of layout changes of visible elements

i raise you this

**Comment by brendankenny** [comment]
I'll cede this one to @paulirish

**Comment by paulirish** [comment]
> > Cumulative Layout Shift measures the amount of layout changes of visible elements
> 
> i raise you this

works for me.

**Comment by connorjclark** [comment]
wording was a little awkward and I didn't like reusing 'layout'

```
Cumulative Layout Shift measures how much visible elements move around the page
```

**Comment by brendankenny** [comment]
> wording was a little awkward and I didn't like reusing 'layout'
> 
> ```
> Cumulative Layout Shift measures how much visible elements move around the page
> ```

Now i'm not so sure about this :)

"how much" causes a miscue for me while reading, where I think the thing immediately after it is what's being measured, then it reads like a grammar error ("how much visible elements?") and then I realize "move" is what is being measured, but by then I've lost the flow.

If we want to keep this general form, something like

```
Cumulative Layout Shift measures the movement of visible elements around the page.
```
(or within the viewport, etc) could also work.

**Comment by paulirish** [comment]
sure.

i like: 

> Cumulative Layout Shift measures the movement of visible elements within the viewport.

**Pull request merged**
