### PR TITLE
docs: update required chrome version

### PR DESCRIPTION
**Pull request by patrickhulce**
#5424 got me thinkin' :)

### CODE REVIEW

**Comment by paulirish** [comment]
i wonder if we should just point to https://googlechromelabs.github.io/current-versions/ and say "stable"

**Comment by patrickhulce** [comment]
Meh, I'm somewhat ambivalent. We don't really *need* to update it that often, but it is a pain to remember.

**Comment by paulirish** [comment]
sure.

related: 
#5424 looks like it was with Chromium 65, which is recent enough to not have headless issues, id expect.
so i dont know if a bump to 66 really woulda solved it for him

**Comment by patrickhulce** [comment]
#5424 got me thinking not because it had anything to do with his problem but because the bug contained the error message "The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later" which is definitely wrong at this point.

**Pull request merged**
