### PR TITLE
core(audits): Disable video-description

### PR DESCRIPTION
**Pull request by Malvoz**
axe deprecated their video-description rule in https://github.com/dequelabs/axe-core/pull/1737 due to poor implementations of the `descriptions` keyword for the `<track kind="">` attribute. I'm unsure whether their deprecation warrants a complete removal, this PR simply disables the audit.

(I reordered the audits alphabetically for readability.)

### CODE REVIEW

**Comment by patrickhulce** [comment]
cc @robdodson do you agree?

**Comment by robdodson** [comment]
I recall @mfriesenhahn was working on this. I don't quite recall where we last left things, but I do seem to remember that no browser really supports this at the moment—I think it requires users to install an extension to get the descriptions to play. Michael, what do you think about having LH disable the audit or moving it to manual audit?

**Comment by mfriesenhahn** [comment]
We're waiting on the LH folks to confirm that the audit is being switched to a manual check before publishing the update :)

**Comment by patrickhulce** [comment]
Oh was there already a conversation about this I don't know about and/or have forgotten about @mfriesenhahn? Any chance you know the link? :)

**Comment by mfriesenhahn** [comment]
Here's [the web.dev PR](https://github.com/GoogleChrome/web.dev/pull/1700) where @kaycebasques mentions that y'all expect to have audits converted to manual in Q2.

**Comment by patrickhulce** [comment]
Gotcha thanks for that @mfriesenhahn! I don't have access to either thread that @kaycebasques links to in that PR for what we're waiting on, so I'll defer to someone internal on this one.

**Comment by robdodson** [comment]
This is what @paulirish says in the first thread:


>so first, we'll be removing video-description when we update axe next (as they just deprecated it).

>and for audio-caption, video-caption:
>if axe passes it. we'll pass it.
>if axe marks them as incomplete, we'll switch them to manual, to tell the user that they have to review their videos individually to verify they have captions delivered via JavaScript.
>This requires a bit more internals refactoring so it's not going to happen in our next release, however.

>More likely it's a Q2 thing.

**Comment by mfriesenhahn** [comment]
Thanks, @robdodson! I actually didn't have access to those threads either, so this is the first time I'm seeing the details. Very helpful.

**Comment by patrickhulce** [comment]
> so first, we'll be removing video-description when we update axe next

Alright that sounds like a go-ahead to me!

@Malvoz we can delete the video-description audit code, remove it from the config, and eliminate any tests if you're up for it :)

**Comment by paulirish** [comment]
@Malvoz are you still up for removing this audit?  [patrick's comment](https://github.com/GoogleChrome/lighthouse/pull/10128#issuecomment-574803340) covers what is needed.

**Comment by Malvoz** [comment]
@paulirish and others, sorry for stalling. I am quite busy at the moment so if anyone can take this on that'd be great.

**Comment by connorjclark** [comment]
Closing, will do as part of https://github.com/GoogleChrome/lighthouse/issues/11207

**Pull request closed without merging**
