### PR TITLE
gatherers(stack-collector): use isolation

### LINKED ISSUE #10065: pages the modify fetch mess with gathering
#### **Provide the steps to reproduce**
1. Run LH on <affected url>
- Go to https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.tiffany.com and the page speed score does not load. 
  

#### **What is the current behavior**?
I'm trying to pull lighthouse scores for www.tiffany.com but every time i do i receive a "backend error" message. This issue started around Sep 4th, prior to that date, i was able to pull lighthouse KPI's however the SEO score has never been able to populate.

**Today i get the following message:** Lighthouse returned error: generic::internal: Extension result empty. Lighthouse calling Page.navigate with https://www.tiffany.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5525:13) at http://ghost-rider/devtools_script_api.js:708:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:707:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:689:65) at <anonymous>:1:40 Dismiss

#### **What is the expected behavior?**
I expect to see a desktop and mobile speed scores pulled i from lighthouse. 

#### **Environment Information**
* Affected Channels:  All channels
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System: windows & mac

**Related issues**

### PR DESCRIPTION
**Pull request by exterkamp**
Isolate `stack-collector`.

fixes #10065

### CODE REVIEW

**Comment by philkrie** [comment]
Just as an FYI, testing this myself on https://developers.google.com/speed/pagespeed/insights/, that issue #10065 doesn't appear to be resolved: [example](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.tiffany.com%2F)

**Comment by patrickhulce** [comment]
@philkrie it hasn't been deployed to PSI yet. This will be released in Lighthouse 6.0.0.

**Comment by philkrie** [comment]
@patrickhulce thanks for the clarification, when will LH 6 be used in PSI?

**Comment by patrickhulce** [comment]
@philkrie no set date, but 6.0.0 has to be finalized first so at least another few weeks.

**Pull request merged**
