### PR TITLE
Get chromium path from env var on Linux

### PR DESCRIPTION
**Pull request by deepanjanroy**
For #106

### CODE REVIEW

**Comment by brendankenny** [comment]
I like this change. Do you want to fix it so the test server also runs it this way? Feel free to do a follow up PR instead of adding another commit to this one.

Right now the test server downloads a continuous Chrome build in [test/download-chrome.sh](https://github.com/GoogleChrome/lighthouse/blob/beab048471cbc983fa90355682f6910b4a55c183/test/download-chrome.sh), so you would need to
- change `chromepath` in `download-chrome.sh` to `LIGHTHOUSE_CHROMIUM_PATH` and
- drop the manual launch of Chrome on this line in [.travis.yml](https://github.com/GoogleChrome/lighthouse/blob/beab048471cbc983fa90355682f6910b4a55c183/.travis.yml#L13) to instead just run your `launch-chrome.sh`

I think we do need that extra `--disable-setuid-sandbox` flag for that case (a downloaded continuous build that's not Chrome and we didn't build ourselves), but not when running on Linux in general, which adds another wrinkle. For those that haven't run into this, this has more details: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md#Try-bots-and-waterfall

**Comment by paullewis** [comment]
Happy to merge. Do you want to update the tests as per @brendankenny's suggestion, or roll with this as-is?

**Comment by deepanjanroy** [comment]
Let me do a separate PR for the tests.

**Comment by paullewis** [comment]
Done.

**Pull request merged**
