### PR TITLE
docs: remove dead link

### PR DESCRIPTION
**Pull request by connorjclark**
ref https://github.com/ampproject/amp-toolbox/pull/1203

### CODE REVIEW

**Comment by connorjclark** [comment]
Or maybe we link to a specific commit?

**Comment by brendankenny** [comment]
there was a start on this in https://github.com/GoogleChrome/lighthouse/pull/12390, not sure what happened...

**Comment by patrickhulce** [comment]
Ah that toolbox PR definitely seems to suggest it is dead though, I didn't realize the link I found was on `master` but they'd transitioned to `main` :) removal SGTM

**Comment by connorjclark** [comment]
interesting to know it only took 12 days to not just get a report, but a PR for a dead link! much faster than I would have guessed.

**Comment by patrickhulce** [comment]
How do we re-run the checks on a branch of a fork for the new requirements? Would be nice to give external credit :)

**Comment by patrickhulce** [comment]
fixed by https://github.com/GoogleChrome/lighthouse/pull/12390 :)

**Pull request closed without merging**
