### PR TITLE
fix: default(.json -> .js). Disable css usage audit

### PR DESCRIPTION
**Pull request by patrickhulce**
Breaking changes have landed in protocol (currently failing all AppVeyor builds) and we're punting on fixing the accuracy until after IO anyway, just disable for now.

### CODE REVIEW

**Comment by paulirish** [comment]
this now becomes a disabled audit, though we're keeping it in the source tree for good reasons.

I wonder if theres somewhere else we can clearly indicate it's disabled, as unfortunately commenting out in the default.json isn't a possibility.

how about also changing the audit.meta.name from `"unused-css-rules"` to `"DISABLED__unused-css-rules"` or something?

**Comment by brendankenny** [comment]
> as unfortunately commenting out in the default.json isn't a possibility

Time to `git mv default.json default.js`? :)

**Comment by paulirish** [comment]
> Time to git mv default.json default.js? :)

YUP. patrick wants to, too. let's do it.

**Comment by patrickhulce** [comment]
BOOM! 💥 
> paulirish added the RlsToStable label 16 minutes ago


wait, @paulirish changing default.js is not compatible with that plan...

**Comment by patrickhulce** [comment]
i'll cut a separate PR for 1.6.0 branch?

**Comment by patrickhulce** [comment]
PTAL for added json -> js :)

**Comment by patrickhulce** [comment]
oh, oops, I literally just merged :) makes it easy to find files requires with grep/simple search though so i'm actually not as jazzed about extension-less requires

**Comment by brendankenny** [comment]
fair (though I just saved a regex for that :). Main benefit is that it makes it transparent where the data is coming from (json or from executed code), but since this is the hardcoded default config it doesn't matter

**Comment by patrickhulce** [comment]
> Main benefit is that it makes it transparent where the data is coming from

You mean opaque? ;) haha, that's exactly why I don't like it!

**Pull request merged**
