### PR TITLE
Upgrades HTTPS audit

### PR DESCRIPTION
**Pull request by paullewis**
Now uses `driver.getSecurityState()`.

### CODE REVIEW

**Comment by paulirish** [comment]
do you want to the timeout in driver.getSecState instead?  
would be slightly more valuable there.

lgtm regardless.

**Comment by paullewis** [comment]
Let's open an issue for that where we can reject getSecurityState; it'd help both this and the HTTP redirect gatherer.

**Comment by paullewis** [comment]
Opened #335 for this.

**Comment by paulirish** [comment]
k

**Pull request merged**
