### PR TITLE
log.js: fix spread strings

### PR DESCRIPTION
**Pull request by paulirish**
Verbose logging regressed a bit ago:
image

Strings were being spread into arrays. :)

This PR swaps out usage of `arguments` for spread args, along with some minor cleanup of the log module.

### CODE REVIEW

**Comment by wardpeet** [comment]
Damn you beat me to it was just going to make this pr :D

**Comment by paulirish** [comment]
spread arguments aren't supported in v5. will need to adjust the approach.

**Comment by wardpeet** [comment]
Just use arguments?

**Comment by wardpeet** [comment]
can we make errors something else than white?
image

**Pull request merged**
