### PR TITLE
docs: fixed typo in documentation throttling.md

### PR DESCRIPTION
**Pull request by ryuichi1208**
**Summary**

Fixed typo in documentation

https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#devtools-lighthouse-panel-throttling

**Related Issues/PRs**

### CODE REVIEW

**Review by adamraine — APPROVED** [review]
LGTM

**Comment by adamraine** [comment]
@ryuichi1208 Make sure to sign the CLA and we can merge this.

**Comment by ryuichi1208** [comment]
done

**Comment by ryuichi1208** [comment]
@googlebot I signed it!

**Pull request merged**
