### PR TITLE
Run travis only on node "node"

### PR DESCRIPTION
**Pull request by samccone**
> This should resolve the travis CI failure around new syntax :sparkles:

### CODE REVIEW

**Comment by brendankenny** [comment]
what's the travis failure?

**Comment by samccone** [comment]
https://travis-ci.org/GoogleChrome/lighthouse/builds/118607722#L451

**Comment by brendankenny** [comment]
wait, how is that even possible? That's the only time that appears to have happened: https://travis-ci.org/GoogleChrome/lighthouse/builds

**Comment by brendankenny** [comment]
:+1: :+1:

**Comment by paulirish** [comment]
:+1:

**Pull request merged**
