### PR TITLE
Moved package.json from lighthouse-core to ligthouse

### PR DESCRIPTION
**Pull request by wardpeet**
Should fix #512 - make sure to test it all :)

### CODE REVIEW

**Comment by paulirish** [comment]
Yeah I'd say that seems great.

Hopefully we can wait for travis to get back online. And I'll green-button it in.

**Comment by wardpeet** [comment]
Rebased master into the branch.

**Comment by wardpeet** [comment]
I only looked at core but should i move extension over aswell?

**Comment by paulirish** [comment]
> I'm not sure why it doesn't fail on the other builds 

The _install_deps.js actually does run and does install the extension deps successfully on travis right now. 

I fixed this in b17f0267faaa4bdb5502e5e6ab233ced8fef9d5b where i restored a line we had a while ago.

**Comment by paulirish** [comment]
merged and all set. thank you!

**Pull request merged**
