### PR TITLE
docs(programmatic): add caveat about removing artifacts

### LINKED ISSUE #4346: Update programmatic example to delete results.artifacts
I checked every 'report.html', file size of each report is larger than 20M bytes. It is impossible to serve on websites. Is there any way to shrink the size?

### PR DESCRIPTION
**Pull request by patrickhulce**
closes #4346

### CODE REVIEW

**Comment by patrickhulce** [comment]
does this help @ganlanyuan?

**Comment by ganlanyuan** [comment]
Yes, that's helpful!
Thanks

**Comment by ganlanyuan** [comment]
But this doesn't work for me, I just get the results of `undefined`:
```javascript
return lighthouse(url, opts, config).then(results => {
  delete results.artifacts;
  chrome.kill().then(() => {
    return new ReportGenerator().generateReportHtml(results);
  })});
```
While this works:
```javascript
return lighthouse(url, opts, config).then(results =>
  chrome.kill().then(() => {
    delete results.artifacts;
    return new ReportGenerator().generateReportHtml(results);
  }));
```

**Comment by paulirish** [comment]
@ganlanyuan this is true. implicit return. updated the code to be more obvious about this. :)

**Pull request merged**
