### PR TITLE
report(header): new header WIP

### PR DESCRIPTION
**Pull request by wardpeet**
image

### CODE REVIEW

**Comment by patrickhulce** [comment]
😮 👏 👏 👏 👏 👏 👏

**Comment by vinamratasingal** [comment]
LGTM! Thanks Ward :) 

cc: @hwikyounglee

**Comment by paulirish** [comment]
Nice! Don't worry about the runtime settings for now. We can wrestle with that.

Can you address the conflicts?

(sorry, renderer is conflict party these days. :)

**Comment by wardpeet** [comment]
I still have one test to fix.

Header:
image

25%:
image

50%:
image

75%:
image

100%:
image

**Comment by hwikyounglee** [comment]
Thanks wardpeet@! 

One suggestion is to show 1) URL and 2) chevron for the runtime settings in the collapsed state. 
header-url

**Comment by wardpeet** [comment]
@hwikyounglee paul had some ideas around that but I could fix the url moving

**Comment by paulirish** [comment]
hwi's ideas are better than mine on the runtime settings, tbh. :) if you want to take a shot on that, be my guest.

**Comment by wardpeet** [comment]
@hwikyounglee @paulirish 
this is the best I could do for the limited time :(
image

image

**Pull request merged**
