### PR TITLE
misc(git3po): lock-resolved

### PR DESCRIPTION
**Pull request by connorjclark**

### CODE REVIEW

**Comment by connorjclark** [comment]
For each new rule the idea is that Paul will run it initially with an early
start date, and then the cron will take up maintenance. For this one in
particular, yeah it'd be a big bandaid so perhaps makes sense to do it
during next bug triage, when we blow ourselves up any how

**Comment by connorjclark** [comment]
The maintainer of a tool that does just this summarizes my thoughts: https://github.com/dessant/lock-threads/issues/13#issuecomment-461854159

Don't we all just mass-delete GH emails at bug triage time anyways?

**Comment by patrickhulce** [comment]
Proposal: we only do this moving forward and manually apply a label to issues that get bumped in the meantime to have the bot autolock them as well? All 6000 seems like overkill and I don't think my plebeian gmail will be able to handle it :)

**Comment by paulirish** [comment]
> Don't we all just mass-delete GH emails at bug triage time anyways?

some of us do. but in addition to the 6 of us that know about triage, we have >500 people who also watch the repo and get emails.

> Proposal: we only do this moving forward and manually apply a label to issues that get bumped in the meantime to have the bot autolock them as well?

I would prefer the manual approach as well. We apply a label and bot follows up with a lock sgtm.

**Pull request merged**
