### PR TITLE
deps: Upgrade debug to 2.6.9

### PR DESCRIPTION
**Pull request by PatOnTheBack**
**Summary**

This fixes a [ReDoS vulnerability in debug 2.6.8](https://snyk.io/test/npm/debug/2.6.8)

### CODE REVIEW

**Comment by brendankenny** [comment]
- it looks like we'd need CLA information from @snyk-test, the author of the commit. We have one from `snyk-bot`...any way to switch to that user? Or to get a CLA for @snyk-test.
- I'd call this more of a corner-case performance improvement than a DoS fix :)
- Is this an automated service? It would be good to link to any info about who is running this, etc in the profile if so.
- I'm also not sure we want to sign up for automated PRs.

**Comment by PatOnTheBack** [comment]
@brendankenny Yes, Snyk is an automated service from the GitHub marketplace. You can find out about it here: <https://snyk.io/>

**Comment by brendankenny** [comment]
> @brendankenny Yes, Snyk is an automated service from the GitHub marketplace. You can find out about it here: https://snyk.io/

yes, I was wondering if *you* were a bot, but apparently not :)

**Comment by paulirish** [comment]
thanks. i'll take care of this in #9398

**Pull request closed without merging**
