### PR TITLE
deps: update lighthouse-logger to 1.3.0

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Removes the wart introduced by #12805 and bumps our use of lighthouse-logger to be prefixed with `LH:`

**Related Issues/PRs**
ref #11313 #12805

### CODE REVIEW

**Review by brendankenny — APPROVED** [review]
LGTM

hopefully no one out there is parsing those logs too strictly :)

**Comment by connorjclark** [comment]
You'll need to update the devtools tests.

**Comment by patrickhulce** [comment]
> You'll need to update the devtools tests.

How does one do that in their broken state?

**Comment by connorjclark** [comment]
oh, forgot to land https://github.com/GoogleChrome/lighthouse/pull/12807

should be go now. `yarn update:test-devtools`

**Pull request merged**
