### PR TITLE
Add AppVeyor CI support for Windows testing.

### LINKED ISSUE #1079: Add support for AppVeyor
[AppVeyor](https://www.appveyor.com/) is a continuous delivery system for Windows that's analogous to Travis. We use it on a few of my Node projects and it's served us pretty well. Adding support would help catch issues like #1057 a little sooner. 

The only downsides to adding support are that we would then start to catch places where our tests may fail on Windows and require proper cross-platform bugfixing to get them addressed. Throwing out this idea after I mentioned it to @brendankenny today.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #1079.

**Preview**: <https://ci.appveyor.com/project/XhmikosR/lighthouse/history>

**Before merging**: one of the project maintainers needs to add AppVeyor to the repository and paste the image link so that I add it in readme.md and rebase.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@FeodorFitsner: I cannot solve the failure AppVeyor is having whatever I try :/

Something must be wrong with `PATH`. If I don't add MSYS in `PATH`, then `find` from Windows is being used so bash fails. If I add MSYS in `PATH` I'm getting another error, which I cannot explain where it's coming from.

**Comment by wardpeet** [comment]
@XhmikosR the variable isn't correctly set because mocha is not running as harmony.
Try to get appveyor working in node 6 / 7 first ;)

**Comment by XhmikosR** [comment]
Cool thanks. I meant to ask you about this. Of you really want node 4
support on Windows or not.

**Comment by XhmikosR** [comment]
@wardpeet: here is my findings so far.

1. `__node_harmony` is problematic; it's also in npm scripts which you reference it as `$__node_harmony` which doesn't work on Windows
2. `npm run build` fails for the extension with this

    ```
    C:\projects\lighthouse>pushd lighthouse-extension && npm run build && popd

    > lighthouse@ build C:\projects\lighthouse\lighthouse-extension
    > gulp build

    [19:42:57] Using gulpfile C:\projects\lighthouse\lighthouse-extension\gulpfile.js
    [19:42:57] Starting 'build'...
    [19:42:57] Starting 'lint'...
    [19:42:57] Finished 'lint' after 431 ms
    [19:42:57] Starting 'browserify'...
    [19:42:57] Starting 'browserify-lighthouse'...
    stream.js:74
          throw er; // Unhandled stream error in pipe.
          ^

    Error: Cannot find module 'debug/browser' from 'C:\projects\lighthouse\lighthouse-core\lib'
        at C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
        at process (C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
        at ondir (C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
        at load (C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
        at onex (C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
        at C:\projects\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
        at FSReqWrap.oncomplete (fs.js:82:15)
    ```

So, how do you want to proceed?

**Comment by wardpeet** [comment]
The pr that fixes debug is not merged yet.
To just test if appveyor is working you could force package.json to load debug 2.2.0 instead of 2.5.x

`"debug": "2.2.0",`

**Comment by paulirish** [comment]
@wardpeet 

> The pr that fixes debug is not merged yet.

what PR you talking about? on debug or here?

**Comment by XhmikosR** [comment]
So, I decided to try and convert the releavant scripts to JS; I started with run-mocha.sh. I don't get the dailure though so if anyone has any ideas, let me know.

**Comment by XhmikosR** [comment]
Hmm, and the build is erroneously marked as passing in Travis so that's something that should be fixed in another PR.

**Comment by wardpeet** [comment]
@paulirish it is now #1272 
@XhmikosR will make time to look at appveyor today :)

**Comment by brendankenny** [comment]
> Hmm, and the build is erroneously marked as passing in Travis so that's something that should be fixed in another PR.

It looks like the `run-mocha.js` script is absorbing the exit code, so an error in the unit tests isn't translating to an error exit code. Can mocha be used as a module instead of in a child process?

The error just seems to be the test filename pattern isn't working, so that will need to be tweaked

**Comment by brendankenny** [comment]
> it seems we'll need the glob package for wildcards to work

since MSYS is installed, can we just keep using the same `find` call we had before?

**Comment by XhmikosR** [comment]
Well, MSYS isn't a native part of Windows... And even on Windows 10, one has to manually enable Ubuntu.

That is why I suggest shell.js. It should cover all use cases regardless of the OS.

**Comment by wardpeet** [comment]
@XhmikosR lets stick with bash. If you use bash for everything appveyor will work until gulp build. I'm looking into why it's not building as we speak :)

**Comment by XhmikosR** [comment]
I believe you are missing the point that you are certainly not helping
Windows users by sticking with bash. But anyway even with bash as long as
everything works.

**Comment by paulirish** [comment]
I'm looking at https://github.com/eslint/eslint/blob/master/Makefile.js which they run on appveyor. It appears they're just passing globs right into the mocha call.  Is that possible?

Here's some other folks potentially solving this too: [Search · win32 mocha.cmd process CI](https://github.com/search?l=JavaScript&o=desc&q=win32+mocha.cmd+process+CI&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93)

**Comment by wardpeet** [comment]
@XhmikosR you are right but first we want appveyor to work so we are sure we are green until a new pr comes in where we can go windows specific! Thanks for all the effort so far!!

@paulirish looks like the mocha.js is just some sugar on top of _mocha which does the same thing as what they are doing in there makefiles, js files.

**Comment by XhmikosR** [comment]
So, how are we going to proceed with this?

We could split some of the package.json changes so that things sort of work on Windows.

**Comment by XhmikosR** [comment]
So, there's one Windows failure for unit tests which is due to the recent changes we made to the console output.

If that is sorted unit tests will pass on node.js 5. Then we can move to smoke and smokehouse tests.

**Comment by XhmikosR** [comment]
So, now the `$__node_harmony` issue is left. https://ci.appveyor.com/project/XhmikosR/lighthouse/build/37

**Comment by XhmikosR** [comment]
@wardpeet @paulirish @brendankenny: so, I fixed all issues and tests run and pass on my Windows machine with bash. On AppVeyor they fail, but I guess it's because they use old Chrome or something. See https://ci.appveyor.com/project/XhmikosR/lighthouse/build/41

Can you sort https://github.com/GoogleChrome/lighthouse/pull/1280#issue-197411049?

After this is merged, we should really find a purely cross platform solution without the need for bash. Maybe pure node.js scripts or shelljs.

**Comment by XhmikosR** [comment]
OK, the issue with AppVeyor's failure is because it is using an older Chrome and not the one specified by the script. It seems on Windows the scripts always load Chrome from `PROGRAMFILES` folder.

**Comment by XhmikosR** [comment]
Updated for the latest package.json changes.

We still need to adapt the code so that `LIGHTHOUSE_CHROMIUM_PATH` is being used on Windows too.

**Comment by XhmikosR** [comment]
So, what are we going to do with this? I have updated my first post with the issues I face. Currently tests pass but I don't run `smoke`, `smokehouse` and build the extension.

**Comment by XhmikosR** [comment]
So we are down to 2 issues for this after #1519.

**Comment by XhmikosR** [comment]
OK, so @wardpeet @paulirish @wardpeet: this works [fine](https://ci.appveyor.com/project/XhmikosR/lighthouse) now minus the Chrome 56 tests which would work if #1472 was sorted.

Can one of you:

>Before merging: one of the project maintainers needs to add AppVeyor to the repository and paste the image link so that I add it in readme.md and rebase.

Also, make sure you enable the option to "Skip branches without appveyor.yml".

**Comment by XhmikosR** [comment]
And SUCCESS! 🕺 See https://ci.appveyor.com/project/XhmikosR/lighthouse/history

Now, we only need to merge #1572 in order to fix #1472, and then one of the maintainers needs to:

>**Before merging**: one of the project maintainers needs to add AppVeyor to the repository and paste the image link so that I add it in readme.md and rebase.

Some final notes:

1. not sure if we should cache the downloaded Chromium or not in order to match Travis CI behavior
2. tests fail with stable Chrome 56 which is something that CIs can't catch since we always use the latest Chromium

**Comment by XhmikosR** [comment]
@addyosmani: ping since you originally asked for this :)

Only the [above](https://github.com/GoogleChrome/lighthouse/pull/1280#issuecomment-275905087) comments are left for this.

**Comment by brendankenny** [comment]
with 1.5 out the door, excited to get this going!

**Comment by brendankenny** [comment]
I don't believe I have the ability to add AppVeyor with this repo, so @paulirish is going to try it out.

re:caching, we added it in Travis since it's definitely a drag to have to wait for it to be downloaded for every run of the tests, especially if you're tweaking quickly (or worse, if you're trying to debug an issue that only appears when run in the CI :).

OTOH, yeah, if we can't clear the cache that will be an issue as new Chrome versions come out.

**Comment by XhmikosR** [comment]
All right so caching Chromium disabled we really ok. Adding AppVeyor to the
report I'll wait for Paul. Just make sure you enable skip branches without
appveyor.yml.

Then the only thing left is if we should use the same script to download
Chromium or not.

Otherwise tests work fine and are passing after all the fixes I have
submitted all this time :)

**Comment by paulirish** [comment]
@XhmikosR I think this is the badge URL for ya:

```md
[![Build status](https://ci.appveyor.com/api/projects/status/3bdm5qn9r32ha5cg?svg=true)](https://ci.appveyor.com/project/paulirish/lighthouse)
```

[these were the choices](https://cloud.githubusercontent.com/assets/39191/22848753/87f31082-efab-11e6-878b-8b9ef776e82b.png), FYI.

**Comment by XhmikosR** [comment]
@paulirish: rebased and added your account's badge.

I update the badge. The AppVeyor settings look good to me. We could rename appveyor.yml to .apppveyor.yml if you prefer that.

So the only thing left is if we should use the same script to download Chromium or not for AppVeyor.

**Comment by paulirish** [comment]
This was a long effort, but it's totally worth it. So excited to have test coverage on windows, finally. :)

-----

✅  _asserted true: Awesome PR_
✅  _asserted true: Great collaboration_
✅  _asserted true: Test coverage upgrade_
✅  _asserted true: PR merged_
_4 of 4 tests pass._

**Comment by XhmikosR** [comment]
If it weren't for this I wouldn't have noticed most of the issues so far.

I hate that most devs ignore Windows when it has so big market share ;)

Now if we could sort #1691 eventually, it would make my and all Windows users lives easier. :)

**Pull request merged**
