### PR TITLE
deps: bundlesize to 0.18.0

### PR DESCRIPTION
**Pull request by paulirish**
hopefully fixing the spam in our CI output.

### CODE REVIEW

**Comment by paulirish** [comment]
didn't fix anything.

fwiw i also tried refreshing the env variable on travis but no luck either.

**Comment by paulirish** [comment]
The upstream bug: https://github.com/siddharthkp/bundlesize/issues/308

**Comment by paulirish** [comment]
Brendan points me to https://github.com/GoogleChrome/lighthouse/pull/9089  where he called out out [bundlewatch](https://bundlewatch.io) (which looks nice)

and speaking of other options.. there's also 

https://github.com/GoogleChromeLabs/travis-size-report

and https://buildtracker.dev/

**Comment by XhmikosR** [comment]
I'm also looking for alternative solutions. The aforementioned issue is present for so many months. Also, bundlesize itself is quite a big devDependency and requires native bindings due to brotli. One could just target Node.js > 10.16 or so that has brotli built in.

I'll keep an eye on bundlewatch. I've also found https://github.com/ampproject/filesize but it doesn't seem to integrate with pull requests.

**Pull request merged**
