### PR TITLE
core(dom-size): display metric values as integers

### LINKED ISSUE #14422: Too much precision on the DOM size audit
We shouldn't need the `.0`. These values will always be integers

Screen Shot 2022-10-04 at 12 46 14 PM

### PR DESCRIPTION
**Pull request by shogohida**
**Summary**

Fixes #14422 

**Related Issues/PRs**

I think this issue was caused by the changes in this [PR](https://github.com/GoogleChrome/lighthouse/pull/11563/files#diff-eea8149074228d97e9a32ada82e224c64e2176fb308133457a789c2fa44acb09R99)

### CODE REVIEW

**Comment by adamraine** [comment]
This won't actually change the value because the numbers are already integers. The problem is that the Lighthouse report displays the integers with unnecessary granularity.

To fix this, we need to change the details items from 

```js
{
  statistic: str_(UIStrings.statisticDOMElements),
  value: stats.totalBodyElements,
}
```
to

```js
{
  statistic: str_(UIStrings.statisticDOMElements),
  value: {
    type: 'numeric',
    granularity: 1,
    value: stats.totalBodyElements,
  },
}
```

**Comment by shogohida** [comment]
@adamraine 
Thanks for your comment! I will push the changes when I finish

**Comment by connorjclark** [comment]
Please confirm your changes locally via `yarn start https://www.example.com`.

**Comment by shogohida** [comment]
@connorjclark @adamraine 
I added settings of value in [this commit](https://github.com/GoogleChrome/lighthouse/pull/14479/commits/dd5d4ae77cc06c1342147b818201b19534cc4454) as Adam indicated. 

In addition, I checked there is no `.0` with the command Connor taught me.
スクリーンショット 2022-11-01 22 56 37

**Comment by adamraine** [comment]
Some of our tests are failing, to fix this you should

1. run `yarn update:sample-json` and commit the changes
2. Update the unit test expectations

https://github.com/GoogleChrome/lighthouse/blob/60c2fa25d11187802e905e4f335b2e7f6df735f1/core/test/audits/dobetterweb/dom-size-test.js#L24-L32

3. Update the smoke test expectations

https://github.com/GoogleChrome/lighthouse/blob/60c2fa25d11187802e905e4f335b2e7f6df735f1/cli/test/smokehouse/test-definitions/dobetterweb.js#L403-L417

**Comment by shogohida** [comment]
@adamraine 
Thanks for your comment! Your support always helps me.

I made changes in the commits below.
https://github.com/GoogleChrome/lighthouse/pull/14479/commits/1aa78ac511dcc2b489fa5932aabc866e0f6249d2
https://github.com/GoogleChrome/lighthouse/pull/14479/commits/e87d529179bc8dca208e42b2f1955d1749cf5923
https://github.com/GoogleChrome/lighthouse/pull/14479/commits/aabd3db19c0953342ba4d6a0019a3586dbc39050

A test case of `difference at total-blocking-time audit.numericValue` fails but it seems there is no relation between that failure and this PR.

https://github.com/GoogleChrome/lighthouse/actions/runs/3371728139/jobs/5594423467

**Review by adamraine — APPROVED** [review]
> A test case of difference at total-blocking-time audit.numericValue fails but it seems there is no relation between that failure and this PR.

You are correct, this is a common flaky failure #14271. This PR looks good, thanks for the contribution!

**Comment by shogohida** [comment]
Thanks for your quick review! I hope to contribute more 👍

**Pull request merged**
