### PR TITLE
deps: update third-party-web

### PR DESCRIPTION
**Pull request by hcodes**
**Summary**
Update `third-party-web` to [0.12.2](https://github.com/patrickhulce/third-party-web/releases/tag/v0.12.2).

**Related Issues/PRs**
https://github.com/patrickhulce/third-party-web/issues/88

### CODE REVIEW

**Comment by hcodes** [comment]
@googlebot I signed it!

**Review by adamraine — APPROVED** [review]
LGTM. Same changes are made in https://github.com/GoogleChrome/lighthouse/pull/11290 but that's still in review. Thanks for updating separately!

**Comment by hcodes** [comment]
@adamraine 
I want to merge this PR now, so as not to wait for another one. To do iterations. Time is money.

**Comment by hcodes** [comment]
Thank you all!

**Pull request merged**
