### PR TITLE
core(listitem): mention li can be contained by a menu

### PR DESCRIPTION
**Pull request by FMJansen**
**Summary**
Axe-core has been updated to allow listitems to exist inside menu elements, in accordance with the HTML spec. So, this text should be updated since axe-core has been updated to 4.4.x (https://github.com/GoogleChrome/lighthouse/commit/37a1ceb4bb365fc6df470d1cc172760ae03fffa5)

Related to https://github.com/GoogleChrome/web.dev/issues/7802 and https://github.com/GoogleChrome/web.dev/pull/7803 in the web.dev repo.

Menu spec: https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element
Menu on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu

**Related Issues/PRs**
#13926

### CODE REVIEW

**Comment by adamraine** [comment]
You will need to run `yarn update:sample-json` and commit the changes since this modifies one of our translated UI strings.

**Comment by FMJansen** [comment]
Ah, got it, missed that before!

**Comment by connorjclark** [comment]
This is our fault, but we have a newly extra step to deal with too: `yarn update:flow-sample-json`

@adamraine wdyt of having `yarn update:sample-json` just do both? I always forget too.

**Comment by FMJansen** [comment]
At least the error said it, too, haha, done! :D

**Comment by adamraine** [comment]
> @adamraine wdyt of having yarn update:sample-json just do both? I always forget too.

SGTM

**Comment by FMJansen** [comment]
I see some tests are failing but this is a little over my head, do I need to fix something on my end?

**Comment by connorjclark** [comment]
You won't believe it but... we also have to run `yarn update:test-devtools` to update some other tests. I'll take care of it from here, though, just a minute.

**Comment by FMJansen** [comment]
Haha I found that command in one of the failed test messages, but when I ran it nothing changed so I was already confused. Thanks for picking it up :)

**Review by connorjclark — APPROVED** [review]
Thanks!

**Pull request merged**
