### PR TITLE
core(seo): support japanese in link-text audit

### PR DESCRIPTION
**Pull request by rdlabo**
**Summary**
lint link-text is great!! I think that it will more wonderful if it supports multiple languages.

I added Japanese easily. But I think this should be separate file, and that various people should be involved in editing.
Please let the opinion. 

thanks.

### CODE REVIEW

**Comment by rdlabo** [comment]
signed it!

sakakibara@rdlabo.jp
https://github.com/rdlabo

 HTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTH

Ionicで作る モバイルアプリ制作入門〈Web/iPhone/Android対応〉
好評発売中 http://amzn.to/2IainNW

WordPressを使ってアプリをつくるためのOSS Ionic-WP.com
http://ionic-wp.com/ （デモ：https://demo.ionic-wp.com）

女友だちをつくる女性専用ソーシャルサービス tipsys
http://tipsys.me/ （Web版 / iOS版）

------------------------------------------------

一般社団法人リレーションデザイン研究所 代表理事

榊原昌彦 - Masahiko Sakakibara
        e-mail sakakibara@rdlabo.jp / twitter rdlabo

------------------------------------------------

一般社団法人エリア・イノベーション・アライアンス CTO
特定非営利活動法人場とつながりの研究センター 研究員

 HTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTH

2018-05-24 2:40 GMT+09:00 googlebot <notifications@github.com>:

**Comment by paulirish** [comment]
cc @agektmr do these look good to you?  If so, any links with these phrases _should_ be improved to have more context.  (e.g. 'Click here' => 'Understand our pricing')

**Comment by rdlabo** [comment]
@paulirish  I changed that lang file move config folder. please check.

**Comment by agektmr** [comment]
I'm not an expert on this field, but not sure if "全文表示" (display all), "続きを読む" (continue reading) and "もっと読む" (read more) are kind of link text to be avoided. It seems a lot of publishers use these link text on their CMS template. If they would have to replace them with concrete text, could be a challenge.

Is there any criteria for English blocklist? I think same thing goes to "learn more" for example.

**Comment by rdlabo** [comment]
@agektmr thanks for review.

The site that reached 100 point in item of PWA is too minority now.  But I think this make web more valuable. ( and get 100 point is very easy more than the Performance )
I want item of SEO will make web more valuable.

**Comment by brendankenny** [comment]
I missed @paulirish's 👍

**Pull request merged**
