### PR TITLE
Report: fix rendering issues in FF. Fixes #1124

### LINKED ISSUE #1124: Report: FF rendering issues
Lots of cleanup to do in FF.

- The Beta banner is gone
- the check/x's are gone in FF. That's probably because we're using some `-webkit-mask-image` action. They should really just be background images with `background-size: contain`.
- The help toggles are checkboxes instead of images

screen shot 2016-12-08 at 10 37 46 am

### PR DESCRIPTION
**Pull request by ebidel**
R: all

This is an alternative to https://github.com/GoogleChrome/lighthouse/pull/1489.

The benefit is that it keeps the SVG unencoded (easier to maintain later) and also fixes the checkboxes in firefox. Didn't touch the Beta banner for FF. Probably not worth it.

screen shot 2017-01-26 at 7 30 29 pm

### CODE REVIEW

**Comment by Janpot** [comment]
the beta banner seems still missing in your screenshot.

**Comment by XhmikosR** [comment]
What @Janpot said plus the toggle help button looks bad using FF 52b1.

1498alt

Other than those 2, much cleaner solution, agreed 👍

**Comment by ebidel** [comment]
I should have mentioned, I didn't touch the Beta banner for FF. Didn't think it's worth the trouble.

My screenshot is from FF54. It looks like they've fixed the behavior of `-moz-appearance` for checkboxes in later versions of FF.

**Comment by XhmikosR** [comment]
All right, then I guess it makes sense to merge this but it will land on beta in like 2 months at best.

I'd still URL encode the banner though unless you plan to remove it soon :).

**Comment by ebidel** [comment]
We've talked about that :)

**Comment by XhmikosR** [comment]
All right, closing my PR then, and thanks for this!

**Comment by ebidel** [comment]
Update: 

This is also rocking blue "?" icons now and black headings, as per @paulirish's css changes for devtools.

screen shot 2017-01-27 at 3 40 58 pm

**Pull request merged**
