### PR TITLE
Fix: Replace npm with yarn on travis

### PR DESCRIPTION
**Pull request by stramel**
Hoping this addresses #2048  Not too familiar with Yarn. Did get passing tests on travis though.

### CODE REVIEW

**Comment by stramel** [comment]
Hmm, not sure why that test failed. Didn't fail when it ran for my fork's travis job. Perhaps the caching is causing the test to be flaky? /shrug

**Comment by brendankenny** [comment]
looks like it was our perpetually flakey test. Did a rerun and green now :)

**Comment by wardpeet** [comment]
Ok for me, I believe everyone is using it locally anyway.

**Comment by paulirish** [comment]
@stramel thanks so much! appreciate this.

**Pull request merged**
