### PR TITLE
core(trace-processing): add backport for pubads

### PR DESCRIPTION
**Pull request by adamraine**
Looks like https://github.com/GoogleChrome/lighthouse/pull/14693 broke pubads which was causing the errors in our e2e tests. This is a hacky workaround to fix pubads on main.

Our smokes didn't catch this because we don't check any pubads audits that use trace processing.

We could also just revert #14693, doesn't seem super important.

### CODE REVIEW

**Comment by brendankenny** [comment]
Good call on getting it into smoke tests. Can we update pubads? We are still (in theory - #14375) going to get an official release there)

**Comment by adamraine** [comment]
I guess we could, pubads is already using a dev version of lighthouse:
https://github.com/googleads/publisher-ads-lighthouse-plugin/blob/f05bf852f0e9e772a14ab408d55b0852672daac6/package.json#L25

**Comment by adamraine** [comment]
So there are a lot of changes we would need to make for pubads to work with the latest dev release of LH. I would prefer to keep the backport and do those changes when 10.0 is released officially.

**Comment by connorjclark** [comment]
Are we to ask them to do an official release where the pinned version for the LH dep is one of our nightlies?

**Comment by brendankenny** [comment]
> I would prefer to keep the backport and do those changes when 10.0 is released officially.

That seems fine, maybe just add a note to #14375 to get rid of the workaround?

This probably warrants a discussion about testing for plugin compatibility when we're explicitly working on a major version release with breaking changes. For 11.0, for instance, should we just disable the pubads tests and reenable when there's a release supporting 11? Downside is we wouldn't catch _unexpected_ regressions, but I'm not sure how likely that is given that we should have pretty good coverage for the artifacts they need, etc.

**Review by connorjclark — APPROVED** [review]

**Pull request merged**
