### PR TITLE
estimated input latency audit

### LINKED ISSUE #28: metric: Thread availability
Capturing how available the main thread is. This is a proxy metric to for potential input latency, as we cannot predict when input will hit the browser.

------------------------------------
_Update_: See details at `Timestamp: Main thread ready for interaction` in #27
--------------------------------------------

##### Scoring

S-curve handled by Ben's math. Basic expectations:

* Goal: 90% percentile main thread task duration ~ under 300ms
* Goal: Maximum main thread task duration is < 400ms
* 100/100 is 90% percentile figure is <12ms
* 0/100 is 90% percentile figure is <1000ms.
* TBD: Determine curve.

### PR DESCRIPTION
**Pull request by paulirish**
Mostly by brendan (#426), but I rebased it.

aka thread availability, Risk to Responsiveness, expected task queueing time, etc. Fixes #28

screen shot 2016-06-14 at 01 03 15

> still a few things to take care of, like making scoring work and it needs to get in shape to also be useable for measuring TTI.

### CODE REVIEW

**Comment by paulirish** [comment]
From lewis:

> This looks great overall. I think we need a meta bug for the UI, though, because we need to make sure it's (eventually) understandable by as many folks as possible.

Presentation notes from lewis/irish discussion:

> Let's score on 90th percentile.
> Highlight 90th percentile.
> "You have a 9 in 10 chance of input latency being XXX or shorter."

**Comment by paulirish** [comment]
We also have to remove the clipping of the ends.

**Comment by paulirish** [comment]
* Value : 90th percentile
* Report extendedInfo: "90% probability of input latency at XXXms or shorter. (50%: XXms, 75%: XXms, 90%: XXms, 99%: XXms)"

**Comment by brendankenny** [comment]
updated.

clarifying questions: 
should the phrase be something like `90% probability of input latency at XXXms or shorter after first paint` or something? I don't want to confuse it with FMP or FCP, but that seems important

should we still add the 16ms for ideal input response latency by the system itself, as [catapult does](https://github.com/catapult-project/catapult/blob/f7df8568ae1f63ee17f08a73b49261afe9f7ea8c/tracing/tracing/metrics/system_health/hazard_metric.html#L45-L46)? That's going to shift everything so even the 0th percentile will be a minimum of 16ms, but it's also (probably) a more realistic estimate of input response latency

**Comment by paulirish** [comment]
> should the phrase be something like 90% probability of input latency at XXXms or shorter after first paint or something? I don't want to confuse it with FMP or FCP, but that distinction seems important

TBH we're undercommunicating until we have a glossary for each of these where we can link to real documetnation. so i'm ambivalent. glossary we'll add this week.

> should we still add the 16ms for ideal input response latency by the system itself, as catapult does? That's going to shift everything, so even the 0th percentile will be a minimum of 16ms, but it's also (probably) a more realistic estimate of input response latency

Yes + 16 on the values for sure.

**Comment by brendankenny** [comment]
everything shifted by 16ms and tests added to handle some of the corner cases that come up in traces (like 0ms-long tasks)

**Comment by brendankenny** [comment]
should be good to go

**Pull request merged**
