### PR TITLE
Update extension and core report to use new logo / styling

### PR DESCRIPTION
**Pull request by ebidel**
R: all

screen shot 2016-12-11 at 4 19 36 pm
screen shot 2016-12-11 at 10 25 38 am
screen shot 2016-12-11 at 10 25 43 am

### CODE REVIEW

**Comment by paulirish** [comment]
what if we used the lighthouse searchlight animation for our spinner?   😺

**Comment by ebidel** [comment]
On a related note, I wanted to use the md spinner (https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html&active=paper-spinner) but most implementations I found jank when we're testing b/c their CPU bound. The polymer one is completely GPU, but it's too heavy weight to justify bringing it in.

**Comment by paulirish** [comment]
hows this look for extension icon?

image

 I'll add the asset in here

**Comment by ebidel** [comment]
Or how about super simple box:

screen shot 2016-12-11 at 4 46 43 pm

The will be a nice favicon too.

**Comment by brendankenny** [comment]
I feel like the round one is kind of weird when cropped like that. Maybe if it were moved down relative to the lighthouse? Definitely like how the lighthouse bottom isn't visible vs how it is in the box one

**Comment by brendankenny** [comment]
that would be I feel like the round *background* is kind of weird when cropped as in @paulirish's suggestion

**Comment by paulirish** [comment]
k. +1 to eric's latest but move the lighthouse down to give it some blue breathing room at the top.

**Comment by ebidel** [comment]
Grass is nice.

screen shot 2016-12-11 at 5 05 50 pm

**Comment by paulirish** [comment]
the new spinner is a little nasty on my screen. :/



what if we used the lighthouse searchlight animation for our spinner? 😺😺

**Comment by ebidel** [comment]
Ayight. Awesome sauce now:

screen shot 2016-12-12 at 7 35 11 pm

**Pull request merged**
