### PR TITLE
speedline to 1.0.1

### PR DESCRIPTION
**Pull request by paulirish**
This includes a major refactor to speedline: https://github.com/pmdartus/speedline/pull/30

The big improvement is that traces with 1, 2, or 3 screenshots will now provide a reliable speed index number, whereas before we'd often end up with a `-1` result on sites like airhorner and example.com

### CODE REVIEW

**Comment by paulirish** [comment]
Ah interesting. The test failure is because the speed index of our fixture trace has changed:
image


Consider this PR chillin ❄️  while I investigate if this is expected.

**Comment by paulirish** [comment]
All set.

⚠️  Warning though: **Speed Index results will be changing with this update**. Generally, I expect >3 frame traces to have a slightly lower SI than before, and <= 3 frame traces to work and not return `-1`s.

This is due to a few bugs fixed in the SI calculation:

* **Fixed various definitions of `beginning`/time origin**. In a few places, speedline used the first frame's timestamp as if that were the time origin. Now the first event's timestamp is used as the time origin all the way through. 
* **Speed Index definition updated.** It's now (as of 1.0.1), as Parvez [described here](https://github.com/pmdartus/speedline/issues/28#issuecomment-244127192), `SI = firstPaint + sum(fP to VC){1-VC%}`. In reality this mostly sorts out <= 3 frame traces.

**Comment by brendankenny** [comment]
do we want to wait for 1.0.2 and https://github.com/pmdartus/speedline/pull/33?

**Comment by brendankenny** [comment]
would a one frame test be helpful?

**Comment by brendankenny** [comment]
> would a one frame test be helpful?

just told that speedline itself has this test :)

**Comment by paulirish** [comment]
> do we want to wait for 1.0.2 and pmdartus/speedline#33?

Yup. That's a neccessary dependency. (Currently this PR does indeed depend on it :)  But as soon as it lands, we'll bump over there and I'll adjust here.

And yeah... speedline now has tests for various 1,2,3 frame scenarios. woo.

**Pull request merged**
