### PR TITLE
Adds more a11y audits

### PR DESCRIPTION
**Pull request by paullewis**
FYI @robdodson

### CODE REVIEW

**Comment by robdodson** [comment]
\o/

**Comment by paulirish** [comment]
That was fast. Nice!

**Comment by paulirish** [comment]
for the curious, Audits added in this PR

```
'Element aria-* roles are valid';
'Background and foreground colors have a sufficient contrast ratio';
'Every image element has an alt attribute';
'Every form element has a label';
'No element has a tabindex attribute greater than 0';
```

**Comment by paulirish** [comment]
This is looking very nice.

**Pull request merged**
