### PR TITLE
core(legacy-javascript): drop parseInt, Array.prototype.reduce,reduceRight signals

### PR DESCRIPTION
**Pull request by zloirock**
Because of [this V8 bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1049982), `core-js` polyfill `Array.prototype.{ reduce, reduceRight }` in Chrome 80-82 -> with `esmodules` target - too. [See `core-js-compat` data](https://github.com/zloirock/core-js/blob/361b0b4b264df59beb3a481023fd4635b98bd3c7/packages/core-js-compat/src/data.mjs#L227-L242).

---

Update: Also, `Number.parseInt` should be polyfilled in Chakra-based Edge.

---

Too many polyfills should be added to this list, but I'm not very familiar with the Lighthouse architecture, so I'll just create an issue about it. See #13440.

### CODE REVIEW

**Comment by connorjclark** [comment]
Ah, that's a shame. Good catch. Thanks!

> Update: Also, Number.parseInt should be polyfilled in Chakra-based Edge.

Does that refer to this part of the compat data?

https://github.com/zloirock/core-js/blob/361b0b4b264df59beb3a481023fd4635b98bd3c7/packages/core-js-compat/src/data.mjs#L824

**Comment by connorjclark** [comment]
Could you also include these changes? 
image

**Comment by zloirock** [comment]
> Does that refer to this part of the compat data?

Yes, sure.

**Comment by connorjclark** [comment]
continuing here #13482

**Pull request closed without merging**
