### PR TITLE
 core(config): move unused-javascript to default config

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
putting DZL through it's paces to see how much of an impact unused-javascript has. maybe it can finally see the light of day! :D

### CODE REVIEW

**Comment by patrickhulce** [comment]
DZL, do a barrel roll!

**Comment by patrickhulce** [comment]
DZL is done! Go check it out http://lh-dzl-6728.surge.sh

**Comment by patrickhulce** [comment]
DZL is done! Go check it out http://lh-dzl-6728.surge.sh

**Comment by exterkamp** [comment]
I like new audits, but will this flair up some old debates without 3rd party filtering if we make it super visible...e.g.

image

**Comment by brendankenny** [comment]
@patrickhulce what was the verdict? Or do we not care either way for now (just a DZL test) and we can think about it another day?

**Comment by patrickhulce** [comment]
> what was the verdict? 

The verdict was that there was no difference, but my confidence in DZL to conclude that is pretty low. I'm fine closing and re-opening once we finish our variance efforts.

**Pull request closed without merging**
