### PR TITLE
misc(git3po): land-when-green

### PR DESCRIPTION
**Pull request by connorjclark**

### CODE REVIEW

**Comment by paulirish** [comment]
this is gonna work? neat.

**Comment by connorjclark** [comment]
yeah I added the necessary functionality to git3po and tested it on a test repo.

**Comment by paulirish** [comment]
i get an error: `Fatal error: RangeError: Invalid time value`

image

confirmed that i have the latest git3po (1.7.0) installed.

**Comment by patrickhulce** [comment]
you're missing `started-at` for that invocation @paulirish, no? we should have a better error message for it though :)

**Comment by connorjclark** [comment]
I omitted the start at because you'll be providing one in the cli.

**Pull request merged**
