### PR TITLE
Tag and ship Lighthouse 2.0

### PR DESCRIPTION
**Pull request by paulirish**
Eric and Brendan are doing their right _right now_. So how about we do it.
we do it live.  :D 

WDYT??!?!?

### CODE REVIEW

**Comment by paulirish** [comment]
image

image


about to do it.....

**Comment by paulirish** [comment]
it's done.

image

We shipped!


🛥 🛥 🛥 🛥 🛥 🛥  🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by patrickhulce** [comment]
image

**Comment by paulirish** [comment]
Somehow I need to communicate this to @ebidel and @brendankenny 

image

**Comment by pedro93** [comment]
Wave like crazy :+1:

**Comment by ebidel** [comment]
Lolllll

**Pull request merged**
