### PR TITLE
deps: axe-core@3.2.2

### LINKED ISSUE #7355: 0 Accessebility
https://www.deque.com/axe/ does not open. This site can’t be reached

#### Provide the steps to reproduce
1. Run LH on https://www.homeyou.com/

#### What is the current behavior?
0 Accessibility, even on such points that when checked manually are present.

#### What is the expected behavior?
At least 1 point.

errorr

### LINKED ISSUE #7496: Upgrade axe to 3.2.0
https://github.com/dequelabs/axe-core/releases/tag/v3.2.0 

It was shipped last week. It has 3 performance improvements I'm really excited about.

cc @robdodson @marcysutton

### PR DESCRIPTION
**Pull request by paulirish**
has two perf boosts: https://github.com/dequelabs/axe-core/releases/tag/v3.2.0

3.2.0 introduced rules [`aria-hidden-focus`](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus) and [`form-field-multiple-labels`](https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels) which are tagged wcag2a (which means we'll run them now).

The hidden-focus rule scares me a bit, implementation-wise, so I'm hesitant to include that in our results. The multiple-labels rule looks straightfoward.

@robdodson @marcysutton do yall have feelings on this?

fixes #7496
fixes #7355

### CODE REVIEW

**Comment by marcysutton** [comment]
Hey @paulirish! I don't work at Deque anymore, but I'm sure @wilcofiers and @dylanb would love to know what reservations you have about the `hidden-focus` rule.

**Comment by robdodson** [comment]
I think if we're unsure about the aria-hidden-focus rule we could disable it:
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/accessibility.js#L40

**Comment by patrickhulce** [comment]
Shouldn't we disable all the rules we don't have audits for anyhow? :) 

Yay for perf fixes!!! 🎉

**Comment by robdodson** [comment]
@patrickhulce good point :)

**Comment by paulirish** [comment]
> Hey @paulirish! I don't work at Deque anymore

oh shoot! i totally knew and forgot that. my bad!

dylan/wilco: mostly reservations as we're in a sprint towards tagging a new major version and i am scared of adding new audits to put in front of users that we haven't spent time with. After Google I/O we'll have more breathing room to evaluate these. ;)


> Shouldn't we disable all the rules we don't have audits for anyhow? :)

for sure. brendan did the research into this back in https://github.com/GoogleChrome/lighthouse/issues/7127

Here's what I'm thinking:

1. we land this version bump with these 2 new axe rules disabled
2. i immediately followup this with another PR to disable the 5 rules brendan found. 
3. I add these two axe rules to that #7127 and after I/O we'll decide if we'll surface them to LH users.

**Comment by ConradSollitt** [comment]
I found this from issue https://github.com/GoogleChrome/lighthouse/issues/8435 after finding a hidden label with correct `for="id"` was not working on a site I created that uses a label with placeholder on a filter input:

https://awesome-web-react.js.org/

Seems that hidden associated labels are still showing as not linked in Lighthouse.

Posting the work around below in case someone else comes across the issue. Also, I added a similar comment on the issue.

```css
/* Original version: */
label { display: none; }

/* Fix to pass Lighthouse: */
label { position: absolute; top:-1000px; left:-1000px; }
```

**Pull request merged**
