### PR TITLE
misc: rename 'lighthouse-' folders

### PR DESCRIPTION
**Pull request by connorjclark**
```
git mv lighthouse-core core
git mv lighthouse-cli cli
git mv lighthouse-viewer viewer
git mv lighthouse-treemap treemap
git mv lighthouse-logger logger
```

* global find/replace for lighthouse-core -> core, etc. (except for lighthouse-logger)
* don't change `lighthouse-viewer` in `firebase-auth.js` (api credentials)
* manual fixing of .md files (some links are pointing to particular commits)
* ignored changelog.md

This is a huge change, but since the only manual aspect of it was the *.md files you can see a smaller diff via `git diff origin/master origin/great-move -- '*.md'`. Our extensive tests should give us confidence to make this change.

It just occurred to me that changing the location of `(lighthouse-)core/config/lr-desktop-config.js` used for `--config-path` may break someone. Should we do a fallback config lookup in `bin.js` if `.../core/config/...` doesn't match anything (try `.../lighthouse-core/config/...`)? And possibly drop that next major version.

### CODE REVIEW

**Comment by brendankenny** [comment]
I applaud the Herculean effort but this might need to be a breaking change :/

We haven't always done the best job exposing the API end points folks need, so e.g. just a cursory search of pubads there's a bunch of places they reach into `lighthouse-core/` and a few to `lighthouse-cli/`.

Viewer and treemap might be workable, though?

**Comment by connorjclark** [comment]
> We haven't always done the best job exposing the API end points folks need, so e.g. just a cursory search of pubads there's a bunch of places they reach into lighthouse-core/ and a few to lighthouse-cli/.

Obvious in hindsight, but strangely I can't get this error to happen locally with `yarn build-devtools`, so I'm stuck debugging a solution in GHA. I'd bet that _only_ pubads is using anything beyond `require('lighthouse')`, and so we have the possibility of just fixing it ourselves without breaking any existing plugins. Just a hunch, I'll take a look at existing plugins.

**Comment by brendankenny** [comment]
It's not just pubAds, lighthouse-ci does too. I'm sure most integrations do.

**Comment by patrickhulce** [comment]
+1 to this being a breaking change.

While Lighthouse CI does indeed do this, we're pinned to a very specific Lighthouse version such that we could probably handle it OK. My greater concern is that *anyone* using the report renderer would be in the same position and probably didn't peg to a single version.

**Comment by connorjclark** [comment]
See y'all here in a few months :)

**Pull request closed without merging**
