### PR TITLE
tests: test fewer things in appveyor

### PR DESCRIPTION
**Pull request by connorjclark**
We really just want to keep this to verify Windows development probably works.

### CODE REVIEW

**Comment by connorjclark** [comment]
hm... twice in a row the smoke lantern failed ...

https://github.com/GoogleChrome/lighthouse/runs/824199701?check_suite_focus=true
https://github.com/GoogleChrome/lighthouse/pull/11017/checks?check_run_id=824199701

**Comment by brendankenny** [comment]
Is cutting out everything important to land? I thought we talked about moving Windows testing to Github Actions. Meanwhile Appveyor is non-blocking, whether passing, failing, or in progress.

I'd at least like to see some smoke tests kept, since running on Windows is actually pretty important :)

**Comment by patrickhulce** [comment]
+1 to the idea of removing this in a PR that adds windows github actions :) 

as for the lantern failure, it looks like we can move on before we hit all 40 iterations in the new rIC shim test, happens about 1/20 of the time locally. I'll open PR to fix that.

**Comment by connorjclark** [comment]
> +1 to the idea of removing this in a PR that adds windows github actions :)

Let's open this up when GH actions is running windows. And decide to either land as-is (pared down tests) or remove completely.

**Pull request closed without merging**
