### PR TITLE
remove aggregations

### PR DESCRIPTION
**Pull request by brendankenny**
part of #2276

it is time to say goodbye :)

### CODE REVIEW

**Comment by brendankenny** [comment]
the diff on `runner-test.js` looks like more is changing than actually is.

[`?w=1`](https://github.com/GoogleChrome/lighthouse/pull/2426/files?w=1#diff-9476be2df7d812bc50da0dd73d73f2f8) makes it clearer that it's just one test being removed and one test switching from a config with an aggregation to one with a category

**Comment by paulirish** [comment]
ya got some conflicts now :)

**Comment by brendankenny** [comment]
all ✅ and travis says 💚 so farewell aggregations

**Comment by brendankenny** [comment]
(note: aggregations died on the way back to their home planet)

**Comment by paulirish** [comment]
best best.

**Comment by stramel** [comment]
6k deletions 😂😂😂

**Pull request merged**
