### PR TITLE
core: remove no-websql audit

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
This audit is relevant to only 0.6% of sites on HTTPArchive (only 8k out of ~1.3M) . The `websql` gatherer takes at least 500ms for every site that *passes* the audit, so we're spending 1,200,000 seconds a month just on WPT doing nothing :)

My claim is that this audit would not pass our `new-audit` criteria doc if we were to validate it today and should be removed.

**Related Issues**
thought of while investigating #6272 

<details>

<summary>
See Query
</summary>

```sql
SELECT
  JSON_EXTRACT_SCALAR(report, '$.audits.no-websql.score') as score, COUNT(*)
FROM
  httparchive.lighthouse.2018_09_01_mobile
 GROUP BY score
```
</details>

### CODE REVIEW

**Comment by brendankenny** [comment]
screen shot 2018-10-16 at 10 18 43

someone playing around this this?

**Comment by brendankenny** [comment]
oh, maybe it's new actions or whatever

**Comment by patrickhulce** [comment]
> Need to also delete WebSQL in artifacts.d.ts

@brendankenny do you have a way for force vscode show the .d.ts files and have them in find/replace

```
        "**/*.d.ts": {
            "when": "$(basename).ts"
        }
```

hasn't been doing the trick clearly :)

**Comment by brendankenny** [comment]
oh, no, and I hadn't even noticed that was a problem...

I was thinking that maybe we need to reverse `artifacts.d.ts` and have it pull the artifact types off of the gatherers that produce them (which would have flagged the change in this case), but I believe our earlier reasoning was that by having the source of truth in that file, bugs in gatherers would be more easily caught, which still seems sound...

**Pull request merged**
