### PR TITLE
Windows: Look into `LIGHTHOUSE_CHROMIUM_PATH` variable too.

### LINKED ISSUE #1472: Windows: Use `LIGHTHOUSE_CHROMIUM_PATH` if set
Currently, Chrome is always being loaded from the Program Files folder regardless of `LIGHTHOUSE_CHROMIUM_PATH` value.

Noticed this while working on #1280

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #1472.

### CODE REVIEW

**Comment by paulirish** [comment]
sg. shall we add it for Mac too just so it's straightforward to reason about?

if this is set, then we should definitely use it rather than any sniffed location.

**Comment by XhmikosR** [comment]
I guess it makes sense to take into consideration the variable. Although it should be documented somewhere.

I need this for #1280 and noticed that only on Linux the env var us taken into consideration.

**Comment by brendankenny** [comment]
+1 for mac support and having it override any other choice (unless you use `--select-chrome` in addition to setting the variable).

win32 will need the `priorities` treatment that the other platforms get, and mac will need to set `process.env.LIGHTHOUSE_CHROMIUM_PATH` as highest priority in the same way linux does

**Comment by XhmikosR** [comment]
@brendankenny: what does that mean? That this won't be merged currently?

**Pull request merged**
