### PR TITLE
fix: remove `paintNonDefaultBackgroundColor` from user timings

### LINKED ISSUE #934: User timing marks showing "paintNonDefaultBackgroundColor"
Looks like Chrome has a [new mark](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/paint/ViewPainter.cpp?type=cs&q=paintNonDefaultBackgroundColor&sq=package:chromium&l=172) it puts in the timeline. `paintNonDefaultBackgroundColor`:

screen shot 2016-11-12 at 12 33 10 pm

What is it and will there be more? We should differentiate though. It'll be confusing if we lump the user's marks together with defaults recorded by Chrome.

### PR DESCRIPTION
**Pull request by patrickhulce**
Don't show paintNonDefaultBackgroundColor with user timings

Fixes #934

### CODE REVIEW

**Comment by ebidel** [comment]
It might be nice keep browser-created marks. Is there a way we can differentiate/style them differently than user-created ones? I think Chrome is working on adding a few more of these metrics and it would be useful for LH to preserve showing them.

**Comment by patrickhulce** [comment]
sure but shouldn't we break them out of user-timings regardless? smells like a new audit to me

**Comment by ebidel** [comment]
It might depend on what the plan is for these new metrics. If they're marks
that will eventually surface in  the timeline, we may want to keep them. If
they will always be an internal thing, then we should probably ditch them.

CC @paulirish

**Comment by paulirish** [comment]
ya agree it shouldn't be in our report for user timings.  surfacing them elsewhere seems good but i'd rather be deliberate about that.

**Pull request merged**
