### PR TITLE
core(fr): timespan/snapshot specific audit groups

### LINKED ISSUE #12828: Change performance group based on FR mode
https://github.com/GoogleChrome/lighthouse/pull/12814#discussion_r676961397

We need a way to change and audits group based on the FR mode to progress with 
#12814. Specifically, it would be nice to relegate opportunities to the diagnostic group if they can't report any savings.

One option is to use the config to decide the audit group for different modes.

Another option I've been thinking about, optionally return `overrideGroup` in the audit to dynamically change the group.

### PR DESCRIPTION
**Pull request by adamraine**
Closes #12828

Pretty simple solution, just requires `gatherMode` to be added to LHR. I imagine we would need to do that at some point anyway.

Another option would be to modify the group on the LHR before emitting.

### CODE REVIEW

**Comment by patrickhulce** [comment]
Nice! We'll definitely want gatherMode accessible *somewhere* on the LHR for the imminent flow report work so that's 👍 

I kinda prefer your previous proposal of

> Another option I've been thinking about, optionally return overrideGroup in the audit to dynamically change the group.

But did you run into a new case where this is necessary? If it's still opportunities only, I think this might be solved naturally by moving away from the hard line distinction.

**Comment by adamraine** [comment]
> But did you run into a new case where this is necessary?

No, it's pretty much just demoting opportunities into the diagnostics group.

> I think this might be solved naturally by moving away from the hard line distinction.

Are you referring to removing the `load-opportunities` and `diagnostics` groups?

**Comment by brendankenny** [comment]
Groups have been a purely config->report display/organization tool except the single case (AFAIK) where we require opportunities to have `opportunity` audit details. My proposal in https://github.com/GoogleChrome/lighthouse/issues/12828#issuecomment-887069310 was that we get rid of that case, so they really are only a display option set in the config (and `performance-category-renderer`'s special behavior relies only on the audit details).

I'm not sure going the other way (letting individual audits decide if they want to override what's in the config) is worth the complexity, e.g. what if the config being used doesn't have a definition for the `timespanGroup` or `snapshotGroup` desired? What if the config is putting the audit in a different group than normal on purpose (e.g. it's a perf audit but they want it in their plugin category as well?) etc.

But maybe more examples where we need this would make it clearer the tradeoff is worth it?

**Comment by patrickhulce** [comment]
> Are you referring to removing the load-opportunities and diagnostics groups?

Correct, in our recent opportunities discussions with jiwoong there are not two separate groups and the type of details determines how to display the impact. I was asking mostly to see if we're still OK with tabling this for the time being.

The points @brendankenny raises are good reasons to avoid the programmatic option I highlighted, so that's out 👍

**Comment by adamraine** [comment]
> I was asking mostly to see if we're still OK with tabling this for the time being

Yeah, sounds good

**Pull request closed without merging**
