### PR TITLE
docs: remove dated domhtml reference from README.md

### LINKED ISSUE #4899: Reference to 'domhtml' in README.md
The README.md still mentions 'domhtml' but as far as I can tell that has been removed (#4176).

### PR DESCRIPTION
**Pull request by nourikhalass**
Fixes #4899 

Co-authored-by: Michiel van Spaendonck <mvanspaendonck@users.noreply.github.com>

### CODE REVIEW

**Comment by nourikhalass** [comment]
I signed it!

**Comment by nourikhalass** [comment]
Should @mvanspaendonck make a reply here that he consents or does he have to sign the CLA (which I believe he already did) and type some magic words?

**Comment by patrickhulce** [comment]
thanks very much for the contribution @nourikhalass! @mvanspaendonck a quick "fine with me" comment here should suffice :)

**Comment by mvanspaendonck** [comment]
I had idd already signed it, but I hope this "fine with me" makers it even more official :). Thanks and a happy Easter btw!

**Comment by patrickhulce** [comment]
thanks @mvanspaendonck happy easter! 🐰 🥚 🌈 🌤

**Pull request merged**
