### PR TITLE
report: redirect gauge focus so highlighter is not outlined

### LINKED ISSUE #9167: Dual focus b/wn sticky header score gauge + highlighter
image

From: https://bugs.chromium.org/p/chromium/issues/detail?id=972504#c1

### PR DESCRIPTION
**Pull request by Hoten**
Fixes #9167

### CODE REVIEW

**Comment by Hoten** [comment]
Rats ... thoughts on introducing a polyfill for that? We currently have this issue on each expandable audit too btw. Maybe we should just use a polyfill until browsers catch up.

**Comment by wardpeet** [comment]
click-focus
Are we talking about this flash of focus? I don't think it's worth adding a polyfill for it. If we feel strongly about it we could go for https://bundlephobia.com/result?p=focus-visible@4.1.5

**Comment by patrickhulce** [comment]
Well I first noticed it when I clicked but my mouse slipped and it stayed up permanently.

image

I'd be 100% on board if we could make it match our gauge :) 
thoughts on `box-shadow` + `border-radius` instead of `outline`?
image

**Comment by wardpeet** [comment]
Oh yeah I could reproduce, the box shadow looks really nice 😍

**Comment by Hoten** [comment]
<3

**Comment by brendankenny** [comment]
As a general rule, we should really only be messing with browser-focus rendering if we have to (and only after consulting with someone with knowledge about potential impact).

If we want to add a cool glow from the scroll handler that could be separate from the thing that tells you which navigation element is currently focused.

**Comment by Hoten** [comment]
> As a general rule, we should really only be messing with browser-focus rendering if we have to (and only after consulting with someone with knowledge about potential impact).

Can you share resources on this? I don't understand how these changes could be problematic.

**Comment by brendankenny** [comment]
> Can you share resources on this? I don't understand how these changes could be problematic.

Any time we change accessibility defaults we run the risk of breaking someone's workflow (though we don't necessarily break anything, of course).

e.g. in this case we get the outline even on mouse click (downside of overriding the focus ring, talked about in https://www.oreilly.com/ideas/proposing-css-input-modality), and the color difference between the ring and the gauges might not have a contrast sufficient to indicate that something is focused.

We have several people we can talk to to get the report looking like we want it to while being sure we aren't breaking things for anyone.

**Pull request closed without merging**
