### PR TITLE
core(unminified-javascript): replace esprima with custom tokenizer

### LINKED ISSUE #5723: Minified JS overestimates savings when esprima fails
#### Provide the steps to reproduce
When running lighthouse tests against our AMP pages we noticed that one of the js scripts shows up on the report as not being minified. The issue is on this file: https://cdn.ampproject.org/v0/amp-date-picker-0.1.js
This is because that file contains a copyright noticed that is hard coded into the minified javascript file, which contains carriage returns and whitespace.
I opened an issue in the AMPHTML repository asking if they could minify the copyright notice, but they said that they cannot change it and that the problem lies with Lighthouse being too picky.

For more information this is the issue I opened in the AMPHTML repository: [Issue 17077](https://github.com/ampproject/amphtml/issues/17077)

#### Environment Information
* Affected Channels: CLI, Node, Extension, DevTools
* Lighthouse version: 3.0.1
* Operating System: All
screen shot 2018-07-25 at 11 26 51

### PR DESCRIPTION
**Pull request by patrickhulce**
**Summary**
Removes dependency on esprima for JS minification savings and replaces it with a custom scanner/token counter similar to our CSS one. Putting this up for discussion before hardening it and going down the edge case rabbit hole.

**Pros**
- Faster than esprima (down to ~750ms from multiple seconds)
- Removes another bundle dependency
- We control our own destiny with bug fixes, etc

**Cons**
- We maintain a pseudo-JS parser
- Not nearly as well tested (though given the problems we've encountered with esprima I'm not super confident anyway)

Anecdotal testing I've done so far is run on a couple sites and make sure the % savings are the same for each file.

**Related Issues/PRs**
fixes #5723

### CODE REVIEW

**Comment by patrickhulce** [comment]
some stats from runs, byte numbers are LH-reported savings, the usual culprits have gone and fixed their minification savings I used to find (yay!), so if you've got good examples, happy to have them :)

| Site | Before | After |
| -- | -- | -- |
| The Verge | <2KB 0ms savings (0.5s) | <2KB 0ms savings (0.2s) | 
| CNN | 3KB 0ms savings (1s) | <2KB 0ms savings (0.5s) |

Instead I used a few libraries during my testing, here's the results

| Library | Predicted Savings Before | Predicted Savings After | Real Savings |
| -- | -- | -- |
| jQuery | 37 KB | 37 KB | 46 KB |
| Angular | 223 KB | 210 KB | 240 KB |
| React | 7 KB | 7 KB | 12 KB |
| Moment | 13 KB | 13 KB | 15 KB|

**Comment by patrickhulce** [comment]
@brendankenny @exterkamp how is this lookin' to you folks?

fine if no opinion, just a bit on the big side to expect no comments ;)

**Comment by brendankenny** [comment]
> candidates for this

we could bring in a dev dependency at a fixed version that we won't ever be using, but could use the contents entirely for smoke testing the CSS/JS tokenizer...

**Comment by patrickhulce** [comment]
> we could bring in a dev dependency at a fixed version that we won't ever be using, but could use the contents entirely for smoke testing the CSS/JS tokenizer...

I like it. What's the biggest, most complex front end dependency we can think of? :)

**Comment by patrickhulce** [comment]
Oh sorry! Was waiting on ideas for smoke test :)

Will do angular in a follow-up if no other suggestions.

**Comment by paulirish** [comment]
sg

**Comment by brendankenny** [comment]
> Was waiting on ideas for smoke test :)

ha, oh yeah, sorry!

**Pull request merged**
