### PR TITLE
Discussion PR: bundle analysis

### PR DESCRIPTION
**Pull request by connorjclark**
I've been working on a few new audits re: bundle analysis. There's a few good breakpoints for dividing this up into smaller PRs, but I wanted to throw this up here to start discussion on some implementation details.

This branch has:

1. #9459 merged in
1. `bundle-duplication` audit
1. `valid-source-maps` audit
1. new detail type for rendering multiple values
1. builds the CDT source map impl. to a commonjs lib

image

image

image

image

## run

```
SIZE_MODE=cdt node lighthouse-cli https://web.dev/ --only-audits=bundle-duplication,valid-source-maps --view # passes

# or use https://www.coursehero.com to see a failing audit

# SIZE_MODE=moz (or don't set at all) will use a different counting impl.
```

## source map implementation

There is the popular `mozilla/source-map`, and there is Chrome DevTool's version. The `bundle-duplication` audit uses this to count how many bytes are mapped to an input source file.

`mozilla/source-map` uses WASM to parse the mappings. CDT is all JS. They run in equivalent times, as far as the usage is `bundle-duplication` is concerned.

To efficiently attribute the byte costs, a `lastGeneratedColumn` is required, which is missing in CDT but exists in `mozilla/source-map`. It was a simple patch, and is something we need to upstream to CDT for @paulirish's CDT bundle visualizer anyhow.

CDT adds 20KB, `mozilla/source-map` adds 49KB.

CDT is written in esmodules, so I've made a build script that transpiles `chrome-devtools-frontend` to commonjs. There were also a few hacks required - there is some global prototype pollution, but I've contained all global scope pollution to a toplevel `globalThis.cdt`.

**Question**: Currently, there is no speed benefit to using CDT, but there is a size benefit. Which should we use?

**Question**: Is there a way to turn off tsc for `lighthouse-core/lib/cdt/generated`?

## `bundle-duplication`

**Question**: I investigated a threshold for byte duplication, since there can be many "0KB"s and that's kinda noisy. I landed on a 100 byte threshold with 0.05 granularity. We could go higher, but there can be a long tail and the sum of all of them can be significant. We could throw them all into a "the rest" item (like font-size does), but that's not actionable. Thoughts?

## multi

`bundle-duplication` reports files (from source maps) that are duplicated, and for each module (normalized to ignore nested `node_modules`) there can be n duplicates. For this audit to be actionable, it must be clear which source file each duplicate comes from. Additionally, each item needs to aggregate the information for a module, such that they can be sorted in the table.

That means we need a column that can contain multiple entries. In the interest of backwards compatibility and not needing to change tons internal of code, I suggest this format:

image

If the header is marked as `multi: true`, then the details renderer will lookup values in `item.multi[key]` and render each. To maintain the interface all the other byte efficiency audits use, the top-level `item.wastedBytes` is the sum of all `multi.wastedBytes`.

The other top-level properties are unnecessary for `bundle-duplication`, but I didn't attempt to tweak the TS interface to drop them entirely. Maybe `ByteEfficiencyItem` could be a union of a `multi` type and a normal one?

**Thoughts?**

## `valid-source-maps`

Surfaces a few things.

* Load errors (map was defined but fetching failed)
* missing sourcesContent (we can punt on this, not used yet)
* script looks like a bundle, but did not define a map (haven't done yet)

I'm also interested in pulling in `source-map-validator` to do some validations, but that isn't critical imo.

**Question**: is a `best-practices` audit the best way to surface this data? It's kinda meta to report, in that lack of this data means other audits can't function. What if those other audits hotlink to this one, if it's missing required data?

### CODE REVIEW

**Comment by patrickhulce** [comment]
Wowza that's a lot of stuff! Very nice! :)

> Currently, there is no speed benefit to using CDT, but there is a size benefit. Which should we use?

I strongly lean CDT if for no other reason than avoiding WASM in our toolchain for now. WASM in the multitude of environments we support is just bound for subtle and not-so-subtle problems IMO.

> Is there a way to turn off tsc for lighthouse-core/lib/cdt/generated?

Can we add `// @ts-nocheck` to the top of the file?

AFAIK even if we put it into the ignore tsconfig section, if it's a transitive dependency of something that *is* typechecked it will get processed regardless.

> I landed on a 100 byte threshold with 0.05 granularity. We could go higher, but there can be a long tail and the sum of all of them can be significant. We could throw them all into a "the rest" item (like font-size does), but that's not actionable. Thoughts?

That sounds very low to me. There's going to be some inevitable duplication of files and it feels like there will be lots of noise with a threshold that low. I agree on the long tail concern though, so is there a way we can aggregate parts and put a larger threshold on that? I'm thinking maybe by folder recognition even if we don't display a treemap in the UI :) 

If I'm being realistic, personally, I'm not going to start splitting my bundles to avoid duplication unless we start talking 20KB+ of savings. The firebase 2KB of duplicated utils is a prime example of something that seems very not useful to surface.

> Thoughts [on multi]?

Is this structure to make it easier to satisfy proto/ts? If I were just considering the freewheelin' js perspective I would expect the values of those properties to just be arrays of the value rather than nested in a separate key, but I understand the appeal of doing it the way you have now for all our other constraints and it seems pretty straightforward so 👍 if that's what you were thinking as well.

> is a best-practices audit the best way to surface this data? It's kinda meta to report, in that lack of this data means other audits can't function. What if those other audits hotlink to this one, if it's missing required data?

Best practices makes sense to me. The other audits could depend on that same computed artifact and warn or be notapplicable based on its result?

-----

Nothing immediately jumps out as show stopping here, so if there's anything else specific you're concerned about on a macro level that changes big decisions here, you'll probably need to pose the appropriate `Thoughts?` question ;) 

Do you have a proposal for the order/dependency graph of landing all of this?

**Comment by patrickhulce** [comment]
Oh I was confused by the potential savings of the bundles though, why is the first one always 0 is that because the bytes have to go somewhere? We should probably just report the non-zero number then.

**Comment by connorjclark** [comment]
> Wowza that's a lot of stuff! Very nice! :)

:D

> I strongly lean CDT if for no other reason than avoiding WASM in our toolchain for now. WASM in the multitude of environments we support is just bound for subtle and not-so-subtle problems IMO.

Agreed.

> Can we add `// @ts-nocheck` to the top of the file?

sweeet that works

> That sounds very low to me. There's going to be some inevitable duplication of files and it feels like there will be lots of noise with a threshold that low. I agree on the long tail concern though, so is there a way we can aggregate parts and put a larger threshold on that? I'm thinking maybe by folder recognition even if we don't display a treemap in the UI :)

Higher threshold + aggregate based on folder name is promising. I'll investigate.

> If I'm being realistic, personally, I'm not going to start splitting my bundles to avoid duplication unless we start talking 20KB+ of savings. The firebase 2KB of duplicated utils is a prime example of something that seems very not useful to surface.

As an example, lodash has many small files, but in total if you duplicate all of lodash across multiple bundles it adds up. Aggregating based on directory (or even `node_modules/{x}`) would avoid issues w/ actionability / noise. 

> Is this structure to make it easier to satisfy proto/ts? If I were just considering the freewheelin' js perspective I would expect the values of those properties to just be arrays of the value rather than nested in a separate key, but I understand the appeal of doing it the way you have now for all our other constraints and it seems pretty straightforward so  if that's what you were thinking as well.

Allowing all things in an `OpprotunityItem` to be `string | string[] | number | number[] | ...` is a breaking change for all consumers, and would shake up a lot of our internal usages.
 
> Best practices makes sense to me. The other audits could depend on that same computed artifact and warn or be notapplicable based on its result?

I'd like a warning with a hotlink to jump to the best-practice audit, so the user can immediately investigate.
 
> Do you have a proposal for the order/dependency graph of landing all of this?

Besides the CDT / multi stuff coming first, it's safe to go in any order.

> Oh I was confused by the potential savings of the bundles though, why is the first one always 0 is that because the bytes have to go somewhere? We should probably just report the non-zero number then.

Yeah, gotta go somewhere. The `URL` column definitely should have all occurrences, because it should be clear where all the usages are.

BTW, I want to show the bytes of each occurrence because if they differ, that is a signal that the modules are different versions.

How about a multi-column for `bytes` that shows the size for all occurrences, and a scalar column for Potential Savings that sums all the occurrences and subtracts one of them?

I failed to mention how the "canonical" occurrence of a module is determined. I'll just paste the comment I made:
```
// One copy of this module is treated as the canonical version - the rest will have
      // non-zero `wastedBytes`. In the case of all copies being the same version, all sizes are
      // equal and the selection doesn't matter. When the copies are different versions, it does
      // matter. Ideally the newest version would be the canonical copy, but version information
      // is not present. Instead, size is used as a heuristic for latest version. This makes the
      // audit conserative in its estimation.
      // TODO: instead, choose the "first" script in the DOM as the canonical?
```

**Comment by connorjclark** [comment]
Aggregate <1KB to `Other` + split byte size / savings columns:

image

**Comment by connorjclark** [comment]
Closing, this has served its purpose.

**Comment by paulirish** [comment]
FWIW I'm super excited about this whole effort! 🎉

**Pull request closed without merging**
