### PR TITLE
Factor report into class

### PR DESCRIPTION
**Pull request by ebidel**
R: all

This looks scarier than it is. It's a small refactor of the main report into a class. The idea is that other views can subclass the main report functionality. This is working towards https://github.com/GoogleChrome/lighthouse/issues/1166 and a cherry pick from https://github.com/GoogleChrome/lighthouse/pull/1169/files. 

Note: `class` and `=>` support is really good theses days, so not worried about any x-browser issues.

### CODE REVIEW

**Comment by brendankenny** [comment]
this looks fine for this purpose, but is there a compelling reason for a class hierarchy? We don't entirely know what perfX is going to look like yet, which leaves us with pretty much the base report and viewer, and aren't they going to be mostly the same eventually?

**Comment by ebidel** [comment]
It isn't hugely compelling atm, but I started to use inheritance in https://github.com/GoogleChrome/lighthouse/pull/1169/files and it led to better organization and modularity and it's nice to be able to override the report functionality elsewhere.

We'll be adding more stuff to the base class, but I think there's value in being able to subclass the main html report. We don't know the shape of perfX, but right now it's adding in extra stuff on top of the report and things are getting messy. Same is true for viewer.

**Comment by ebidel** [comment]
In theory, this is also helpful for consumers of lighthouse who want to extend the report themselves.

**Comment by brendankenny** [comment]
> This looks scarier than it is

good case for adding `?w=1`

**Comment by WeiweiAtGit** [comment]
> cc @WeiweiAtGit to think about the perfx report subclassing LighthouseReport instead of inserting additional scripts :)

Sorry I don't fully understand this : (
How can I subclass `LighthouseReport` without inserting additional scripts?

**Pull request merged**
