### PR TITLE
lock dependency versions

### PR DESCRIPTION
**Pull request by brendankenny**
Locks versions of dependencies in `package.json` to versions already required by the `yarn.lock` files, so they're known working.

Helps with #1327.

### CODE REVIEW

**Comment by paulirish** [comment]
cc @samccone seem right by you?

**Comment by XhmikosR** [comment]
Any reason you don't want to use use `npm shrinkwrap --dev` instead?

**Comment by samccone** [comment]
yeah this will be better, stil :+1: l not a yarn.lock but better :)

**Comment by wardpeet** [comment]
@brendankenny can you run travis without npm cache just to be sure :)

**Comment by brendankenny** [comment]
someone else can take on shrinkwrapping, this was just a super easy way to at least avoid a repeat of the `debug` situation

> can you run travis with clean slate (clear cache)

cache cleared, we'll see how this goes :)

**Pull request merged**
