### PR TITLE
Smokehouse: log out the command we spawn with

### PR DESCRIPTION
**Pull request by paulirish**
image

Handy so you can retry the exact command to debug.

### CODE REVIEW

**Comment by brendankenny** [comment]
is that going to be useful since most rely on the test server running?

**Comment by paulirish** [comment]
well, for this netrecordsComputed branch i was only failing in smokehouse, and no where else.. so i needed to repro the exact situation in order to debug it.

so yes? :)

**Comment by paulirish** [comment]
If you're interested.. also logging the static-server command now: 

image

wdyt?

**Comment by brendankenny** [comment]
I think that's cool, though it's pretty noisy. You couldn't just run `yarn smokehouse` locally?

**Pull request merged**
