### PR TITLE
[WIP] Show emulations in html report

### PR DESCRIPTION
**Pull request by wardpeet**
Show emulation inside the html report.
It still needs some styling but what do you guys think?
**Note:  Started from cpu branch**

image

### CODE REVIEW

**Comment by wardpeet** [comment]
Was thinking that it might be handy for future reference when you share reports. You have 3 flags, disableNetworkThrottle, disableCpuThrottle & disableDeviceEmulation. Which you won't know at a later moment in time

**Comment by brendankenny** [comment]
would fix #568 

I think it's worth having in there, though it's not the prettiest of sidebars :)

**Comment by addyosmani** [comment]
Given the menu is primarily used for navigation, maybe this could work at the top of the main report on the right? I could also see this info being exposed behind a `<details>` under an "Emulation Details" link.

**Comment by wardpeet** [comment]
sure was just a wip :D I can try the details stuff :)

**Comment by wardpeet** [comment]
sure was just a wip :D I can try the details stuff :)

**Comment by paulirish** [comment]
we can close this now..

this stuff is surfaced in the header:
image

**Pull request closed without merging**
