### PR TITLE
core: assert.strict doesn't work in bundles

### PR DESCRIPTION
**Pull request by connorjclark**
partial fix for #10732

### CODE REVIEW

**Comment by brendankenny** [comment]
oops, meant to comment over here

> can we just turn the two `assert.ok` calls into if statements? Don't need a comment then :)

**Comment by brendankenny** [comment]
(sadly zlib is pulling in `assert` so it won't be excised from the bundle)

**Comment by connorjclark** [comment]
how?

critical request:

```
if (!mainResource) {
      return false;
    }
```


idk how to turn `assert.ok(RESOURCE_AGE_IN_HOURS_DECILES.length === 12, 'deciles 0-10 and 1 for overflow');` into an if statement (I guess you meant to return a default value)? return 0? return 1?

**Comment by brendankenny** [comment]
oh, sorry, I didn't mean anything tricky. I really meant an if and a throw. `if (!mainResource) throw new Error('mainResource not provided');` etc

**Pull request merged**
