### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by piperchester**

### CODE REVIEW

**Comment by ebidel** [comment]
According to https://en.oxforddictionaries.com/usage/less-or-fewer, "less" is ok since we're talking about a number (12) with a measurement (characters).

**Comment by patrickhulce** [comment]
[NY Times stylebook also agrees](https://afterdeadline.blogs.nytimes.com/2011/03/01/fewer-vs-less/?_r=0) on this point

**Comment by paulirish** [comment]
cc @kaycebasques this sgty?

**Comment by kaycebasques** [comment]
So long as we effectively transfer the knowledge to our readers, I generally don't worry about stuff like this

IMO either word conveys the essential info

**Comment by piperchester** [comment]
Thanks everyone! 👍

**Pull request merged**
