### PR TITLE
GoogleChrome/lighthouse -> lighthouse

### PR DESCRIPTION
**Pull request by nolanlawson**
seems you managed to nab the "lighthouse" name, so might as well...

### CODE REVIEW

**Comment by nolanlawson** [comment]
I signed it!

**Comment by samccone** [comment]
💥

**Comment by paulirish** [comment]
Ah. I went with the github install so it's always installed from master. 
I don't think we have our npm publishing schedule on track just yet

**Comment by samccone** [comment]
Going to revert for now since we are not on a regular publish schedule yet....

**Pull request merged**
