### PR TITLE
Add related projects section

### PR DESCRIPTION
**Pull request by chrisdwheatley**
This covers #1102 by adding the suggested links to the readme.

### CODE REVIEW

**Comment by chrisdwheatley** [comment]
I signed it!

**Comment by ebidel** [comment]
Thanks for the contribution @chrisdwheatley! 

Wonder what you/others think about enabling the wiki and we can have folks add their projects there? We did something similar for https://github.com/Polymer/polymer/wiki/Who's-using-Polymer%3F.

**Comment by paulirish** [comment]
IMO readme gets like 100x more eyes than wiki. I think we should only move this data to the wiki once we have like > 20 items to put here.

i <3 having this stuff in the readme like this.


@ebidel sgty?

**Comment by paulirish** [comment]
@chrisdwheatley thx for the ez pz contribution! really appreciate it.

looking at https://www.npmjs.com/browse/depended/lighthouse i wonder if there's anything else worth adding. maybe lighthouse-batch?

**Comment by ebidel** [comment]
SG. Can you also add https://github.com/ebidel/lighthouse-hue :)

**Comment by paulirish** [comment]
did a followup commit: https://github.com/GoogleChrome/lighthouse/commit/342398c716ce98fd497a7e7d3dfa64a751f4eb1f

image

**Pull request merged**
