### PR TITLE
Added test suffix to all tests & changed config

### LINKED ISSUE #575: RFC: A few file renames
Proposal for file renames in the codebase:

* All tests like `test/audits/icons.js` get a `-test` filename suffix so: `icons-test.js`
* `config/index.js` to `config/config.js`

I think that may be it. Any others people would like?

### PR DESCRIPTION
**Pull request by wardpeet**
Should fix #575 

Not really a fan of the config/index.js change because now you need to require config/config instead of just config

### CODE REVIEW

**Comment by paulirish** [comment]
> Not really a fan of the config/index.js change because now you need to require config/config instead of just config

Yah. Admittedly the require looks uglier, but this is mostly about the in-editor experience. Having a number of tabs open called "index.js" is hard to work with. And it also slows down cmd-p file navigation... (you mostly have to type `confind` for it to resolve).

**Comment by brendankenny** [comment]
yeah, I prefer it as well. The other benefit is talking about the file (especially if we add another file (like a validator.js or something) in that directory). Much easier to discuss `config.js` than `config/index.js`. That particular file should only used in a few places, so in this case I think the tradeoff is worth it.

**Comment by wardpeet** [comment]
Now I understand and follow the perspective :)

**Comment by paulirish** [comment]
I think we'll land this after the other PRs go in. 

While github appears to think there's a conflict, when I merged locally, I had no problems. So we'll just merge to master ourselves.

**Comment by brendankenny** [comment]
when you do rebase, could you also update the `find` command in `run-mocha.sh` since the unit tests are more easily identifiable now? Could also easily be done in a followup, though

**Comment by wardpeet** [comment]
rebased and updated run-mocha @brendankenny

**Comment by paulirish** [comment]
Had some rebasing to do.
Manually merged
🎈

**Pull request merged**
