### PR TITLE
deps(inquirer): upgrade to 7.3.3

### PR DESCRIPTION
**Pull request by connorjclark**
part of https://github.com/GoogleChrome/lighthouse/issues/10404

fixes 2 of the 5 high severity issues

### CODE REVIEW

**Comment by brendankenny** [comment]
I don't think we have any tests for the inquirer integration, so should manually check it's not automatically enrolling in error reporting due to switching to promises or something.

**Comment by brendankenny** [comment]
(but this PR also isn't updating lodash)

**Comment by brendankenny** [comment]
yarn has actually been lazy here:

https://github.com/GoogleChrome/lighthouse/blob/039b6c6e0826d8b09e145e6ffd5253724b497021/yarn.lock#L5559-L5567

if you delete these lines and re-run `yarn` it'll converge on a single version of `4.17.20` and no need to risk inquirer updates.

**Comment by connorjclark** [comment]
Oh, I did test it manually. You just have to delete the configstore check in `sentry-prompt`. still works the same.

**Comment by brendankenny** [comment]
> Oh, I did test it manually. You just have to delete the configstore check in `sentry-prompt`. still works the same.

yes, no, and timeout? :D

**Comment by connorjclark** [comment]
didn't think to test timeout, just did that now, yup all good.

**Review by adamraine — APPROVED** [review]
LGTM

**Comment by brendankenny** [comment]
> (but this PR also isn't updating lodash)

y'all... :)

**Pull request merged**
