### PR TITLE
Add fancier stuff to default config

### PR DESCRIPTION
**Pull request by ebidel**
R: @patrickhulce all

Not sure if this was intentional. A couple of audits are no longer being run after the switch to the new config.

### CODE REVIEW

**Comment by patrickhulce** [comment]
intentionally left out since they weren't expressed as being carried over to the new report in all the mocks of top level categories, unintentionally forgotten to highlight for discussion :)

I'm personally not the biggest fan of these right now as I believe they're noisy and not drop-in replacements, but I tend to sympathize with the likes of #2022 generally. We should get some proper 'warning'/'info'/'did you know?' styling that makes them not show up as errors 😃

**Comment by ebidel** [comment]
Hmm, I thought we were going to filter. We have UI treatment for `informative: true` audits that we can leverage.

**Comment by brendankenny** [comment]
where did this end up? @paulirish

**Comment by paulirish** [comment]
I'm fine with adding no-consoletime to Best Practices and marking as informative

i think no-datenow should be removed, but we should discuss it in voice.

**Comment by paulirish** [comment]
#2155 is tracking the return of these two

**Pull request closed without merging**
