### PR TITLE
(WIP) gather manifest by intercepting requestAppBanner load

### LINKED ISSUE #83: artifact: fetch manifest based on triggered network request
Calling [`requestAppBanner`](https://chromedevtools.github.io/debugger-protocol-viewer/Page/#method-requestAppBanner) will fetch the manifest, which we can pick up in the network requests record. 

This avoids the DOM dance and make sure we're testing the same manifest that Chrome does.

for now you need `--enable-add-to-shelf` for this to work

### PR DESCRIPTION
**Pull request by brendankenny**
replacement for #137
fixes #83 

When running lighthouse twice with the same Chrome window, the manifest request always times out for me (Canary, 51.0.2702.2), which is obviously a problem for the extension. It works fine for @paulirish (chromium ToT, 51.0.2702.0). Still trying to debug.

Correctly fetching the manifest (the first time) for me with this PR:
- [x] https://airhorner.com
- [x] https://guitar-tuner.appspot.com
- [x] https://jakearchibald.github.io/svgomg/
- [x] http://flipkart.com
- [x] https://voice-memos.appspot.com/
- [ ] https://operasoftware.github.io/pwa-list/

The Opera PWA list is still giving me a `Manifest fetched but unable to retrieve request body for 'https://operasoftware.github.io/pwa-list/.webmanifest' with id 16442.67.` error. Not sure why yet.

### CODE REVIEW

**Comment by paullewis** [comment]
Just started reviewing :)

**Comment by brendankenny** [comment]
Hold off on review, this approach (#83) possibly just won't work.

**Comment by paullewis** [comment]
Just stopped reviewing then :goat:

**Comment by brendankenny** [comment]
Unfortunately won't work. See #157

**Pull request closed without merging**
