### PR TITLE
Smooth scroll

### PR DESCRIPTION
**Pull request by surma**
**DO NOT MERGE OR REVIEW YET**

Implements an audit for 60fps smooth scrolling.

Currently blocked on catapult-project/catapult#2428

### CODE REVIEW

**Comment by paulirish** [comment]
catapult-project/catapult#2428 should now be resolved. We'll have to bump our traceviewer-js dependency (docs in the readme), but otherwise should be in good shape.

**Comment by surma** [comment]
I’ll work on it this week.

**Comment by samccone** [comment]
is this still active? if not perhaps we should close for now

**Comment by surma** [comment]
Closing it for now. Will need to restart anyways.

**Pull request closed without merging**
