### PR TITLE
tests: Upgrade jest to fix current node 11 build

### PR DESCRIPTION
**Pull request by mattzeunert**
[Requiring](https://github.com/GoogleChrome/lighthouse/pull/7312/files#diff-ceee8c863ccea22dff8faff10c2b9d43R9) `jest-mock` [breaks latest Node 11](https://github.com/facebook/jest/pull/8050). Upgrade jest to fix.

Also `jest-mock` should be an explicit dependency if we require it directly.

### CODE REVIEW

**Comment by brendankenny** [comment]
> Requiring jest-mock breaks latest Node 11. Upgrade jest to fix.

ah, nice find!

> Also jest-mock should be an explicit dependency if we require it directly.

do we require it directly? We're running `jest` as a command, I'm assuming it handles injecting mocking into the environment so wouldn't it be an indirect dependency?

**Comment by brendankenny** [comment]
> +1,204 −694 

dear lord,` jest`, what are you doing

**Comment by mattzeunert** [comment]
> do we require it directly? We're running jest as a command, I'm assuming it handles injecting mocking into the environment so wouldn't it be an indirect dependency?

We use it inside mocha for `yarn test-clients`. Is mocha just being phased out or do we use it for a reason?

**Comment by brendankenny** [comment]
> Is mocha just being phased out or do we use it for a reason?

phased out. It should be trivial, but I haven't wanted to sit down and figure out our code coverage situation in `package.json` :)

**Comment by brendankenny** [comment]
> We use it inside mocha for yarn test-clients

including `jest-mock` for this sounds 👍 , all the more motivation for removing `mocha` :)

> The command "yarn unit:silentcoverage" exited with 1.

speaking of having to figure out our code coverage situation :(

**Comment by mattzeunert** [comment]
> The command "yarn unit:silentcoverage" exited with 1.

Does that mean something? Can't repro it on local.

**Comment by mattzeunert** [comment]
My laptop is out of battery and my charger is at the office, so I'll leave this for today. Feel free to clean up my mess 😭

**Comment by paulirish** [comment]
during `nyc report --reporter text-lcov > unit-coverage.lcov` it hits an error: 

```
/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/yargs/yargs.js:1133
      else throw err
           ^
TypeError: Cannot read property 'decl' of undefined
    at /home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:38
    at Array.forEach (<anonymous>)
    at TextLcov.LcovOnlyReport.onDetail (/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at Visitor.(anonymous function) [as onDetail] (/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at /home/travis/build/GoogleChrome/lighthouse/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And the offending line in lcovonly is this one:
https://github.com/istanbuljs/istanbuljs/blob/76069111918d07f35fe831fd6d0ca24982a20303/packages/istanbul-reports/lib/lcovonly/index.js#L31


and yeah thats 3/3 of us that can't repro this locally. :/

**Comment by paulirish** [comment]
travis is green. i guess the travis cache clearing fixed it.

**Pull request merged**
