### PR TITLE
about:blank navigation moved to before gatherer.beforeClass()

### PR DESCRIPTION
**Pull request by brendankenny**
On master, the beginning of a pass goes:
- `beforePass()` on all gatherers
- navigate to `about:blank`, then target url
- `pass()` on all gatherers
- etc

After this PR, each pass will begin:
- navigate to `about:blank`
- `beforePass()` on all gatherers
- navigate to target url
- `pass()` on all gatherers
- etc

### CODE REVIEW

**Comment by paulirish** [comment]
Is this fixing a bug or site in particular?

**Comment by brendankenny** [comment]
It's one way of fixing https://airhorner.com/, for instance, which currently fails the SW check on master. The SW gatherer runs in `beforePass()`, and since that runs *before* we navigate to about:blank and back again, the SW never takes over and it fails. This makes sure we've navigated away before running the next pass.

**Comment by brendankenny** [comment]
I believe it will also fix the smoketests for #578 since it looks like the SWs just never have a chance to get set up for the offline test

**Comment by paulirish** [comment]
Sounds good. Happy to sort the flakiness around our SW stuff.

**Pull request merged**
