### PR TITLE
Introduce raw driver type

### PR DESCRIPTION
**Pull request by pavelfeldman**
This one is based on a bare "port" interface that only has on/send/close methods.

### CODE REVIEW

**Comment by paulirish** [comment]
Oh, this is looking nice. Thanks very much!
It might take us a few to review, but we'll dig in soon.

**Comment by brendankenny** [comment]
Can you give some more context here? Is this a driver for when Lighthouse is run as a panel inside DevTools?

**Comment by pavelfeldman** [comment]
>> Can you give some more context here? Is this a driver for when Lighthouse is run as a panel inside DevTools?

Yes, we intend to use lighthouse in a Web Worker using raw protocol connection (raw is send(message)/dispatch(message) string level. I don't want to extend the Driver in my Worker - such dependency is too heavy, so I implement my own "port" that I feed to the new "raw" driver instead.

A better design would be to replace Driver inheritance with delegate aggregation for connection abstraction. Then all the present driver ancestors would become driver-agnostic "connection" implementations instead of Driver ancestors. Depending on whether you want driver to be able to establish the connection, new connection interface would either have or not have the promisified "connect" method along with the sendCommand.

**Comment by pavelfeldman** [comment]
Let me re-request this once connection is extracted.

**Pull request closed without merging**
