### PR TITLE
core(installable-manifest): icon requirement 192px -> 144px

### PR DESCRIPTION
**Pull request by connorjclark**
part 1 of #6700

### CODE REVIEW

**Comment by patrickhulce** [comment]
Has the 

> after double checking this is 👍 :)

part been satisfied? :)

This has been a very public and very vocal issue (inexplicably IMO 😆) for a long time to change without any PR description or link to how this was confirmed 😉

**Comment by connorjclark** [comment]
https://misc-hoten.surge.sh/lh-6700-manifest/index140.html
https://misc-hoten.surge.sh/lh-6700-manifest/index144.html
https://misc-hoten.surge.sh/lh-6700-manifest/index192.html

Chrome works for all but 140px. Firefox works for all of them.

**Comment by patrickhulce** [comment]
Oh good point. I interpreted @brendankenny's comment to mean it's been blessed by some mixture of PWA stakeholders elsewhere, but maybe he just meant testing functionality confirmation...

**Comment by paulirish** [comment]
i looked at @dominickng's [last comment](https://bugs.chromium.org/p/chromium/issues/detail?id=910880#c8) (from ~13months ago) and verified [in the source](https://cs.chromium.org/chromium/src/chrome/browser/installable/installable_manager.cc) that 144 is still the case.

so we're good on the 192 -> 144 change, still.

**Comment by connorjclark** [comment]
Alls that left is some green checks :)

**Pull request merged**
