### PR TITLE
core(audits): Point a11y audit links to web.dev

### PR DESCRIPTION
**Pull request by mfriesenhahn**
Points "Learn more" links in accessibility audits to relevant web.dev guides.

### CODE REVIEW

**Comment by patrickhulce** [comment]
(You'll need to update our fixtures for tests though @mfriesenhahn, should be running `yarn update:sample-json`)

**Comment by brendankenny** [comment]
@paulirish @egsweeny how do y'all want to handle docs review?

**Comment by mfriesenhahn** [comment]
@brendankenny @patrickhulce I can't seem to make `yarn update:sample-json` happy. I'm getting the following error even though protobuf is installed:
```
$ protoc --python_out=./ ./proto/lighthouse-result.proto && mv ./proto/*_pb2.py ./proto/scripts || (echo "❌ Install protobuf ≥ 3.7.1 to compile the proto file." && false)
$ cd proto/scripts && PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2 python json_roundtrip_via_proto.py
Traceback (most recent call last):
  File "json_roundtrip_via_proto.py", line 5, in <module>
    import lighthouse_result_pb2 as lhr_pb2
  File "/Users/mfriesenhahn/Documents/GitHub/lighthouse/proto/scripts/lighthouse_result_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

mfriesenhahn-macbookpro:lighthouse mfriesenhahn$ protoc --version
libprotoc 3.7.1
```

**Comment by brendankenny** [comment]
I don't know what's causing that, but random searching did come up with the fact that [there may be conflicting versions of protobuf installed](https://stackoverflow.com/a/37905483).

What does `pip list` say for you?

\<\<insert other python environment debugging techniques that I have no clue about>>

cc @exterkamp

**Comment by mfriesenhahn** [comment]
OK, I realized I didn't have the python environment set up correctly, so after some fiddling, here's what I'm getting for `pip list`:
```
Package    Version
---------- -------
pip        19.0.3 
protobuf   3.7.1  
setuptools 40.8.0 
six        1.12.0 
wheel      0.33.1 
```

And here's what I get when I run `yarn update:sample-json`:
```
$ protoc --python_out=./ ./proto/lighthouse-result.proto && mv ./proto/*_pb2.py ./proto/scripts || (echo "❌ Install protobuf ≥ 3.7.1 to compile the proto file." && false)
$ cd proto/scripts && PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2 python json_roundtrip_via_proto.py
✨  Done in 6.58s.
```

I thought I might be good to go since I'm no longer getting a traceback, and three jsons were updated. But after pushing a new commit to the PR, travis still isn't happy. Help is much appreciated--and sorry for the bother.

**Comment by brendankenny** [comment]
> Seems like travis is happy now?

indeed!

**Comment by patrickhulce** [comment]
> @paulirish @egsweeny how do y'all want to handle docs review?

Bump on this, how do y'all want to handle the review here? My expectation would be that the review happens in the web.dev repo, and does not block this PR, but want to double check.

**Comment by patrickhulce** [comment]
Apologies @mfriesenhahn but this will need a rebase.

**Comment by brendankenny** [comment]
the rebase was kind of tricky because of the i18n changes, so I pushed it for you. A diff shows nothing changed (except to the `en-US.json` format, which is expected).

**Comment by patrickhulce** [comment]
SGTM! landing time? 🕐

**Comment by paulirish** [comment]
yup landing this wfm. 

tbh i'll take a closer look at the other categories.

**Comment by mfriesenhahn** [comment]
Thanks, all. I'll continue submitting PRs for the remaining categories as I can squeeze them in :)

**Pull request merged**
