### PR TITLE
tests(smoke): use --debug in github action

### PR DESCRIPTION
**Pull request by connorjclark**
Use `--debug` so log output is printed.

would have helped for #10906

### CODE REVIEW

**Comment by connorjclark** [comment]
not sure why it also prints out the HTML?

**Comment by connorjclark** [comment]
oh b/c `MainDocumentContent` is an expectation in dbw. hmmmm.

**Comment by connorjclark** [comment]
> "use --debug for more info"

wouldn't help if the failure mode is only in CI.

yea i'd really like this in the default CI run

**Comment by brendankenny** [comment]
> wouldn't help if the failure mode is only in CI.

Right, it would tell you to add `--debug` in that case. The tradeoff is having an extra commit to do that in the very rare case something like this happens vs 1000 extra lines of logging in the every-other-time case :)

**Pull request merged**
