### PR TITLE
Changes scheduler to be more generic

### PR DESCRIPTION
**Pull request by paullewis**
Right now the gatherers are set to run at specific points, meaning a relatively tight coupling of gatherers and scheduler. This PR refactors the scheduler to expect every gatherer to have only four methods: `setup`, `beforePass`, `pass`, `afterPass`, and `tearDown`.

The idea being that we can iterate on this and allow multiple passes to be encoded in a .lighthouserc file (the PR includes a default.json file, though I figure the naming here can change). This should also open up the path to having custom plugins/gatherers where someone can specify a path with additional gatherers that they want to run, along with their config, i.e.

```json
{
  "passes": [{
    "trace": true,
    "gatherers": [
       "myCustomGatherer"
    ]
  }]
}
```

But I think we should also look at folding in audits to this config, and we'll need a way to sort out reports off the back of it. This PR, however, is primarily focussed on picking apart the coupling that we have in place.

### CODE REVIEW

**Comment by brendankenny** [comment]
Reading through this I really like large parts of it so far—the pass regularization instead of having to write multiple one-off passes, getting the artifact names from the gatherers instead of having yet another property—but this really needs to be split into a few PRs to be able to review. As is, it's difficult to mentally isolate the changes from each other and it's difficult to consider the effects of each change on existing (unchanging) code with so many changes happening at once.

I'd also like a little time on the proposal in #415 before moving on the config part of this change. It's a big change and one I'd like to consider first (like with a design doc :). I have some comments on it (and this PR by extension) that I'll add in that issue.

**Comment by paullewis** [comment]
@paulirish Sure.

@brendankenny I hear you, but the reason it's one PR is that the changes cascaded. I only set out to genericise the scheduler, but it easily cascaded to the other changes. Most of the changes are clerical ones about names of properties and such.

**Comment by brendankenny** [comment]
Most of the changes are fairly well contained: normalization of passes, read gathers from config, read audits from config, read aggregations from config, artifact renaming, etc. Each of those are obviously related, yes, but each has knock-on effects that are much easier to review individually. It's 4500 changed lines in 124 files; even if half of that were property name changes, nothing about that says indicates a simple refactor or makes it simple to review

**Comment by paullewis** [comment]
I know it's big, but it's all related :) Also you seem to have a great handle on what the PR contains :D

/me ducks

**Pull request merged**
