### PR TITLE
Adds closure annotations to aggregators.

### PR DESCRIPTION
**Pull request by brendankenny**
rebased and last tweaks for #123

Closes #123

### CODE REVIEW

**Comment by samccone** [comment]
squash an go :ship:

**Comment by paulirish** [comment]
I green buttoned too fast. Didn't squash. 

Sorry :(

**Comment by samccone** [comment]
................

**Comment by samccone** [comment]
-1

**Comment by brendankenny** [comment]
you can green button -> "confirm squash and merge" in the github UI now :)

But careful you don't squash if the commits really should be separate.

**Pull request merged**
