### PR TITLE
eslint: no longer ignore all of lighthouse-extension

### PR DESCRIPTION
**Pull request by paulirish**
We had all of the extension ignored in eslintignore.

Now we exclude only the compiled bits.

### CODE REVIEW

**Comment by brendankenny** [comment]
wasn't this on purpose? #482

**Comment by paulirish** [comment]
> wasn't this on purpose? #482
>> right now npm run lint is running over code in lighthouse-extension/, which is fine if you've never built the extension before (like on travis, where the extension is built last), but fails if you have built it.

It was failing because `app/scripts` was included (which has the browserified payload).

This PR blacklists both app/scripts and dist.

**Comment by brendankenny** [comment]
ah, yeah. Still kind of weird because lighthouse-extension/ has its own .eslintrc, lint task, etc.

I think you may need to rebase against master to pass the tests

**Comment by brendankenny** [comment]
So maybe just sort out the `.eslintrc` and `lighthouse-extension/.eslintrc` (with the few differences like node vs browser) and the `devDependencies`. Not sure how best we want to do this

**Comment by paulirish** [comment]
all set

**Comment by brendankenny** [comment]
📝 🔍 ✔️

**Pull request merged**
