### PR TITLE
misc: preserve error stack when using promise timeout

### LINKED ISSUE #13332: Preserve error stack when timing out a promise
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

not applicable

### What happened?

There is a typical technique to create a timeable promise via `Promise.race`. The `lighthouse-core` uses it in several places:

https://github.com/GoogleChrome/lighthouse/blob/68ba77acbc9c22512b93d213b23b05cca443dda4/lighthouse-core/fraggle-rock/gather/session.js#L145-L164

https://github.com/GoogleChrome/lighthouse/blob/68ba77acbc9c22512b93d213b23b05cca443dda4/lighthouse-core/gather/driver.js#L334-L355

https://github.com/GoogleChrome/lighthouse/blob/68ba77acbc9c22512b93d213b23b05cca443dda4/lighthouse-core/gather/fetcher.js#L193-L214

Each implementation listed above has a flaw, preventing to preserve the stack of the error if it's thrown. Example:

```
LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver.js:343:21)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.enable)',
  lhrRuntimeError: true,
  protocolMethod: 'Page.enable'
}
```

In all cases, the new instance is created within the `setTimeout` callback and the only available stack for each such error is:

```
    at Timeout.<anonymous> (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver.js:343:21)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
```

### What did you expect?

The error object should be constructed outside the `setTimeout` callback to preserve the call stack.

```
LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at /crawler/node_modules/lighthouse/lighthouse-core/gather/driver.js:341:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver.js:339:28)
    at Driver.sendCommand (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver.js:363:17)
    at ExecutionContext._evaluateInContext (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:109:42)
    at ExecutionContext.evaluateAsync (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:146:25)
    at ExecutionContext.evaluate (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:178:17)
    at getBenchmarkIndex (/crawler/node_modules/lighthouse/lighthouse-core/gather/driver/environment.js:54:43)
    at Function.run (/crawler/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:469:44)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)',
  lhrRuntimeError: true,
  protocolMethod: 'Runtime.evaluate'
}
```

### What have you tried?

_No response_

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.6.0

### Chrome Version

chrome-stable--91.0.4472.114-amd64.deb

### Node Version

v15.2.1

### OS

```
Linux 702400aa3abf 4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 x86_64 GNU/Linux
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BR0kEN-**
https://github.com/GoogleChrome/lighthouse/issues/13332

### CODE REVIEW

**Comment by adamraine** [comment]
This looks good! While you're here, I think there is one more usage of error timeout that we can upgrade:
https://github.com/GoogleChrome/lighthouse/blob/68ba77acbc9c22512b93d213b23b05cca443dda4/lighthouse-cli/run.js#L175-L179

**Comment by BR0kEN-** [comment]
Yeah, true, I was searching across `lighthouse-core` only. Give me a couple of mins.

**Review by adamraine — APPROVED** [review]

**Comment by BR0kEN-** [comment]
All failed checks seem to be unrelated to changes. What are the next actions @adamraine?

**Comment by adamraine** [comment]
Correct, failed checks are unrelated. https://github.com/GoogleChrome/lighthouse/pull/13342 should fix the smoke failure, after that we can land this.

**Pull request merged**
