### PR TITLE
report(redesign): remove units from table columns

### PR DESCRIPTION
**Pull request by Hoten**
#8185

### CODE REVIEW

**Comment by brendankenny** [comment]
before/after screenshot?

**Comment by Hoten** [comment]
before
image
after
image

**Comment by exterkamp** [comment]
> LGTM. We need to sync this ASAP if we want it within a week. But the not so bad news is that the other locales will just say "X (ms)" instead of just "X" so it's not crazy critical.

Oh how naive I was.  This breaks tc/ :laughing:

**Comment by patrickhulce** [comment]
*breaks* tc? How!?

**Pull request merged**
