### PR TITLE
Trace buckets

### PR DESCRIPTION
**Pull request by surma**
Here we go again 🙄

I must have reverted the changed from `driver/index.js` during one of the rebases. Since unit tests work in isolation, tests for gatherers/audits and driver were passing, but didn’t work together in the CLI. 

PTAL :)

### CODE REVIEW

**Comment by surma** [comment]
Re-ran the tests with #534 having been merged :)

**Comment by paulirish** [comment]
I'm seeing -1 results for our perf stuff with this PR.

image

And back on master i'm getting results. Just doing a basic run with `lighthouse http://paulirish.com`

**Comment by surma** [comment]
Thanks for keeping an eye out. Seems like I can’t see the forest for the trees. Will investigate.

**Comment by surma** [comment]
PTAL. I think I got it all now, but you know,…

**Comment by paulirish** [comment]
Thanks for all your work on this. 🎆   
landed.

**Pull request merged**
