### PR TITLE
docs(readme): add Ryte to the list of integrations

### PR DESCRIPTION
**Pull request by dannylinden**
Would like to add [Ryte](https://en.ryte.com/) to the list of services since we using Lighthouse in our main product to show performance insights across the user domains. Lighthouse is also available in our free plan

### CODE REVIEW

**Comment by dannylinden** [comment]
@googlebot I fixed it

**Comment by patrickhulce** [comment]
Hi @dannylinden thanks for the PR!

To be honest, this makes me uncomfortable to add here. 

- "Lighthouse" is nowhere to be found in the text of any of the marketing pages I looked at and Performance appears to be a tertiary concern for the product, very much unlike all the other services in the "Web Perf Services" section. 
- You've placed yourself 3rd in the list (1st among all paid options, including many of which *actually* focus on performance, contribute back to the core library, and feature Lighthouse prominently in their descriptions). 
- Ryte's Free option is *very* buried (not even mentioned in the pricing table, hidden behind a disclosure FAQ) and does not appear to be taken seriously (see bug in screenshot)
image

Seems like a great product and all, but not one that appears to deserve prime placement in the *Lighthouse* README. If Ryte would like to make a good faith effort to address these concerns, I could see it living in the other integrations section, but I'll defer to @paulirish for a final decision on it.

**Comment by patrickhulce** [comment]
> its visible in the most prominent area of our homepage, see attached screenshot:

Awesome! Apologies I didn't click that one, I clicked the "Test it for free" on the Pricing page and assumed the homepage one led to the same trial rather than the free edition, but glad to hear it's a priority :)

> We take it very serious i think If I can use our webpagetest results as witness:
https://www.webpagetest.org/result/211007_AiDcQB_f0804bc2868a29f4c1ca85c423205e2f/

Sorry for the miscommunication. The performance of the site feels fine :) (although when using webpagetest links to make a performance point, I'd suggest using settings a little more difficult than desktop + cable 😉 ) I meant the positioning of the product does not emphasize Performance monitoring as its primary goal. Feels similar to the AwesomeTechStack product in "Non-Web Perf Services" section in this respect, but if the prominence is reduced I think this is fine.

Regarding the lack of "Lighthouse", I'm just curious if there was a specific reason that the site avoids referencing Lighthouse directly?

**Comment by dannylinden** [comment]
@patrickhulce thanks for quick reply, its moved now to the bottom of non-perf 👍

**Pull request closed without merging**
