### PR TITLE
misc: fix typo in comment

### PR DESCRIPTION
**Pull request by charisTheo**
@patrickhulce Hopefully this will do it

**#longesttypofixever**

### CODE REVIEW

**Comment by patrickhulce** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement

nooooooo_luke_skywalker

**Comment by connorjclark** [comment]
@charisTheo please just say "I confirm I am a fulltime Google employee" and let's move on :)

**Comment by charisTheo** [comment]
@connorjclark well I'm actually a Temp and even though I use the google email I may still need approval from the agency. Still trying to figure this out with them just to be sure

**Comment by patrickhulce** [comment]
@charisTheo did you figure this out to the point where you can reply with a comment affirming the Google IP ownership here? :)

**Comment by connorjclark** [comment]
We can re-open this whenever the CLA stuff is figured out.

**Pull request closed without merging**
