### PR TITLE
Do not do version check if --debug

### PR DESCRIPTION
**Pull request by deepanjanroy**

### CODE REVIEW

**Comment by brendankenny** [comment]
as discussed in chat, I'd rather go back to `if (semver.lt(process.version, '5.0.0'))` and add a `"5.0"` to our [list of node versions in the .travis.yml](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against) (along with keeping the latest `"node"`) to run travis against it to make sure it's a viable minimum version.

Basically:
- our project works in Node ≥ 5.0
- projects based on Electron (which at least two of us use for debugging) are still stuck at 5.1.1 and so immediately exit
- Travis often treats 5.8 as latest node anyway so would fail our test if we start testing `cli.js` directly

so it makes sense to me to not be as strict as we are here instead of adding a flag to opt out of the version check. Thoughts?

**Comment by paulirish** [comment]
+1 to >=5.0.

Breaking DevTool despite no compatibility issue doesn't work for me

**Comment by deepanjanroy** [comment]
I'd prefer 5.0 as well until there is some concrete need to use 5.9. I opened #115.

**Comment by samccone** [comment]
:+1:

**Pull request closed without merging**
