### PR TITLE
Handles ports for SW.

### LINKED ISSUE #532: ServiceWorker origin matching doesn't consider ports
Which means a SW for localhost:8080 is gonna get "matched" for a site on localhost:3000.

Yikes

Should be an easy fix, obv.

### PR DESCRIPTION
**Pull request by paullewis**
SW check needs ports.

Fixes #532

### CODE REVIEW

**Comment by paulirish** [comment]
If you're up for it we could use whatwg-url package to normalize our url parsing everywhere.
It can also be added to our browserify excludes.

Here's it in action:

https://tonicdev.com/5798e3b9edc3e41200aaa828/5798f15349cba51300e86a05

**Comment by wardpeet** [comment]
For the few times we use url parsing I wouldn't introduce a new dependency

**Comment by paullewis** [comment]
I'm undecided. Browserify already polyfills node's URL parsing IIRC, so we're consistent if less good than I'd like. I kinda agree with @wardpeet about not introducing a new dep at this stage, though as these things go it's pretty small and that.

**Comment by brendankenny** [comment]
@zhaoz would have to update for this dep too, and he just got done with all that :)

**Comment by paulirish** [comment]
Aiight. sg.

**Pull request merged**
