### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by Janpot**
Browserify selects correct version automatically.
also `log.color = undefined` seems to be problematic in the latest version of `debug`.
fixes https://github.com/GoogleChrome/lighthouse/issues/1228
fixes https://github.com/GoogleChrome/lighthouse/issues/1261

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please note that this doesn't fix https://github.com/GoogleChrome/lighthouse/issues/1228 completely so better remove that from the description. There's still the issue with some unicode characters not displaying correctly on Windows. See https://github.com/GoogleChrome/lighthouse/issues/1228#issuecomment-268741410

**Comment by Janpot** [comment]
Seems like two unrelated issues to me. 
You might want to take a look at https://github.com/sindresorhus/figures. I'm not on a Windows machine so it's a bit hard to test for me.

**Comment by XhmikosR** [comment]
Well, not unrelated since the console output is one thing and is still broken.

I could make another issue, but still, the issue existed before this PR.

**Comment by XhmikosR** [comment]
BTW, thanks for the link to figures, it seems it will do the job so I'll do some testing and put together a PR.

Would be nice if we had #1079 sorted to actually test things on Windows.

**Comment by XhmikosR** [comment]
Also, we might as well use chalk for colors and simplify cli a bit.

**Comment by ebidel** [comment]
Thanks for the PR @Janpot. We'll take your changes in https://github.com/GoogleChrome/lighthouse/pull/1307 and make sure it's a merge and not a squash :)

**Pull request closed without merging**
