### PR TITLE
misc: use cache in workflow

### PR DESCRIPTION
**Pull request by jongwooo**
Signed-off-by: jongwooo <jongwooo.han@gmail.com>

## Summary

Updated workflows to cache dependencies using [actions/setup-node](https://github.com/actions/setup-node#caching-global-packages-data). `setup-node@v3` or newer has caching **built-in**.

### About caching workflow dependencies
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.

### Solutions
Node.js projects can run faster on GitHub Actions by enabling dependency caching on the [setup-node](https://github.com/actions/setup-node) action.

### AS-IS

```yaml
- name: Use Node.js 16.x
  uses: actions/setup-node@v1
  with:
    node-version: 16.x
```

### TO-BE

```yml
- name: Use Node.js 16.x
  uses: actions/setup-node@v3
  with:
    node-version: 16.x
    cache: yarn
```

> It’s literally a one line change to pass the `cache: yarn` input parameter.

## Related Issues/PRs
N/A

## References

- [https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
- [https://thearchivelog.dev/article/caching-dependencies-to-speed-up-workflows/](https://thearchivelog.dev/article/caching-dependencies-to-speed-up-workflows/)

### CODE REVIEW

**Comment by connorjclark** [comment]
I think you're missing something here, but I don't know what. Please see the failures in CI.

**Comment by jongwooo** [comment]
@connorjclark Thank you for your comment! I accidentally forgot to change the version of `setup-node` to v3 in `package-test.yml`

**Comment by connorjclark** [comment]
Well everything else is failing, though.

**Comment by connorjclark** [comment]
In general this is going to be more work than the typical use case, because in some of our workflows (devtools.yml) install in a subfolder of the github workspace, so `cache-dependency-path` needs to be set.

If this is something you want to help us with, I suggest iterating on a fork and running the actions their locally first.

**Comment by connorjclark** [comment]
Because right now I need to keep hitting this button to use _our_ github actions to verify your changes, this is too much back/forth for the PR not currently in a working state.

image


This change would be great (we often get yarn install timeout, so a cache would help there)–but let's close this PR until this is ready and verified in your fork's CI. Please re-open when ready, thanks!

**Comment by connorjclark** [comment]
example failures btw: 

https://github.com/GoogleChrome/lighthouse/actions/runs/3735210285/jobs/6338446824
https://github.com/GoogleChrome/lighthouse/actions/runs/3735210291/jobs/6338446953

**Pull request closed without merging**
