### PR TITLE
[WIP] Fix summary tag in FF

### PR DESCRIPTION
**Pull request by ev1stensberg**
Need feedback on this

Fix for #2385

### CODE REVIEW

**Comment by ebidel** [comment]
Looks the default details arrow is coming back in https://github.com/GoogleChrome/lighthouse/pull/2297. This PR may be moot.

**Comment by ev1stensberg** [comment]
No worries! Remember to close #2385 too once this is redundant!

**Comment by ebidel** [comment]
Cool. Going to close in favor of #2297.

**Comment by ev1stensberg** [comment]
Just realized that we could have used 'moz-box-shadow' for the background. If the Mozilla bug still stands after #2297  I can make a fix

**Pull request closed without merging**
