### PR TITLE
deps: add @types/yargs-parser

### PR DESCRIPTION
**Pull request by connorjclark**
resolves issue found in another PR: https://github.com/GoogleChrome/lighthouse/pull/11271#issuecomment-700203190

### CODE REVIEW

**Review by patrickhulce — APPROVED** [review]
looks like they flipped to typescript at v19.x.x we could benefit from on update :)

LGTM for problem at hand though 👍

**Comment by brendankenny** [comment]
The latest types have probably drifted quite a bit from our `yargs@3.32.0`, but looks like they'll probably be closer than those three year old types it looks like _someone_ threw together in about 30 seconds :)

**Comment by patrickhulce** [comment]
> The latest types have probably drifted quite a bit from our yargs@3.32.0

These are for yargs*-parser* though which is at 18.3.1, no?

**Comment by brendankenny** [comment]
> These are for yargs*-parser* though which is at 18.1.3, no?

Oh, right. Well the three year old types were still useless, but yeah, we probably should have just updated since we already broke the seal in #10723. Oh well :)

**Pull request merged**
